// Code generated by go-swagger; DO NOT EDIT.

package messages

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewMessagesV2GetPredocumentParams creates a new MessagesV2GetPredocumentParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewMessagesV2GetPredocumentParams() *MessagesV2GetPredocumentParams {
	return NewMessagesV2GetPredocumentParamsWithTimeout(cr.DefaultTimeout)
}

// NewMessagesV2GetPredocumentParamsWithTimeout creates a new MessagesV2GetPredocumentParams object
// with the ability to set a timeout on a request.
func NewMessagesV2GetPredocumentParamsWithTimeout(timeout time.Duration) *MessagesV2GetPredocumentParams {
	return &MessagesV2GetPredocumentParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewMessagesV2GetPredocumentParamsWithContext creates a new MessagesV2GetPredocumentParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [MessagesV2GetPredocumentParams].
func NewMessagesV2GetPredocumentParamsWithContext(ctx context.Context) *MessagesV2GetPredocumentParams {
	return &MessagesV2GetPredocumentParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewMessagesV2GetPredocumentParamsWithHTTPClient creates a new MessagesV2GetPredocumentParams object
// with the ability to set a custom HTTPClient for a request.
func NewMessagesV2GetPredocumentParamsWithHTTPClient(client *http.Client) *MessagesV2GetPredocumentParams {
	return &MessagesV2GetPredocumentParams{
		HTTPClient: client,
	}
}

/*
MessagesV2GetPredocumentParams contains all the parameters to send to the API endpoint

	for the messages v2 get predocument operation.

	Typically these are written to a http.Request.
*/
type MessagesV2GetPredocumentParams struct {

	/* DocumentID.

	   The unique ID of the document.
	*/
	DocumentID string

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the messages v2 get predocument params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *MessagesV2GetPredocumentParams) WithDefaults() *MessagesV2GetPredocumentParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the messages v2 get predocument params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *MessagesV2GetPredocumentParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the messages v2 get predocument params.
func (o *MessagesV2GetPredocumentParams) WithTimeout(timeout time.Duration) *MessagesV2GetPredocumentParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the messages v2 get predocument params.
func (o *MessagesV2GetPredocumentParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the messages v2 get predocument params.
//
// Deprecated: use the operation call with context to pass the context instead of [MessagesV2GetPredocumentParams].
func (o *MessagesV2GetPredocumentParams) WithContext(ctx context.Context) *MessagesV2GetPredocumentParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the messages v2 get predocument params.
//
// Deprecated: use the operation call with context to pass the context instead of [MessagesV2GetPredocumentParams].
func (o *MessagesV2GetPredocumentParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the messages v2 get predocument params.
func (o *MessagesV2GetPredocumentParams) WithHTTPClient(client *http.Client) *MessagesV2GetPredocumentParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the messages v2 get predocument params.
func (o *MessagesV2GetPredocumentParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDocumentID adds the documentID to the messages v2 get predocument params.
func (o *MessagesV2GetPredocumentParams) WithDocumentID(documentID string) *MessagesV2GetPredocumentParams {
	o.SetDocumentID(documentID)
	return o
}

// SetDocumentID adds the documentId to the messages v2 get predocument params.
func (o *MessagesV2GetPredocumentParams) SetDocumentID(documentID string) {
	o.DocumentID = documentID
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *MessagesV2GetPredocumentParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	// path param documentId
	if err := r.SetPathParam("documentId", o.DocumentID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
