// Code generated by go-swagger; DO NOT EDIT.

package messages

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewMessagesV2GetDocumentParams creates a new MessagesV2GetDocumentParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewMessagesV2GetDocumentParams() *MessagesV2GetDocumentParams {
	return NewMessagesV2GetDocumentParamsWithTimeout(cr.DefaultTimeout)
}

// NewMessagesV2GetDocumentParamsWithTimeout creates a new MessagesV2GetDocumentParams object
// with the ability to set a timeout on a request.
func NewMessagesV2GetDocumentParamsWithTimeout(timeout time.Duration) *MessagesV2GetDocumentParams {
	return &MessagesV2GetDocumentParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewMessagesV2GetDocumentParamsWithContext creates a new MessagesV2GetDocumentParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [MessagesV2GetDocumentParams].
func NewMessagesV2GetDocumentParamsWithContext(ctx context.Context) *MessagesV2GetDocumentParams {
	return &MessagesV2GetDocumentParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewMessagesV2GetDocumentParamsWithHTTPClient creates a new MessagesV2GetDocumentParams object
// with the ability to set a custom HTTPClient for a request.
func NewMessagesV2GetDocumentParamsWithHTTPClient(client *http.Client) *MessagesV2GetDocumentParams {
	return &MessagesV2GetDocumentParams{
		HTTPClient: client,
	}
}

/*
MessagesV2GetDocumentParams contains all the parameters to send to the API endpoint

	for the messages v2 get document operation.

	Typically these are written to a http.Request.
*/
type MessagesV2GetDocumentParams struct {

	/* DocumentID.

	   The unique ID of the document.
	*/
	DocumentID string

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the messages v2 get document params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *MessagesV2GetDocumentParams) WithDefaults() *MessagesV2GetDocumentParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the messages v2 get document params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *MessagesV2GetDocumentParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the messages v2 get document params.
func (o *MessagesV2GetDocumentParams) WithTimeout(timeout time.Duration) *MessagesV2GetDocumentParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the messages v2 get document params.
func (o *MessagesV2GetDocumentParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the messages v2 get document params.
//
// Deprecated: use the operation call with context to pass the context instead of [MessagesV2GetDocumentParams].
func (o *MessagesV2GetDocumentParams) WithContext(ctx context.Context) *MessagesV2GetDocumentParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the messages v2 get document params.
//
// Deprecated: use the operation call with context to pass the context instead of [MessagesV2GetDocumentParams].
func (o *MessagesV2GetDocumentParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the messages v2 get document params.
func (o *MessagesV2GetDocumentParams) WithHTTPClient(client *http.Client) *MessagesV2GetDocumentParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the messages v2 get document params.
func (o *MessagesV2GetDocumentParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDocumentID adds the documentID to the messages v2 get document params.
func (o *MessagesV2GetDocumentParams) WithDocumentID(documentID string) *MessagesV2GetDocumentParams {
	o.SetDocumentID(documentID)
	return o
}

// SetDocumentID adds the documentId to the messages v2 get document params.
func (o *MessagesV2GetDocumentParams) SetDocumentID(documentID string) {
	o.DocumentID = documentID
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *MessagesV2GetDocumentParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	// path param documentId
	if err := r.SetPathParam("documentId", o.DocumentID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
