// Code generated by go-swagger; DO NOT EDIT.

package messages

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/jabbrwcky/paperless-bank/internal/bank/comdirect/models"
)

// MessagesV2GetDocumentReader is a Reader for the MessagesV2GetDocument structure.
type MessagesV2GetDocumentReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *MessagesV2GetDocumentReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 404:
		result := NewMessagesV2GetDocumentNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewMessagesV2GetDocumentUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewMessagesV2GetDocumentInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 503:
		result := NewMessagesV2GetDocumentServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /messages/v2/documents/{documentId}] messagesV2GetDocument", response, response.Code())
	}
}

// NewMessagesV2GetDocumentNotFound creates a MessagesV2GetDocumentNotFound with default headers values
func NewMessagesV2GetDocumentNotFound() *MessagesV2GetDocumentNotFound {
	return &MessagesV2GetDocumentNotFound{}
}

/*
MessagesV2GetDocumentNotFound describes a response with status code 404, with default header values.

Not Found
*/
type MessagesV2GetDocumentNotFound struct {
}

// IsSuccess returns true when this messages v2 get document not found response has a 2xx status code
func (o *MessagesV2GetDocumentNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this messages v2 get document not found response has a 3xx status code
func (o *MessagesV2GetDocumentNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this messages v2 get document not found response has a 4xx status code
func (o *MessagesV2GetDocumentNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this messages v2 get document not found response has a 5xx status code
func (o *MessagesV2GetDocumentNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this messages v2 get document not found response a status code equal to that given
func (o *MessagesV2GetDocumentNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the messages v2 get document not found response
func (o *MessagesV2GetDocumentNotFound) Code() int {
	return 404
}

func (o *MessagesV2GetDocumentNotFound) Error() string {
	return fmt.Sprintf("[GET /messages/v2/documents/{documentId}][%d] messagesV2GetDocumentNotFound", 404)
}

func (o *MessagesV2GetDocumentNotFound) String() string {
	return fmt.Sprintf("[GET /messages/v2/documents/{documentId}][%d] messagesV2GetDocumentNotFound", 404)
}

func (o *MessagesV2GetDocumentNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewMessagesV2GetDocumentUnprocessableEntity creates a MessagesV2GetDocumentUnprocessableEntity with default headers values
func NewMessagesV2GetDocumentUnprocessableEntity() *MessagesV2GetDocumentUnprocessableEntity {
	return &MessagesV2GetDocumentUnprocessableEntity{}
}

/*
MessagesV2GetDocumentUnprocessableEntity describes a response with status code 422, with default header values.

Unprocessable Entity
*/
type MessagesV2GetDocumentUnprocessableEntity struct {
	Payload *models.StandardErrorResponse
}

// IsSuccess returns true when this messages v2 get document unprocessable entity response has a 2xx status code
func (o *MessagesV2GetDocumentUnprocessableEntity) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this messages v2 get document unprocessable entity response has a 3xx status code
func (o *MessagesV2GetDocumentUnprocessableEntity) IsRedirect() bool {
	return false
}

// IsClientError returns true when this messages v2 get document unprocessable entity response has a 4xx status code
func (o *MessagesV2GetDocumentUnprocessableEntity) IsClientError() bool {
	return true
}

// IsServerError returns true when this messages v2 get document unprocessable entity response has a 5xx status code
func (o *MessagesV2GetDocumentUnprocessableEntity) IsServerError() bool {
	return false
}

// IsCode returns true when this messages v2 get document unprocessable entity response a status code equal to that given
func (o *MessagesV2GetDocumentUnprocessableEntity) IsCode(code int) bool {
	return code == 422
}

// Code gets the status code for the messages v2 get document unprocessable entity response
func (o *MessagesV2GetDocumentUnprocessableEntity) Code() int {
	return 422
}

func (o *MessagesV2GetDocumentUnprocessableEntity) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /messages/v2/documents/{documentId}][%d] messagesV2GetDocumentUnprocessableEntity %s", 422, payload)
}

func (o *MessagesV2GetDocumentUnprocessableEntity) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /messages/v2/documents/{documentId}][%d] messagesV2GetDocumentUnprocessableEntity %s", 422, payload)
}

func (o *MessagesV2GetDocumentUnprocessableEntity) GetPayload() *models.StandardErrorResponse {
	return o.Payload
}

func (o *MessagesV2GetDocumentUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StandardErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewMessagesV2GetDocumentInternalServerError creates a MessagesV2GetDocumentInternalServerError with default headers values
func NewMessagesV2GetDocumentInternalServerError() *MessagesV2GetDocumentInternalServerError {
	return &MessagesV2GetDocumentInternalServerError{}
}

/*
MessagesV2GetDocumentInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type MessagesV2GetDocumentInternalServerError struct {
}

// IsSuccess returns true when this messages v2 get document internal server error response has a 2xx status code
func (o *MessagesV2GetDocumentInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this messages v2 get document internal server error response has a 3xx status code
func (o *MessagesV2GetDocumentInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this messages v2 get document internal server error response has a 4xx status code
func (o *MessagesV2GetDocumentInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this messages v2 get document internal server error response has a 5xx status code
func (o *MessagesV2GetDocumentInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this messages v2 get document internal server error response a status code equal to that given
func (o *MessagesV2GetDocumentInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the messages v2 get document internal server error response
func (o *MessagesV2GetDocumentInternalServerError) Code() int {
	return 500
}

func (o *MessagesV2GetDocumentInternalServerError) Error() string {
	return fmt.Sprintf("[GET /messages/v2/documents/{documentId}][%d] messagesV2GetDocumentInternalServerError", 500)
}

func (o *MessagesV2GetDocumentInternalServerError) String() string {
	return fmt.Sprintf("[GET /messages/v2/documents/{documentId}][%d] messagesV2GetDocumentInternalServerError", 500)
}

func (o *MessagesV2GetDocumentInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewMessagesV2GetDocumentServiceUnavailable creates a MessagesV2GetDocumentServiceUnavailable with default headers values
func NewMessagesV2GetDocumentServiceUnavailable() *MessagesV2GetDocumentServiceUnavailable {
	return &MessagesV2GetDocumentServiceUnavailable{}
}

/*
MessagesV2GetDocumentServiceUnavailable describes a response with status code 503, with default header values.

Service Unavailable
*/
type MessagesV2GetDocumentServiceUnavailable struct {
}

// IsSuccess returns true when this messages v2 get document service unavailable response has a 2xx status code
func (o *MessagesV2GetDocumentServiceUnavailable) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this messages v2 get document service unavailable response has a 3xx status code
func (o *MessagesV2GetDocumentServiceUnavailable) IsRedirect() bool {
	return false
}

// IsClientError returns true when this messages v2 get document service unavailable response has a 4xx status code
func (o *MessagesV2GetDocumentServiceUnavailable) IsClientError() bool {
	return false
}

// IsServerError returns true when this messages v2 get document service unavailable response has a 5xx status code
func (o *MessagesV2GetDocumentServiceUnavailable) IsServerError() bool {
	return true
}

// IsCode returns true when this messages v2 get document service unavailable response a status code equal to that given
func (o *MessagesV2GetDocumentServiceUnavailable) IsCode(code int) bool {
	return code == 503
}

// Code gets the status code for the messages v2 get document service unavailable response
func (o *MessagesV2GetDocumentServiceUnavailable) Code() int {
	return 503
}

func (o *MessagesV2GetDocumentServiceUnavailable) Error() string {
	return fmt.Sprintf("[GET /messages/v2/documents/{documentId}][%d] messagesV2GetDocumentServiceUnavailable", 503)
}

func (o *MessagesV2GetDocumentServiceUnavailable) String() string {
	return fmt.Sprintf("[GET /messages/v2/documents/{documentId}][%d] messagesV2GetDocumentServiceUnavailable", 503)
}

func (o *MessagesV2GetDocumentServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
