// Code generated by go-swagger; DO NOT EDIT.

package messages

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/conv"
)

// NewMessagesV2GetDocumentsParams creates a new MessagesV2GetDocumentsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewMessagesV2GetDocumentsParams() *MessagesV2GetDocumentsParams {
	return NewMessagesV2GetDocumentsParamsWithTimeout(cr.DefaultTimeout)
}

// NewMessagesV2GetDocumentsParamsWithTimeout creates a new MessagesV2GetDocumentsParams object
// with the ability to set a timeout on a request.
func NewMessagesV2GetDocumentsParamsWithTimeout(timeout time.Duration) *MessagesV2GetDocumentsParams {
	return &MessagesV2GetDocumentsParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewMessagesV2GetDocumentsParamsWithContext creates a new MessagesV2GetDocumentsParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [MessagesV2GetDocumentsParams].
func NewMessagesV2GetDocumentsParamsWithContext(ctx context.Context) *MessagesV2GetDocumentsParams {
	return &MessagesV2GetDocumentsParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewMessagesV2GetDocumentsParamsWithHTTPClient creates a new MessagesV2GetDocumentsParams object
// with the ability to set a custom HTTPClient for a request.
func NewMessagesV2GetDocumentsParamsWithHTTPClient(client *http.Client) *MessagesV2GetDocumentsParams {
	return &MessagesV2GetDocumentsParams{
		HTTPClient: client,
	}
}

/*
MessagesV2GetDocumentsParams contains all the parameters to send to the API endpoint

	for the messages v2 get documents operation.

	Typically these are written to a http.Request.
*/
type MessagesV2GetDocumentsParams struct {

	/* PagingCount.

	   The maximum number of results that will be returned.

	   Format: int32
	   Default: 20
	*/
	PagingCount *int32

	/* PagingFirst.

	   Index of the returning results.

	   Format: int32
	*/
	PagingFirst *int32

	/* User.

	   The literal "user" or the unique ID of the client.
	*/
	User string

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the messages v2 get documents params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *MessagesV2GetDocumentsParams) WithDefaults() *MessagesV2GetDocumentsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the messages v2 get documents params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *MessagesV2GetDocumentsParams) SetDefaults() {
	var (
		pagingCountDefault = int32(20)

		pagingFirstDefault = int32(0)
	)

	val := MessagesV2GetDocumentsParams{
		PagingCount: &pagingCountDefault,
		PagingFirst: &pagingFirstDefault,
	}

	val.inner.timeout = o.inner.timeout
	val.inner.ctx = o.inner.ctx
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the messages v2 get documents params.
func (o *MessagesV2GetDocumentsParams) WithTimeout(timeout time.Duration) *MessagesV2GetDocumentsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the messages v2 get documents params.
func (o *MessagesV2GetDocumentsParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the messages v2 get documents params.
//
// Deprecated: use the operation call with context to pass the context instead of [MessagesV2GetDocumentsParams].
func (o *MessagesV2GetDocumentsParams) WithContext(ctx context.Context) *MessagesV2GetDocumentsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the messages v2 get documents params.
//
// Deprecated: use the operation call with context to pass the context instead of [MessagesV2GetDocumentsParams].
func (o *MessagesV2GetDocumentsParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the messages v2 get documents params.
func (o *MessagesV2GetDocumentsParams) WithHTTPClient(client *http.Client) *MessagesV2GetDocumentsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the messages v2 get documents params.
func (o *MessagesV2GetDocumentsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPagingCount adds the pagingCount to the messages v2 get documents params.
func (o *MessagesV2GetDocumentsParams) WithPagingCount(pagingCount *int32) *MessagesV2GetDocumentsParams {
	o.SetPagingCount(pagingCount)
	return o
}

// SetPagingCount adds the pagingCount to the messages v2 get documents params.
func (o *MessagesV2GetDocumentsParams) SetPagingCount(pagingCount *int32) {
	o.PagingCount = pagingCount
}

// WithPagingFirst adds the pagingFirst to the messages v2 get documents params.
func (o *MessagesV2GetDocumentsParams) WithPagingFirst(pagingFirst *int32) *MessagesV2GetDocumentsParams {
	o.SetPagingFirst(pagingFirst)
	return o
}

// SetPagingFirst adds the pagingFirst to the messages v2 get documents params.
func (o *MessagesV2GetDocumentsParams) SetPagingFirst(pagingFirst *int32) {
	o.PagingFirst = pagingFirst
}

// WithUser adds the user to the messages v2 get documents params.
func (o *MessagesV2GetDocumentsParams) WithUser(user string) *MessagesV2GetDocumentsParams {
	o.SetUser(user)
	return o
}

// SetUser adds the user to the messages v2 get documents params.
func (o *MessagesV2GetDocumentsParams) SetUser(user string) {
	o.User = user
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *MessagesV2GetDocumentsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	if o.PagingCount != nil {

		// query param paging-count
		var qrPagingCount int32

		if o.PagingCount != nil {
			qrPagingCount = *o.PagingCount
		}
		qPagingCount := conv.FormatInteger(qrPagingCount)
		if qPagingCount != "" {

			if err := r.SetQueryParam("paging-count", qPagingCount); err != nil {
				return err
			}
		}
	}

	if o.PagingFirst != nil {

		// query param paging-first
		var qrPagingFirst int32

		if o.PagingFirst != nil {
			qrPagingFirst = *o.PagingFirst
		}
		qPagingFirst := conv.FormatInteger(qrPagingFirst)
		if qPagingFirst != "" {

			if err := r.SetQueryParam("paging-first", qPagingFirst); err != nil {
				return err
			}
		}
	}

	// path param user
	if err := r.SetPathParam("user", o.User); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
