// Code generated by go-swagger; DO NOT EDIT.

package messages

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/jabbrwcky/paperless-bank/internal/bank/comdirect/models"
)

// MessagesV2GetDocumentsReader is a Reader for the MessagesV2GetDocuments structure.
type MessagesV2GetDocumentsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *MessagesV2GetDocumentsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewMessagesV2GetDocumentsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewMessagesV2GetDocumentsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewMessagesV2GetDocumentsUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewMessagesV2GetDocumentsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /messages/clients/{user}/v2/documents] messagesV2GetDocuments", response, response.Code())
	}
}

// NewMessagesV2GetDocumentsOK creates a MessagesV2GetDocumentsOK with default headers values
func NewMessagesV2GetDocumentsOK() *MessagesV2GetDocumentsOK {
	return &MessagesV2GetDocumentsOK{}
}

/*
MessagesV2GetDocumentsOK describes a response with status code 200, with default header values.

successful operation
*/
type MessagesV2GetDocumentsOK struct {
	Payload *models.ListResourceDocument
}

// IsSuccess returns true when this messages v2 get documents o k response has a 2xx status code
func (o *MessagesV2GetDocumentsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this messages v2 get documents o k response has a 3xx status code
func (o *MessagesV2GetDocumentsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this messages v2 get documents o k response has a 4xx status code
func (o *MessagesV2GetDocumentsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this messages v2 get documents o k response has a 5xx status code
func (o *MessagesV2GetDocumentsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this messages v2 get documents o k response a status code equal to that given
func (o *MessagesV2GetDocumentsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the messages v2 get documents o k response
func (o *MessagesV2GetDocumentsOK) Code() int {
	return 200
}

func (o *MessagesV2GetDocumentsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /messages/clients/{user}/v2/documents][%d] messagesV2GetDocumentsOK %s", 200, payload)
}

func (o *MessagesV2GetDocumentsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /messages/clients/{user}/v2/documents][%d] messagesV2GetDocumentsOK %s", 200, payload)
}

func (o *MessagesV2GetDocumentsOK) GetPayload() *models.ListResourceDocument {
	return o.Payload
}

func (o *MessagesV2GetDocumentsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ListResourceDocument)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewMessagesV2GetDocumentsNotFound creates a MessagesV2GetDocumentsNotFound with default headers values
func NewMessagesV2GetDocumentsNotFound() *MessagesV2GetDocumentsNotFound {
	return &MessagesV2GetDocumentsNotFound{}
}

/*
MessagesV2GetDocumentsNotFound describes a response with status code 404, with default header values.

Not Found
*/
type MessagesV2GetDocumentsNotFound struct {
}

// IsSuccess returns true when this messages v2 get documents not found response has a 2xx status code
func (o *MessagesV2GetDocumentsNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this messages v2 get documents not found response has a 3xx status code
func (o *MessagesV2GetDocumentsNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this messages v2 get documents not found response has a 4xx status code
func (o *MessagesV2GetDocumentsNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this messages v2 get documents not found response has a 5xx status code
func (o *MessagesV2GetDocumentsNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this messages v2 get documents not found response a status code equal to that given
func (o *MessagesV2GetDocumentsNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the messages v2 get documents not found response
func (o *MessagesV2GetDocumentsNotFound) Code() int {
	return 404
}

func (o *MessagesV2GetDocumentsNotFound) Error() string {
	return fmt.Sprintf("[GET /messages/clients/{user}/v2/documents][%d] messagesV2GetDocumentsNotFound", 404)
}

func (o *MessagesV2GetDocumentsNotFound) String() string {
	return fmt.Sprintf("[GET /messages/clients/{user}/v2/documents][%d] messagesV2GetDocumentsNotFound", 404)
}

func (o *MessagesV2GetDocumentsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewMessagesV2GetDocumentsUnprocessableEntity creates a MessagesV2GetDocumentsUnprocessableEntity with default headers values
func NewMessagesV2GetDocumentsUnprocessableEntity() *MessagesV2GetDocumentsUnprocessableEntity {
	return &MessagesV2GetDocumentsUnprocessableEntity{}
}

/*
MessagesV2GetDocumentsUnprocessableEntity describes a response with status code 422, with default header values.

Unprocessable Entity
*/
type MessagesV2GetDocumentsUnprocessableEntity struct {
	Payload *models.StandardErrorResponse
}

// IsSuccess returns true when this messages v2 get documents unprocessable entity response has a 2xx status code
func (o *MessagesV2GetDocumentsUnprocessableEntity) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this messages v2 get documents unprocessable entity response has a 3xx status code
func (o *MessagesV2GetDocumentsUnprocessableEntity) IsRedirect() bool {
	return false
}

// IsClientError returns true when this messages v2 get documents unprocessable entity response has a 4xx status code
func (o *MessagesV2GetDocumentsUnprocessableEntity) IsClientError() bool {
	return true
}

// IsServerError returns true when this messages v2 get documents unprocessable entity response has a 5xx status code
func (o *MessagesV2GetDocumentsUnprocessableEntity) IsServerError() bool {
	return false
}

// IsCode returns true when this messages v2 get documents unprocessable entity response a status code equal to that given
func (o *MessagesV2GetDocumentsUnprocessableEntity) IsCode(code int) bool {
	return code == 422
}

// Code gets the status code for the messages v2 get documents unprocessable entity response
func (o *MessagesV2GetDocumentsUnprocessableEntity) Code() int {
	return 422
}

func (o *MessagesV2GetDocumentsUnprocessableEntity) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /messages/clients/{user}/v2/documents][%d] messagesV2GetDocumentsUnprocessableEntity %s", 422, payload)
}

func (o *MessagesV2GetDocumentsUnprocessableEntity) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /messages/clients/{user}/v2/documents][%d] messagesV2GetDocumentsUnprocessableEntity %s", 422, payload)
}

func (o *MessagesV2GetDocumentsUnprocessableEntity) GetPayload() *models.StandardErrorResponse {
	return o.Payload
}

func (o *MessagesV2GetDocumentsUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StandardErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewMessagesV2GetDocumentsInternalServerError creates a MessagesV2GetDocumentsInternalServerError with default headers values
func NewMessagesV2GetDocumentsInternalServerError() *MessagesV2GetDocumentsInternalServerError {
	return &MessagesV2GetDocumentsInternalServerError{}
}

/*
MessagesV2GetDocumentsInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type MessagesV2GetDocumentsInternalServerError struct {
}

// IsSuccess returns true when this messages v2 get documents internal server error response has a 2xx status code
func (o *MessagesV2GetDocumentsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this messages v2 get documents internal server error response has a 3xx status code
func (o *MessagesV2GetDocumentsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this messages v2 get documents internal server error response has a 4xx status code
func (o *MessagesV2GetDocumentsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this messages v2 get documents internal server error response has a 5xx status code
func (o *MessagesV2GetDocumentsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this messages v2 get documents internal server error response a status code equal to that given
func (o *MessagesV2GetDocumentsInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the messages v2 get documents internal server error response
func (o *MessagesV2GetDocumentsInternalServerError) Code() int {
	return 500
}

func (o *MessagesV2GetDocumentsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /messages/clients/{user}/v2/documents][%d] messagesV2GetDocumentsInternalServerError", 500)
}

func (o *MessagesV2GetDocumentsInternalServerError) String() string {
	return fmt.Sprintf("[GET /messages/clients/{user}/v2/documents][%d] messagesV2GetDocumentsInternalServerError", 500)
}

func (o *MessagesV2GetDocumentsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
