// Code generated by go-swagger; DO NOT EDIT.

package messages

import (
	"context"
	"fmt"
	"time"

	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// New creates a new messages API client.
func New(transport runtime.ContextualTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

// New creates a new messages API client with basic auth credentials.
//
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - user: user for basic authentication header.
// - password: password for basic authentication header.
func NewClientWithBasicAuth(host, basePath, scheme, user, password string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BasicAuth(user, password)
	return &Client{transport: transport, formats: strfmt.Default}
}

// New creates a new messages API client with a bearer token for authentication.
//
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - bearerToken: bearer token for Bearer authentication header.
func NewClientWithBearerToken(host, basePath, scheme, bearerToken string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BearerToken(bearerToken)
	return &Client{transport: transport, formats: strfmt.Default}
}

/*
Client for messages API.
*/
type Client struct {
	transport runtime.ContextualTransport
	formats   strfmt.Registry
}

// ClientOption may be used to customize the behavior of Client methods.
type ClientOption func(*runtime.ClientOperation)

// This client is generated with a few options you might find useful for your swagger spec.
//
// Feel free to add you own set of options.

// WithAccept allows the client to force the Accept header
// to negotiate a specific Producer from the server.
//
// You may use this option to set arbitrary extensions to your MIME media type.
func WithAccept(mime string) ClientOption {
	return func(r *runtime.ClientOperation) {
		r.ProducesMediaTypes = []string{mime}
	}
}

// WithAcceptApplicationJSON sets the Accept header to "application/json".
func WithAcceptApplicationJSON(r *runtime.ClientOperation) {
	r.ProducesMediaTypes = []string{"application/json"}
}

// WithAcceptApplicationPdf sets the Accept header to "application/pdf".
func WithAcceptApplicationPdf(r *runtime.ClientOperation) {
	r.ProducesMediaTypes = []string{"application/pdf"}
}

// WithAcceptTextHTML sets the Accept header to "text/html".
func WithAcceptTextHTML(r *runtime.ClientOperation) {
	r.ProducesMediaTypes = []string{"text/html"}
}

// ClientService is the interface for Client methods.
type ClientService interface {

	// MessagesV2GetDocument delivers a document for the given UUID.
	MessagesV2GetDocument(params *MessagesV2GetDocumentParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) error

	// MessagesV2GetDocumentContext delivers a document for the given UUID.
	MessagesV2GetDocumentContext(ctx context.Context, params *MessagesV2GetDocumentParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) error

	// MessagesV2GetDocuments delivers a list of documents for the customer.
	MessagesV2GetDocuments(params *MessagesV2GetDocumentsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*MessagesV2GetDocumentsOK, error)

	// MessagesV2GetDocumentsContext delivers a list of documents for the customer.
	MessagesV2GetDocumentsContext(ctx context.Context, params *MessagesV2GetDocumentsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*MessagesV2GetDocumentsOK, error)

	// MessagesV2GetPredocument delivers a predocument for the given UUID.
	MessagesV2GetPredocument(params *MessagesV2GetPredocumentParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) error

	// MessagesV2GetPredocumentContext delivers a predocument for the given UUID.
	MessagesV2GetPredocumentContext(ctx context.Context, params *MessagesV2GetPredocumentParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) error

	SetTransport(transport runtime.ContextualTransport)
}

/*
MessagesV2GetDocumentdelivers a document for the given UUID.

This method does not support injected context.
However, timeout and opentracing contexts are honored whenever enabled.

If you need to pass a specific context, use [Client.MessagesV2GetDocumentContext] instead.
*/
func (a *Client) MessagesV2GetDocument(params *MessagesV2GetDocumentParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) error {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.MessagesV2GetDocumentContext(ctx, params, authInfo, opts...)
}

/*
MessagesV2GetDocumentContextdelivers a document for the given UUID.

Do not use the deprecated [MessagesV2GetDocumentParams.Context] with this method: it would be ignored.
*/
func (a *Client) MessagesV2GetDocumentContext(ctx context.Context, params *MessagesV2GetDocumentParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) error {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewMessagesV2GetDocumentParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "messagesV2GetDocument",
		Method:             "GET",
		PathPattern:        "/messages/v2/documents/{documentId}",
		ProducesMediaTypes: []string{"text/html", "application/pdf"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &MessagesV2GetDocumentReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	_, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return err
	}
	// no success response is defined: return nil

	return nil
}

/*
MessagesV2GetDocumentsdelivers a list of documents for the customer.

This method does not support injected context.
However, timeout and opentracing contexts are honored whenever enabled.

If you need to pass a specific context, use [Client.MessagesV2GetDocumentsContext] instead.
*/
func (a *Client) MessagesV2GetDocuments(params *MessagesV2GetDocumentsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*MessagesV2GetDocumentsOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.MessagesV2GetDocumentsContext(ctx, params, authInfo, opts...)
}

/*
MessagesV2GetDocumentsContextdelivers a list of documents for the customer.

Do not use the deprecated [MessagesV2GetDocumentsParams.Context] with this method: it would be ignored.
*/
func (a *Client) MessagesV2GetDocumentsContext(ctx context.Context, params *MessagesV2GetDocumentsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*MessagesV2GetDocumentsOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewMessagesV2GetDocumentsParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "messagesV2GetDocuments",
		Method:             "GET",
		PathPattern:        "/messages/clients/{user}/v2/documents",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &MessagesV2GetDocumentsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*MessagesV2GetDocumentsOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for messagesV2GetDocuments: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
MessagesV2GetPredocumentdelivers a predocument for the given UUID.

This method does not support injected context.
However, timeout and opentracing contexts are honored whenever enabled.

If you need to pass a specific context, use [Client.MessagesV2GetPredocumentContext] instead.
*/
func (a *Client) MessagesV2GetPredocument(params *MessagesV2GetPredocumentParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) error {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.MessagesV2GetPredocumentContext(ctx, params, authInfo, opts...)
}

/*
MessagesV2GetPredocumentContextdelivers a predocument for the given UUID.

Do not use the deprecated [MessagesV2GetPredocumentParams.Context] with this method: it would be ignored.
*/
func (a *Client) MessagesV2GetPredocumentContext(ctx context.Context, params *MessagesV2GetPredocumentParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) error {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewMessagesV2GetPredocumentParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "messagesV2GetPredocument",
		Method:             "GET",
		PathPattern:        "/messages/v2/documents/{documentId}/predocument",
		ProducesMediaTypes: []string{"text/html", "application/pdf"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &MessagesV2GetPredocumentReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	_, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return err
	}
	// no success response is defined: return nil

	return nil
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ContextualTransport) {
	a.transport = transport
}

// innerParams captures internal fields so they don't conflict with user-supplied parameters.
type innerParams struct {
	timeout time.Duration

	// Deprecated: use the operation call with context to pass the context instead of [MessagesParams].
	ctx context.Context
}
