// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/validate"
)

// AccountInformation Model for the information of an account (debtor/creditor).
//
// swagger:model AccountInformation
type AccountInformation struct {

	// The BIC (Bank Identifier Code) for the IBAN - if available
	// Read Only: true
	Bic string `json:"bic,omitempty"`

	// name of the account owner
	// Read Only: true
	HolderName string `json:"holderName,omitempty"`

	// The IBAN (International bank account number) for the account - if available
	// Read Only: true
	Iban string `json:"iban,omitempty"`
}

// Validate validates this account information
func (m *AccountInformation) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validate this account information based on the context it is used
func (m *AccountInformation) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateBic(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateHolderName(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateIban(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AccountInformation) contextValidateBic(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "bic", "body", m.Bic); err != nil {
		return err
	}

	return nil
}

func (m *AccountInformation) contextValidateHolderName(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "holderName", "body", m.HolderName); err != nil {
		return err
	}

	return nil
}

func (m *AccountInformation) contextValidateIban(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "iban", "body", m.Iban); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *AccountInformation) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AccountInformation) UnmarshalBinary(b []byte) error {
	var res AccountInformation
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
