// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	"encoding/json"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
	"github.com/go-openapi/validate"
)

// AccountTransaction Model for an account transaction.
//
// swagger:model AccountTransaction
type AccountTransaction struct {

	// The amount
	// Read Only: true
	Amount *AmountValue `json:"amount,omitempty"`

	// The booking date
	// Read Only: true
	BookingDate *DateString `json:"bookingDate,omitempty"`

	// Status of transaction
	// Read Only: true
	// Enum: ["BOOKED","NOTBOOKED"]
	BookingStatus string `json:"bookingStatus,omitempty"`

	// includes the account information of the name, IBAN and BIC from the creditor
	// Read Only: true
	Creditor *AccountInformation `json:"creditor,omitempty"`

	// Account information of name, IBAN and BIC of the debtor
	// Read Only: true
	Deptor *AccountInformation `json:"deptor,omitempty"`

	// Gives back the creditor identifier of an account transaction, if it is a direct debit.
	// Read Only: true
	DirectDebitCreditorID string `json:"directDebitCreditorId,omitempty"`

	// Gives back the mandateId of an account transaction, if it is a direct debit.
	// Read Only: true
	DirectDebitMandateID string `json:"directDebitMandateId,omitempty"`

	// Gives back the end-to-end-reference of an account transaction, if it is a direct debit.
	// Read Only: true
	EndToEndReference string `json:"endToEndReference,omitempty"`

	// Shows whether the client has seen the account transaction in web.
	// Read Only: true
	NewTransaction *bool `json:"newTransaction,omitempty"`

	// unique reference code of the transaction
	// Read Only: true
	Reference string `json:"reference,omitempty"`

	// remittance information of the transaction. This can be more then one line with a length of 35 symbols. The lines will be numbered in case of an already booked transaction.
	// Read Only: true
	RemittanceInfo string `json:"remittanceInfo,omitempty"`

	// Account information of name, IBAN and BIC of the remitter.
	// Read Only: true
	Remitter *AccountInformation `json:"remitter,omitempty"`

	// Definition of account transaction type.
	// Read Only: true
	TransactionType *EnumText `json:"transactionType,omitempty"`

	// Availability date (yyyy-mm-dd). Could be an invalid date e.g. 2019-12-32
	// Read Only: true
	ValutaDate string `json:"valutaDate,omitempty"`
}

// Validate validates this account transaction
func (m *AccountTransaction) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAmount(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateBookingDate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateBookingStatus(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCreditor(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDeptor(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRemitter(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTransactionType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AccountTransaction) validateAmount(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Amount) { // not required
		return nil
	}

	if m.Amount != nil {
		if err := m.Amount.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("amount")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("amount")
			}

			return err
		}
	}

	return nil
}

func (m *AccountTransaction) validateBookingDate(formats strfmt.Registry) error {
	if typeutils.IsZero(m.BookingDate) { // not required
		return nil
	}

	if m.BookingDate != nil {
		if err := m.BookingDate.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("bookingDate")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("bookingDate")
			}

			return err
		}
	}

	return nil
}

var accountTransactionTypeBookingStatusPropEnum []any

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["BOOKED","NOTBOOKED"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		accountTransactionTypeBookingStatusPropEnum = append(accountTransactionTypeBookingStatusPropEnum, v)
	}
}

const (

	// AccountTransactionBookingStatusBOOKED captures enum value "BOOKED"
	AccountTransactionBookingStatusBOOKED string = "BOOKED"

	// AccountTransactionBookingStatusNOTBOOKED captures enum value "NOTBOOKED"
	AccountTransactionBookingStatusNOTBOOKED string = "NOTBOOKED"
)

// prop value enum
func (m *AccountTransaction) validateBookingStatusEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, accountTransactionTypeBookingStatusPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *AccountTransaction) validateBookingStatus(formats strfmt.Registry) error {
	if typeutils.IsZero(m.BookingStatus) { // not required
		return nil
	}

	// value enum
	if err := m.validateBookingStatusEnum("bookingStatus", "body", m.BookingStatus); err != nil {
		return err
	}

	return nil
}

func (m *AccountTransaction) validateCreditor(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Creditor) { // not required
		return nil
	}

	if m.Creditor != nil {
		if err := m.Creditor.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("creditor")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("creditor")
			}

			return err
		}
	}

	return nil
}

func (m *AccountTransaction) validateDeptor(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Deptor) { // not required
		return nil
	}

	if m.Deptor != nil {
		if err := m.Deptor.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("deptor")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("deptor")
			}

			return err
		}
	}

	return nil
}

func (m *AccountTransaction) validateRemitter(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Remitter) { // not required
		return nil
	}

	if m.Remitter != nil {
		if err := m.Remitter.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("remitter")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("remitter")
			}

			return err
		}
	}

	return nil
}

func (m *AccountTransaction) validateTransactionType(formats strfmt.Registry) error {
	if typeutils.IsZero(m.TransactionType) { // not required
		return nil
	}

	if m.TransactionType != nil {
		if err := m.TransactionType.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("transactionType")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("transactionType")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this account transaction based on the context it is used
func (m *AccountTransaction) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAmount(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateBookingDate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateBookingStatus(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateCreditor(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateDeptor(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateDirectDebitCreditorID(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateDirectDebitMandateID(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateEndToEndReference(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateNewTransaction(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateReference(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateRemittanceInfo(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateRemitter(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateTransactionType(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateValutaDate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AccountTransaction) contextValidateAmount(ctx context.Context, formats strfmt.Registry) error {

	if m.Amount != nil {

		if typeutils.IsZero(m.Amount) { // not required
			return nil
		}

		if err := m.Amount.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("amount")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("amount")
			}

			return err
		}
	}

	return nil
}

func (m *AccountTransaction) contextValidateBookingDate(ctx context.Context, formats strfmt.Registry) error {

	if m.BookingDate != nil {

		if typeutils.IsZero(m.BookingDate) { // not required
			return nil
		}

		if err := m.BookingDate.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("bookingDate")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("bookingDate")
			}

			return err
		}
	}

	return nil
}

func (m *AccountTransaction) contextValidateBookingStatus(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "bookingStatus", "body", m.BookingStatus); err != nil {
		return err
	}

	return nil
}

func (m *AccountTransaction) contextValidateCreditor(ctx context.Context, formats strfmt.Registry) error {

	if m.Creditor != nil {

		if typeutils.IsZero(m.Creditor) { // not required
			return nil
		}

		if err := m.Creditor.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("creditor")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("creditor")
			}

			return err
		}
	}

	return nil
}

func (m *AccountTransaction) contextValidateDeptor(ctx context.Context, formats strfmt.Registry) error {

	if m.Deptor != nil {

		if typeutils.IsZero(m.Deptor) { // not required
			return nil
		}

		if err := m.Deptor.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("deptor")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("deptor")
			}

			return err
		}
	}

	return nil
}

func (m *AccountTransaction) contextValidateDirectDebitCreditorID(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "directDebitCreditorId", "body", m.DirectDebitCreditorID); err != nil {
		return err
	}

	return nil
}

func (m *AccountTransaction) contextValidateDirectDebitMandateID(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "directDebitMandateId", "body", m.DirectDebitMandateID); err != nil {
		return err
	}

	return nil
}

func (m *AccountTransaction) contextValidateEndToEndReference(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "endToEndReference", "body", m.EndToEndReference); err != nil {
		return err
	}

	return nil
}

func (m *AccountTransaction) contextValidateNewTransaction(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "newTransaction", "body", m.NewTransaction); err != nil {
		return err
	}

	return nil
}

func (m *AccountTransaction) contextValidateReference(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "reference", "body", m.Reference); err != nil {
		return err
	}

	return nil
}

func (m *AccountTransaction) contextValidateRemittanceInfo(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "remittanceInfo", "body", m.RemittanceInfo); err != nil {
		return err
	}

	return nil
}

func (m *AccountTransaction) contextValidateRemitter(ctx context.Context, formats strfmt.Registry) error {

	if m.Remitter != nil {

		if typeutils.IsZero(m.Remitter) { // not required
			return nil
		}

		if err := m.Remitter.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("remitter")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("remitter")
			}

			return err
		}
	}

	return nil
}

func (m *AccountTransaction) contextValidateTransactionType(ctx context.Context, formats strfmt.Registry) error {

	if m.TransactionType != nil {

		if typeutils.IsZero(m.TransactionType) { // not required
			return nil
		}

		if err := m.TransactionType.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("transactionType")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("transactionType")
			}

			return err
		}
	}

	return nil
}

func (m *AccountTransaction) contextValidateValutaDate(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "valutaDate", "body", m.ValutaDate); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *AccountTransaction) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AccountTransaction) UnmarshalBinary(b []byte) error {
	var res AccountTransaction
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
