// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
	"github.com/go-openapi/validate"
)

// Account Master data of an account
//
// swagger:model Account
type Account struct {

	// Account identfier
	// Read Only: true
	AccountDisplayID string `json:"accountDisplayId,omitempty"`

	// Account identifier (UUID)
	// Read Only: true
	AccountID string `json:"accountId,omitempty"`

	// Account type. 'key' contains the product type, 'text' a description
	// Read Only: true
	AccountType *EnumText `json:"accountType,omitempty"`

	// Identification Code of the client (UUID)
	// Read Only: true
	ClientID string `json:"clientId,omitempty"`

	// Credit limit, if available
	// Read Only: true
	CreditLimit *AmountValue `json:"creditLimit,omitempty"`

	// Account currency
	// Read Only: true
	Currency *CurrencyString `json:"currency,omitempty"`

	// IBAN (International bank account number), if available
	// Read Only: true
	Iban string `json:"iban,omitempty"`
}

// Validate validates this account
func (m *Account) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAccountType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCreditLimit(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCurrency(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Account) validateAccountType(formats strfmt.Registry) error {
	if typeutils.IsZero(m.AccountType) { // not required
		return nil
	}

	if m.AccountType != nil {
		if err := m.AccountType.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("accountType")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("accountType")
			}

			return err
		}
	}

	return nil
}

func (m *Account) validateCreditLimit(formats strfmt.Registry) error {
	if typeutils.IsZero(m.CreditLimit) { // not required
		return nil
	}

	if m.CreditLimit != nil {
		if err := m.CreditLimit.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("creditLimit")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("creditLimit")
			}

			return err
		}
	}

	return nil
}

func (m *Account) validateCurrency(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Currency) { // not required
		return nil
	}

	if m.Currency != nil {
		if err := m.Currency.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("currency")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("currency")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this account based on the context it is used
func (m *Account) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAccountDisplayID(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateAccountID(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateAccountType(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateClientID(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateCreditLimit(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateCurrency(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateIban(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Account) contextValidateAccountDisplayID(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "accountDisplayId", "body", m.AccountDisplayID); err != nil {
		return err
	}

	return nil
}

func (m *Account) contextValidateAccountID(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "accountId", "body", m.AccountID); err != nil {
		return err
	}

	return nil
}

func (m *Account) contextValidateAccountType(ctx context.Context, formats strfmt.Registry) error {

	if m.AccountType != nil {

		if typeutils.IsZero(m.AccountType) { // not required
			return nil
		}

		if err := m.AccountType.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("accountType")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("accountType")
			}

			return err
		}
	}

	return nil
}

func (m *Account) contextValidateClientID(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "clientId", "body", m.ClientID); err != nil {
		return err
	}

	return nil
}

func (m *Account) contextValidateCreditLimit(ctx context.Context, formats strfmt.Registry) error {

	if m.CreditLimit != nil {

		if typeutils.IsZero(m.CreditLimit) { // not required
			return nil
		}

		if err := m.CreditLimit.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("creditLimit")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("creditLimit")
			}

			return err
		}
	}

	return nil
}

func (m *Account) contextValidateCurrency(ctx context.Context, formats strfmt.Registry) error {

	if m.Currency != nil {

		if typeutils.IsZero(m.Currency) { // not required
			return nil
		}

		if err := m.Currency.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("currency")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("currency")
			}

			return err
		}
	}

	return nil
}

func (m *Account) contextValidateIban(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "iban", "body", m.Iban); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Account) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Account) UnmarshalBinary(b []byte) error {
	var res Account
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
