// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
	"github.com/go-openapi/validate"
)

// AccountBalance Account information, including cash balance and buying power
//
// swagger:model AccountBalance
type AccountBalance struct {

	// The master data of this account (attribute can be suppressed by using the parameter 'without-attr=account')
	// Read Only: true
	Account *Account `json:"account,omitempty"`

	// Account identifier (UUID)
	// Read Only: true
	AccountID string `json:"accountId,omitempty"`

	// Sum of current account balance + credit limit - sum of funds, which are already planned but not yet booked. This is the maximum cash limit
	// Read Only: true
	AvailableCashAmount *AmountValue `json:"availableCashAmount,omitempty"`

	// As 'availableCashAmount', but in EUR
	// Read Only: true
	AvailableCashAmountEUR *AmountValue `json:"availableCashAmountEUR,omitempty"`

	// Current balance
	// Read Only: true
	Balance *AmountValue `json:"balance,omitempty"`

	// Current balance in EUR
	// Read Only: true
	BalanceEUR *AmountValue `json:"balanceEUR,omitempty"`
}

// Validate validates this account balance
func (m *AccountBalance) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAccount(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateAvailableCashAmount(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateAvailableCashAmountEUR(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateBalance(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateBalanceEUR(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AccountBalance) validateAccount(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Account) { // not required
		return nil
	}

	if m.Account != nil {
		if err := m.Account.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("account")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("account")
			}

			return err
		}
	}

	return nil
}

func (m *AccountBalance) validateAvailableCashAmount(formats strfmt.Registry) error {
	if typeutils.IsZero(m.AvailableCashAmount) { // not required
		return nil
	}

	if m.AvailableCashAmount != nil {
		if err := m.AvailableCashAmount.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("availableCashAmount")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("availableCashAmount")
			}

			return err
		}
	}

	return nil
}

func (m *AccountBalance) validateAvailableCashAmountEUR(formats strfmt.Registry) error {
	if typeutils.IsZero(m.AvailableCashAmountEUR) { // not required
		return nil
	}

	if m.AvailableCashAmountEUR != nil {
		if err := m.AvailableCashAmountEUR.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("availableCashAmountEUR")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("availableCashAmountEUR")
			}

			return err
		}
	}

	return nil
}

func (m *AccountBalance) validateBalance(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Balance) { // not required
		return nil
	}

	if m.Balance != nil {
		if err := m.Balance.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("balance")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("balance")
			}

			return err
		}
	}

	return nil
}

func (m *AccountBalance) validateBalanceEUR(formats strfmt.Registry) error {
	if typeutils.IsZero(m.BalanceEUR) { // not required
		return nil
	}

	if m.BalanceEUR != nil {
		if err := m.BalanceEUR.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("balanceEUR")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("balanceEUR")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this account balance based on the context it is used
func (m *AccountBalance) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAccount(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateAccountID(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateAvailableCashAmount(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateAvailableCashAmountEUR(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateBalance(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateBalanceEUR(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AccountBalance) contextValidateAccount(ctx context.Context, formats strfmt.Registry) error {

	if m.Account != nil {

		if typeutils.IsZero(m.Account) { // not required
			return nil
		}

		if err := m.Account.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("account")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("account")
			}

			return err
		}
	}

	return nil
}

func (m *AccountBalance) contextValidateAccountID(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "accountId", "body", m.AccountID); err != nil {
		return err
	}

	return nil
}

func (m *AccountBalance) contextValidateAvailableCashAmount(ctx context.Context, formats strfmt.Registry) error {

	if m.AvailableCashAmount != nil {

		if typeutils.IsZero(m.AvailableCashAmount) { // not required
			return nil
		}

		if err := m.AvailableCashAmount.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("availableCashAmount")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("availableCashAmount")
			}

			return err
		}
	}

	return nil
}

func (m *AccountBalance) contextValidateAvailableCashAmountEUR(ctx context.Context, formats strfmt.Registry) error {

	if m.AvailableCashAmountEUR != nil {

		if typeutils.IsZero(m.AvailableCashAmountEUR) { // not required
			return nil
		}

		if err := m.AvailableCashAmountEUR.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("availableCashAmountEUR")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("availableCashAmountEUR")
			}

			return err
		}
	}

	return nil
}

func (m *AccountBalance) contextValidateBalance(ctx context.Context, formats strfmt.Registry) error {

	if m.Balance != nil {

		if typeutils.IsZero(m.Balance) { // not required
			return nil
		}

		if err := m.Balance.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("balance")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("balance")
			}

			return err
		}
	}

	return nil
}

func (m *AccountBalance) contextValidateBalanceEUR(ctx context.Context, formats strfmt.Registry) error {

	if m.BalanceEUR != nil {

		if typeutils.IsZero(m.BalanceEUR) { // not required
			return nil
		}

		if err := m.BalanceEUR.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("balanceEUR")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("balanceEUR")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *AccountBalance) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AccountBalance) UnmarshalBinary(b []byte) error {
	var res AccountBalance
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
