// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
)

// Balance A balance object is equal to one of the types indicated by the attributes in this definition.
//
// swagger:model Balance
type Balance struct {

	// Balance object for an account
	AccountBalance *AccountBalance `json:"accountBalance,omitempty"`

	// Balance object for a card
	CardBalance *CardBalance `json:"cardBalance,omitempty"`

	// Aggregation object for a depot
	DepotAggregation *DepotAggregation `json:"depotAggregation,omitempty"`

	// Balance object for a fixed term saving
	FixedTermSavings *FixedTermSavings `json:"fixedTermSavings,omitempty"`

	// Balance object for an installment loan
	InstallmentLoanBalance *InstallmentLoanBalance `json:"installmentLoanBalance,omitempty"`
}

// Validate validates this balance
func (m *Balance) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAccountBalance(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCardBalance(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDepotAggregation(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateFixedTermSavings(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateInstallmentLoanBalance(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Balance) validateAccountBalance(formats strfmt.Registry) error {
	if typeutils.IsZero(m.AccountBalance) { // not required
		return nil
	}

	if m.AccountBalance != nil {
		if err := m.AccountBalance.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("accountBalance")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("accountBalance")
			}

			return err
		}
	}

	return nil
}

func (m *Balance) validateCardBalance(formats strfmt.Registry) error {
	if typeutils.IsZero(m.CardBalance) { // not required
		return nil
	}

	if m.CardBalance != nil {
		if err := m.CardBalance.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("cardBalance")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("cardBalance")
			}

			return err
		}
	}

	return nil
}

func (m *Balance) validateDepotAggregation(formats strfmt.Registry) error {
	if typeutils.IsZero(m.DepotAggregation) { // not required
		return nil
	}

	if m.DepotAggregation != nil {
		if err := m.DepotAggregation.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("depotAggregation")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("depotAggregation")
			}

			return err
		}
	}

	return nil
}

func (m *Balance) validateFixedTermSavings(formats strfmt.Registry) error {
	if typeutils.IsZero(m.FixedTermSavings) { // not required
		return nil
	}

	if m.FixedTermSavings != nil {
		if err := m.FixedTermSavings.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("fixedTermSavings")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("fixedTermSavings")
			}

			return err
		}
	}

	return nil
}

func (m *Balance) validateInstallmentLoanBalance(formats strfmt.Registry) error {
	if typeutils.IsZero(m.InstallmentLoanBalance) { // not required
		return nil
	}

	if m.InstallmentLoanBalance != nil {
		if err := m.InstallmentLoanBalance.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("installmentLoanBalance")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("installmentLoanBalance")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this balance based on the context it is used
func (m *Balance) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAccountBalance(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateCardBalance(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateDepotAggregation(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateFixedTermSavings(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateInstallmentLoanBalance(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Balance) contextValidateAccountBalance(ctx context.Context, formats strfmt.Registry) error {

	if m.AccountBalance != nil {

		if typeutils.IsZero(m.AccountBalance) { // not required
			return nil
		}

		if err := m.AccountBalance.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("accountBalance")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("accountBalance")
			}

			return err
		}
	}

	return nil
}

func (m *Balance) contextValidateCardBalance(ctx context.Context, formats strfmt.Registry) error {

	if m.CardBalance != nil {

		if typeutils.IsZero(m.CardBalance) { // not required
			return nil
		}

		if err := m.CardBalance.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("cardBalance")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("cardBalance")
			}

			return err
		}
	}

	return nil
}

func (m *Balance) contextValidateDepotAggregation(ctx context.Context, formats strfmt.Registry) error {

	if m.DepotAggregation != nil {

		if typeutils.IsZero(m.DepotAggregation) { // not required
			return nil
		}

		if err := m.DepotAggregation.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("depotAggregation")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("depotAggregation")
			}

			return err
		}
	}

	return nil
}

func (m *Balance) contextValidateFixedTermSavings(ctx context.Context, formats strfmt.Registry) error {

	if m.FixedTermSavings != nil {

		if typeutils.IsZero(m.FixedTermSavings) { // not required
			return nil
		}

		if err := m.FixedTermSavings.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("fixedTermSavings")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("fixedTermSavings")
			}

			return err
		}
	}

	return nil
}

func (m *Balance) contextValidateInstallmentLoanBalance(ctx context.Context, formats strfmt.Registry) error {

	if m.InstallmentLoanBalance != nil {

		if typeutils.IsZero(m.InstallmentLoanBalance) { // not required
			return nil
		}

		if err := m.InstallmentLoanBalance.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("installmentLoanBalance")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("installmentLoanBalance")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Balance) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Balance) UnmarshalBinary(b []byte) error {
	var res Balance
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
