// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
	"github.com/go-openapi/validate"
)

// BusinessMessage Model for an error
//
// swagger:model BusinessMessage
type BusinessMessage struct {

	// Arguments for the error message
	Args []any `json:"args"`

	// Identifier for the error
	// Enum: ["request.object.invalid","request.query.invalid"]
	Key string `json:"key,omitempty"`

	// Default error message
	Message string `json:"message,omitempty"`

	// List of properties causing validation errors
	Origin []string `json:"origin"`

	// Severity level of the error
	// Enum: ["ERROR","INFO","WARN"]
	Severity string `json:"severity,omitempty"`
}

// Validate validates this business message
func (m *BusinessMessage) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateKey(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSeverity(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var businessMessageTypeKeyPropEnum []any

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["request.object.invalid","request.query.invalid"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		businessMessageTypeKeyPropEnum = append(businessMessageTypeKeyPropEnum, v)
	}
}

const (

	// BusinessMessageKeyRequestDotObjectDotInvalid captures enum value "request.object.invalid"
	BusinessMessageKeyRequestDotObjectDotInvalid string = "request.object.invalid"

	// BusinessMessageKeyRequestDotQueryDotInvalid captures enum value "request.query.invalid"
	BusinessMessageKeyRequestDotQueryDotInvalid string = "request.query.invalid"
)

// prop value enum
func (m *BusinessMessage) validateKeyEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, businessMessageTypeKeyPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *BusinessMessage) validateKey(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Key) { // not required
		return nil
	}

	// value enum
	if err := m.validateKeyEnum("key", "body", m.Key); err != nil {
		return err
	}

	return nil
}

var businessMessageTypeSeverityPropEnum []any

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["ERROR","INFO","WARN"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		businessMessageTypeSeverityPropEnum = append(businessMessageTypeSeverityPropEnum, v)
	}
}

const (

	// BusinessMessageSeverityERROR captures enum value "ERROR"
	BusinessMessageSeverityERROR string = "ERROR"

	// BusinessMessageSeverityINFO captures enum value "INFO"
	BusinessMessageSeverityINFO string = "INFO"

	// BusinessMessageSeverityWARN captures enum value "WARN"
	BusinessMessageSeverityWARN string = "WARN"
)

// prop value enum
func (m *BusinessMessage) validateSeverityEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, businessMessageTypeSeverityPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *BusinessMessage) validateSeverity(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Severity) { // not required
		return nil
	}

	// value enum
	if err := m.validateSeverityEnum("severity", "body", m.Severity); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this business message based on context it is used
func (m *BusinessMessage) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *BusinessMessage) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BusinessMessage) UnmarshalBinary(b []byte) error {
	var res BusinessMessage
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
