// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
	"github.com/go-openapi/validate"
)

// CardBalance Model for a card balance.
//
// swagger:model CardBalance
type CardBalance struct {

	// Sum of current account balance + credit limit - sum of scheduled amounts which are not booked yet. This is the maximum cash limit.
	// Read Only: true
	AvailableCashAmount *AmountValue `json:"availableCashAmount,omitempty"`

	// Current balance.
	// Read Only: true
	Balance *AmountValue `json:"balance,omitempty"`

	// Master data of the card.
	// Read Only: true
	Card *Card `json:"card,omitempty"`

	// Card identifier (UUID).
	// Example: 0123456789ABCDEF0123456789ABCDEF
	// Read Only: true
	CardID string `json:"cardId,omitempty"`
}

// Validate validates this card balance
func (m *CardBalance) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAvailableCashAmount(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateBalance(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCard(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CardBalance) validateAvailableCashAmount(formats strfmt.Registry) error {
	if typeutils.IsZero(m.AvailableCashAmount) { // not required
		return nil
	}

	if m.AvailableCashAmount != nil {
		if err := m.AvailableCashAmount.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("availableCashAmount")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("availableCashAmount")
			}

			return err
		}
	}

	return nil
}

func (m *CardBalance) validateBalance(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Balance) { // not required
		return nil
	}

	if m.Balance != nil {
		if err := m.Balance.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("balance")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("balance")
			}

			return err
		}
	}

	return nil
}

func (m *CardBalance) validateCard(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Card) { // not required
		return nil
	}

	if m.Card != nil {
		if err := m.Card.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("card")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("card")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this card balance based on the context it is used
func (m *CardBalance) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAvailableCashAmount(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateBalance(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateCard(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateCardID(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CardBalance) contextValidateAvailableCashAmount(ctx context.Context, formats strfmt.Registry) error {

	if m.AvailableCashAmount != nil {

		if typeutils.IsZero(m.AvailableCashAmount) { // not required
			return nil
		}

		if err := m.AvailableCashAmount.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("availableCashAmount")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("availableCashAmount")
			}

			return err
		}
	}

	return nil
}

func (m *CardBalance) contextValidateBalance(ctx context.Context, formats strfmt.Registry) error {

	if m.Balance != nil {

		if typeutils.IsZero(m.Balance) { // not required
			return nil
		}

		if err := m.Balance.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("balance")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("balance")
			}

			return err
		}
	}

	return nil
}

func (m *CardBalance) contextValidateCard(ctx context.Context, formats strfmt.Registry) error {

	if m.Card != nil {

		if typeutils.IsZero(m.Card) { // not required
			return nil
		}

		if err := m.Card.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("card")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("card")
			}

			return err
		}
	}

	return nil
}

func (m *CardBalance) contextValidateCardID(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "cardId", "body", m.CardID); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *CardBalance) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CardBalance) UnmarshalBinary(b []byte) error {
	var res CardBalance
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
