// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	"encoding/json"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
	"github.com/go-openapi/validate"
)

// Card Model for a card.
//
// swagger:model Card
type Card struct {

	// Partially masked credit card number.
	// Example: XXXX XXXX XXXX 1234
	// Read Only: true
	CardDisplayID string `json:"cardDisplayId,omitempty"`

	// Card identifier (UUID).
	// Example: 0123456789ABCDEF0123456789ABCDEF
	// Read Only: true
	CardID string `json:"cardId,omitempty"`

	// Image of the card.
	// Read Only: true
	CardImage *VisaCardImage `json:"cardImage,omitempty"`

	// Card limit if available. Will be 0.00 EUR if card has no limit.
	CardLimit *AmountValue `json:"cardLimit,omitempty"`

	// Type of the card. 'key' contains the card type, 'text' a description
	// Example: {\"key\" : \"VISA_CREDIT\", \"text\" : \"Visa-Karte (Kreditkarte)\
	// Read Only: true
	CardType *EnumText `json:"cardType,omitempty"`

	// validity of the card. Format: MM/YY
	// Example: 01/21
	// Read Only: true
	CardValidity string `json:"cardValidity,omitempty"`

	// Client connection uniquely assigned to the credit card account.
	// Example: 0123456789ABCDEF0123456789ABCDEF
	// Read Only: true
	ClientID string `json:"clientId,omitempty"`

	// Name of the card holder
	// Example: Tommer Tapir
	// Read Only: true
	HolderName string `json:"holderName,omitempty"`

	// Contract code of the client uniquely assigned to the credit card account.
	// Example: 0123456789ABCDEF0123456789ABCDEF
	// Read Only: true
	ParticipantID string `json:"participantId,omitempty"`

	// Last 4 digits of the credit card number
	// Example: 1234
	// Read Only: true
	PrimaryAccountNumberSuffix string `json:"primaryAccountNumberSuffix,omitempty"`

	// Default settlement account number uniquely assigned to the credit card account. In this case, it has to be the current account.
	// Example: 0123456789ABCDEF0123456789ABCDEF
	// Read Only: true
	SettlementAccountID string `json:"settlementAccountId,omitempty"`

	// Status of the card.
	// Example: ACTIVE
	// Enum: ["ACTIVE","INACTIVE","IN_CHANGE","UNKNOWN"]
	Status string `json:"status,omitempty"`
}

// Validate validates this card
func (m *Card) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCardImage(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCardLimit(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCardType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Card) validateCardImage(formats strfmt.Registry) error {
	if typeutils.IsZero(m.CardImage) { // not required
		return nil
	}

	if m.CardImage != nil {
		if err := m.CardImage.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("cardImage")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("cardImage")
			}

			return err
		}
	}

	return nil
}

func (m *Card) validateCardLimit(formats strfmt.Registry) error {
	if typeutils.IsZero(m.CardLimit) { // not required
		return nil
	}

	if m.CardLimit != nil {
		if err := m.CardLimit.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("cardLimit")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("cardLimit")
			}

			return err
		}
	}

	return nil
}

func (m *Card) validateCardType(formats strfmt.Registry) error {
	if typeutils.IsZero(m.CardType) { // not required
		return nil
	}

	if m.CardType != nil {
		if err := m.CardType.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("cardType")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("cardType")
			}

			return err
		}
	}

	return nil
}

var cardTypeStatusPropEnum []any

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["ACTIVE","INACTIVE","IN_CHANGE","UNKNOWN"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		cardTypeStatusPropEnum = append(cardTypeStatusPropEnum, v)
	}
}

const (

	// CardStatusACTIVE captures enum value "ACTIVE"
	CardStatusACTIVE string = "ACTIVE"

	// CardStatusINACTIVE captures enum value "INACTIVE"
	CardStatusINACTIVE string = "INACTIVE"

	// CardStatusINCHANGE captures enum value "IN_CHANGE"
	CardStatusINCHANGE string = "IN_CHANGE"

	// CardStatusUNKNOWN captures enum value "UNKNOWN"
	CardStatusUNKNOWN string = "UNKNOWN"
)

// prop value enum
func (m *Card) validateStatusEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, cardTypeStatusPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *Card) validateStatus(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Status) { // not required
		return nil
	}

	// value enum
	if err := m.validateStatusEnum("status", "body", m.Status); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this card based on the context it is used
func (m *Card) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateCardDisplayID(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateCardID(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateCardImage(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateCardLimit(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateCardType(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateCardValidity(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateClientID(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateHolderName(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateParticipantID(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidatePrimaryAccountNumberSuffix(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateSettlementAccountID(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Card) contextValidateCardDisplayID(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "cardDisplayId", "body", m.CardDisplayID); err != nil {
		return err
	}

	return nil
}

func (m *Card) contextValidateCardID(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "cardId", "body", m.CardID); err != nil {
		return err
	}

	return nil
}

func (m *Card) contextValidateCardImage(ctx context.Context, formats strfmt.Registry) error {

	if m.CardImage != nil {

		if typeutils.IsZero(m.CardImage) { // not required
			return nil
		}

		if err := m.CardImage.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("cardImage")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("cardImage")
			}

			return err
		}
	}

	return nil
}

func (m *Card) contextValidateCardLimit(ctx context.Context, formats strfmt.Registry) error {

	if m.CardLimit != nil {

		if typeutils.IsZero(m.CardLimit) { // not required
			return nil
		}

		if err := m.CardLimit.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("cardLimit")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("cardLimit")
			}

			return err
		}
	}

	return nil
}

func (m *Card) contextValidateCardType(ctx context.Context, formats strfmt.Registry) error {

	if m.CardType != nil {

		if typeutils.IsZero(m.CardType) { // not required
			return nil
		}

		if err := m.CardType.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("cardType")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("cardType")
			}

			return err
		}
	}

	return nil
}

func (m *Card) contextValidateCardValidity(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "cardValidity", "body", m.CardValidity); err != nil {
		return err
	}

	return nil
}

func (m *Card) contextValidateClientID(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "clientId", "body", m.ClientID); err != nil {
		return err
	}

	return nil
}

func (m *Card) contextValidateHolderName(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "holderName", "body", m.HolderName); err != nil {
		return err
	}

	return nil
}

func (m *Card) contextValidateParticipantID(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "participantId", "body", m.ParticipantID); err != nil {
		return err
	}

	return nil
}

func (m *Card) contextValidatePrimaryAccountNumberSuffix(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "primaryAccountNumberSuffix", "body", m.PrimaryAccountNumberSuffix); err != nil {
		return err
	}

	return nil
}

func (m *Card) contextValidateSettlementAccountID(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "settlementAccountId", "body", m.SettlementAccountID); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Card) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Card) UnmarshalBinary(b []byte) error {
	var res Card
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
