// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	"encoding/json"
	stderrors "errors"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
	"github.com/go-openapi/validate"
)

// CostGroup Model for a cost group including a list of cost entries for this cost group.
//
// swagger:model CostGroup
type CostGroup struct {

	// List of costs per cost group
	// Read Only: true
	Costs []*CostEntry `json:"costs"`

	// Name of cost group for showing in the cost-note
	// Read Only: true
	Label string `json:"label,omitempty"`

	// Sum of the cost group in trading currency (quantity.amount.unit)
	// Read Only: true
	Sum *AmountValue `json:"sum,omitempty"`

	// Sum of the cost group in reporting currency
	// Read Only: true
	SumReportingCurrency *AmountValue `json:"sumReportingCurrency,omitempty"`

	// Type of cost group. K: Costs of securities purchase, H: Costs of the holding period (per year), V: Costs of the sale of securities
	// Read Only: true
	// Enum: ["K","H","V"]
	Type string `json:"type,omitempty"`
}

// Validate validates this cost group
func (m *CostGroup) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCosts(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSum(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSumReportingCurrency(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CostGroup) validateCosts(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Costs) { // not required
		return nil
	}

	for i := 0; i < len(m.Costs); i++ {
		if typeutils.IsZero(m.Costs[i]) { // not required
			continue
		}

		if m.Costs[i] != nil {
			if err := m.Costs[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("costs" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("costs" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *CostGroup) validateSum(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Sum) { // not required
		return nil
	}

	if m.Sum != nil {
		if err := m.Sum.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("sum")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("sum")
			}

			return err
		}
	}

	return nil
}

func (m *CostGroup) validateSumReportingCurrency(formats strfmt.Registry) error {
	if typeutils.IsZero(m.SumReportingCurrency) { // not required
		return nil
	}

	if m.SumReportingCurrency != nil {
		if err := m.SumReportingCurrency.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("sumReportingCurrency")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("sumReportingCurrency")
			}

			return err
		}
	}

	return nil
}

var costGroupTypeTypePropEnum []any

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["K","H","V"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		costGroupTypeTypePropEnum = append(costGroupTypeTypePropEnum, v)
	}
}

const (

	// CostGroupTypeK captures enum value "K"
	CostGroupTypeK string = "K"

	// CostGroupTypeH captures enum value "H"
	CostGroupTypeH string = "H"

	// CostGroupTypeV captures enum value "V"
	CostGroupTypeV string = "V"
)

// prop value enum
func (m *CostGroup) validateTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, costGroupTypeTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *CostGroup) validateType(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Type) { // not required
		return nil
	}

	// value enum
	if err := m.validateTypeEnum("type", "body", m.Type); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this cost group based on the context it is used
func (m *CostGroup) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateCosts(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateLabel(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateSum(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateSumReportingCurrency(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateType(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CostGroup) contextValidateCosts(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "costs", "body", m.Costs); err != nil {
		return err
	}

	for i := 0; i < len(m.Costs); i++ {

		if m.Costs[i] != nil {

			if typeutils.IsZero(m.Costs[i]) { // not required
				return nil
			}

			if err := m.Costs[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("costs" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("costs" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *CostGroup) contextValidateLabel(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "label", "body", m.Label); err != nil {
		return err
	}

	return nil
}

func (m *CostGroup) contextValidateSum(ctx context.Context, formats strfmt.Registry) error {

	if m.Sum != nil {

		if typeutils.IsZero(m.Sum) { // not required
			return nil
		}

		if err := m.Sum.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("sum")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("sum")
			}

			return err
		}
	}

	return nil
}

func (m *CostGroup) contextValidateSumReportingCurrency(ctx context.Context, formats strfmt.Registry) error {

	if m.SumReportingCurrency != nil {

		if typeutils.IsZero(m.SumReportingCurrency) { // not required
			return nil
		}

		if err := m.SumReportingCurrency.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("sumReportingCurrency")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("sumReportingCurrency")
			}

			return err
		}
	}

	return nil
}

func (m *CostGroup) contextValidateType(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "type", "body", m.Type); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *CostGroup) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CostGroup) UnmarshalBinary(b []byte) error {
	var res CostGroup
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
