// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	"encoding/json"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
	"github.com/go-openapi/validate"
)

// CostEntry Cost entry of a cost group.
//
// swagger:model CostEntry
type CostEntry struct {

	// Cost in trading currency
	// Read Only: true
	Amount *AmountValue `json:"amount,omitempty"`

	// Cost in reporting currency
	// Read Only: true
	AmountReportingCurrency *AmountValue `json:"amountReportingCurrency,omitempty"`

	// Inducement of the cost entry
	// Read Only: true
	Inducement *Inducement `json:"inducement,omitempty"`

	// Label of the cost entry
	// Example: Orderprovision
	// Read Only: true
	Label string `json:"label,omitempty"`

	// Type of the cost entry
	// Read Only: true
	// Enum: ["E","F","P"]
	Type string `json:"type,omitempty"`
}

// Validate validates this cost entry
func (m *CostEntry) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAmount(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateAmountReportingCurrency(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateInducement(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CostEntry) validateAmount(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Amount) { // not required
		return nil
	}

	if m.Amount != nil {
		if err := m.Amount.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("amount")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("amount")
			}

			return err
		}
	}

	return nil
}

func (m *CostEntry) validateAmountReportingCurrency(formats strfmt.Registry) error {
	if typeutils.IsZero(m.AmountReportingCurrency) { // not required
		return nil
	}

	if m.AmountReportingCurrency != nil {
		if err := m.AmountReportingCurrency.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("amountReportingCurrency")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("amountReportingCurrency")
			}

			return err
		}
	}

	return nil
}

func (m *CostEntry) validateInducement(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Inducement) { // not required
		return nil
	}

	if m.Inducement != nil {
		if err := m.Inducement.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("inducement")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("inducement")
			}

			return err
		}
	}

	return nil
}

var costEntryTypeTypePropEnum []any

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["E","F","P"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		costEntryTypeTypePropEnum = append(costEntryTypeTypePropEnum, v)
	}
}

const (

	// CostEntryTypeE captures enum value "E"
	CostEntryTypeE string = "E"

	// CostEntryTypeF captures enum value "F"
	CostEntryTypeF string = "F"

	// CostEntryTypeP captures enum value "P"
	CostEntryTypeP string = "P"
)

// prop value enum
func (m *CostEntry) validateTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, costEntryTypeTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *CostEntry) validateType(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Type) { // not required
		return nil
	}

	// value enum
	if err := m.validateTypeEnum("type", "body", m.Type); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this cost entry based on the context it is used
func (m *CostEntry) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAmount(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateAmountReportingCurrency(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateInducement(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateLabel(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateType(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CostEntry) contextValidateAmount(ctx context.Context, formats strfmt.Registry) error {

	if m.Amount != nil {

		if typeutils.IsZero(m.Amount) { // not required
			return nil
		}

		if err := m.Amount.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("amount")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("amount")
			}

			return err
		}
	}

	return nil
}

func (m *CostEntry) contextValidateAmountReportingCurrency(ctx context.Context, formats strfmt.Registry) error {

	if m.AmountReportingCurrency != nil {

		if typeutils.IsZero(m.AmountReportingCurrency) { // not required
			return nil
		}

		if err := m.AmountReportingCurrency.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("amountReportingCurrency")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("amountReportingCurrency")
			}

			return err
		}
	}

	return nil
}

func (m *CostEntry) contextValidateInducement(ctx context.Context, formats strfmt.Registry) error {

	if m.Inducement != nil {

		if typeutils.IsZero(m.Inducement) { // not required
			return nil
		}

		if err := m.Inducement.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("inducement")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("inducement")
			}

			return err
		}
	}

	return nil
}

func (m *CostEntry) contextValidateLabel(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "label", "body", m.Label); err != nil {
		return err
	}

	return nil
}

func (m *CostEntry) contextValidateType(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "type", "body", m.Type); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *CostEntry) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CostEntry) UnmarshalBinary(b []byte) error {
	var res CostEntry
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
