// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
	"github.com/go-openapi/validate"
)

// CurrencyString Represents the ISO-4217 code of the currency.
//
// swagger:model CurrencyString
type CurrencyString struct {

	// currency
	// Example: EUR
	// Max Length: 3
	// Min Length: 3
	Currency string `json:"Currency,omitempty"`
}

// Validate validates this currency string
func (m *CurrencyString) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCurrency(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CurrencyString) validateCurrency(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Currency) { // not required
		return nil
	}

	if err := validate.MinLength("Currency", "body", m.Currency, 3); err != nil {
		return err
	}

	if err := validate.MaxLength("Currency", "body", m.Currency, 3); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this currency string based on context it is used
func (m *CurrencyString) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CurrencyString) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CurrencyString) UnmarshalBinary(b []byte) error {
	var res CurrencyString
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
