// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
	"github.com/go-openapi/validate"
)

// DateTimeString Represents the date with the time.
//
// swagger:model DateTimeString
type DateTimeString struct {

	// Time with format: 'yyyy-MM-dd'T'HH:mm:ssX'
	// Example: 2018-07-03T15:40:30+01
	// Format: date-time
	DateTime strfmt.DateTime `json:"dateTime,omitempty"`
}

// Validate validates this date time string
func (m *DateTimeString) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDateTime(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DateTimeString) validateDateTime(formats strfmt.Registry) error {
	if typeutils.IsZero(m.DateTime) { // not required
		return nil
	}

	if err := validate.FormatOf("dateTime", "body", "date-time", m.DateTime.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this date time string based on context it is used
func (m *DateTimeString) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DateTimeString) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DateTimeString) UnmarshalBinary(b []byte) error {
	var res DateTimeString
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
