// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	"encoding/json"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
	"github.com/go-openapi/validate"
)

// DepotTransaction Model for a depot transaction.
//
// swagger:model DepotTransaction
type DepotTransaction struct {

	// The booking date
	// Read Only: true
	BookingDate *DateString `json:"bookingDate,omitempty"`

	// Status of transaction
	// Read Only: true
	// Enum: ["BOOKED","NOTBOOKED"]
	BookingStatus string `json:"bookingStatus,omitempty"`

	// The business date
	// Read Only: true
	BusinessDate *DateString `json:"businessDate,omitempty"`

	// Price of the execution
	// Read Only: true
	ExecutionPrice *AmountValue `json:"executionPrice,omitempty"`

	// Exchange rate settlement currency EUR to FX if exectionPrice amount is not notated in EUR
	// Read Only: true
	FxRate *FXRateEUR `json:"fxRate,omitempty"`

	// Information about the instrument of the securities position
	// Read Only: true
	Instrument *Instrument `json:"instrument,omitempty"`

	// InstrumentId as UUID
	// Read Only: true
	InstrumentID string `json:"instrumentId,omitempty"`

	// The quantity
	// Read Only: true
	Quantity *AmountValue `json:"quantity,omitempty"`

	// Date and time of settlement
	// Read Only: true
	SettlementDate *DateTimeString `json:"settlementDate,omitempty"`

	// Transaction direction
	// Read Only: true
	// Enum: ["IN","OUT"]
	TransactionDirection string `json:"transactionDirection,omitempty"`

	// Transaction Identifier (UUID)
	// Read Only: true
	TransactionID string `json:"transactionId,omitempty"`

	// On the basis of securities account turnover transaction type
	// Read Only: true
	// Enum: ["BUY","SELL","TRANSFER_IN","TRANSFER_OUT","OTHER"]
	TransactionType string `json:"transactionType,omitempty"`

	// Value of the transaction
	// Read Only: true
	TransactionValue *AmountValue `json:"transactionValue,omitempty"`
}

// Validate validates this depot transaction
func (m *DepotTransaction) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBookingDate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateBookingStatus(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateBusinessDate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateExecutionPrice(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateFxRate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateInstrument(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateQuantity(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSettlementDate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTransactionDirection(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTransactionType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTransactionValue(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DepotTransaction) validateBookingDate(formats strfmt.Registry) error {
	if typeutils.IsZero(m.BookingDate) { // not required
		return nil
	}

	if m.BookingDate != nil {
		if err := m.BookingDate.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("bookingDate")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("bookingDate")
			}

			return err
		}
	}

	return nil
}

var depotTransactionTypeBookingStatusPropEnum []any

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["BOOKED","NOTBOOKED"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		depotTransactionTypeBookingStatusPropEnum = append(depotTransactionTypeBookingStatusPropEnum, v)
	}
}

const (

	// DepotTransactionBookingStatusBOOKED captures enum value "BOOKED"
	DepotTransactionBookingStatusBOOKED string = "BOOKED"

	// DepotTransactionBookingStatusNOTBOOKED captures enum value "NOTBOOKED"
	DepotTransactionBookingStatusNOTBOOKED string = "NOTBOOKED"
)

// prop value enum
func (m *DepotTransaction) validateBookingStatusEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, depotTransactionTypeBookingStatusPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *DepotTransaction) validateBookingStatus(formats strfmt.Registry) error {
	if typeutils.IsZero(m.BookingStatus) { // not required
		return nil
	}

	// value enum
	if err := m.validateBookingStatusEnum("bookingStatus", "body", m.BookingStatus); err != nil {
		return err
	}

	return nil
}

func (m *DepotTransaction) validateBusinessDate(formats strfmt.Registry) error {
	if typeutils.IsZero(m.BusinessDate) { // not required
		return nil
	}

	if m.BusinessDate != nil {
		if err := m.BusinessDate.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("businessDate")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("businessDate")
			}

			return err
		}
	}

	return nil
}

func (m *DepotTransaction) validateExecutionPrice(formats strfmt.Registry) error {
	if typeutils.IsZero(m.ExecutionPrice) { // not required
		return nil
	}

	if m.ExecutionPrice != nil {
		if err := m.ExecutionPrice.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("executionPrice")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("executionPrice")
			}

			return err
		}
	}

	return nil
}

func (m *DepotTransaction) validateFxRate(formats strfmt.Registry) error {
	if typeutils.IsZero(m.FxRate) { // not required
		return nil
	}

	if m.FxRate != nil {
		if err := m.FxRate.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("fxRate")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("fxRate")
			}

			return err
		}
	}

	return nil
}

func (m *DepotTransaction) validateInstrument(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Instrument) { // not required
		return nil
	}

	if m.Instrument != nil {
		if err := m.Instrument.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("instrument")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("instrument")
			}

			return err
		}
	}

	return nil
}

func (m *DepotTransaction) validateQuantity(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Quantity) { // not required
		return nil
	}

	if m.Quantity != nil {
		if err := m.Quantity.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("quantity")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("quantity")
			}

			return err
		}
	}

	return nil
}

func (m *DepotTransaction) validateSettlementDate(formats strfmt.Registry) error {
	if typeutils.IsZero(m.SettlementDate) { // not required
		return nil
	}

	if m.SettlementDate != nil {
		if err := m.SettlementDate.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("settlementDate")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("settlementDate")
			}

			return err
		}
	}

	return nil
}

var depotTransactionTypeTransactionDirectionPropEnum []any

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["IN","OUT"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		depotTransactionTypeTransactionDirectionPropEnum = append(depotTransactionTypeTransactionDirectionPropEnum, v)
	}
}

const (

	// DepotTransactionTransactionDirectionIN captures enum value "IN"
	DepotTransactionTransactionDirectionIN string = "IN"

	// DepotTransactionTransactionDirectionOUT captures enum value "OUT"
	DepotTransactionTransactionDirectionOUT string = "OUT"
)

// prop value enum
func (m *DepotTransaction) validateTransactionDirectionEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, depotTransactionTypeTransactionDirectionPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *DepotTransaction) validateTransactionDirection(formats strfmt.Registry) error {
	if typeutils.IsZero(m.TransactionDirection) { // not required
		return nil
	}

	// value enum
	if err := m.validateTransactionDirectionEnum("transactionDirection", "body", m.TransactionDirection); err != nil {
		return err
	}

	return nil
}

var depotTransactionTypeTransactionTypePropEnum []any

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["BUY","SELL","TRANSFER_IN","TRANSFER_OUT","OTHER"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		depotTransactionTypeTransactionTypePropEnum = append(depotTransactionTypeTransactionTypePropEnum, v)
	}
}

const (

	// DepotTransactionTransactionTypeBUY captures enum value "BUY"
	DepotTransactionTransactionTypeBUY string = "BUY"

	// DepotTransactionTransactionTypeSELL captures enum value "SELL"
	DepotTransactionTransactionTypeSELL string = "SELL"

	// DepotTransactionTransactionTypeTRANSFERIN captures enum value "TRANSFER_IN"
	DepotTransactionTransactionTypeTRANSFERIN string = "TRANSFER_IN"

	// DepotTransactionTransactionTypeTRANSFEROUT captures enum value "TRANSFER_OUT"
	DepotTransactionTransactionTypeTRANSFEROUT string = "TRANSFER_OUT"

	// DepotTransactionTransactionTypeOTHER captures enum value "OTHER"
	DepotTransactionTransactionTypeOTHER string = "OTHER"
)

// prop value enum
func (m *DepotTransaction) validateTransactionTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, depotTransactionTypeTransactionTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *DepotTransaction) validateTransactionType(formats strfmt.Registry) error {
	if typeutils.IsZero(m.TransactionType) { // not required
		return nil
	}

	// value enum
	if err := m.validateTransactionTypeEnum("transactionType", "body", m.TransactionType); err != nil {
		return err
	}

	return nil
}

func (m *DepotTransaction) validateTransactionValue(formats strfmt.Registry) error {
	if typeutils.IsZero(m.TransactionValue) { // not required
		return nil
	}

	if m.TransactionValue != nil {
		if err := m.TransactionValue.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("transactionValue")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("transactionValue")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this depot transaction based on the context it is used
func (m *DepotTransaction) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateBookingDate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateBookingStatus(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateBusinessDate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateExecutionPrice(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateFxRate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateInstrument(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateInstrumentID(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateQuantity(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateSettlementDate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateTransactionDirection(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateTransactionID(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateTransactionType(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateTransactionValue(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DepotTransaction) contextValidateBookingDate(ctx context.Context, formats strfmt.Registry) error {

	if m.BookingDate != nil {

		if typeutils.IsZero(m.BookingDate) { // not required
			return nil
		}

		if err := m.BookingDate.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("bookingDate")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("bookingDate")
			}

			return err
		}
	}

	return nil
}

func (m *DepotTransaction) contextValidateBookingStatus(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "bookingStatus", "body", m.BookingStatus); err != nil {
		return err
	}

	return nil
}

func (m *DepotTransaction) contextValidateBusinessDate(ctx context.Context, formats strfmt.Registry) error {

	if m.BusinessDate != nil {

		if typeutils.IsZero(m.BusinessDate) { // not required
			return nil
		}

		if err := m.BusinessDate.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("businessDate")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("businessDate")
			}

			return err
		}
	}

	return nil
}

func (m *DepotTransaction) contextValidateExecutionPrice(ctx context.Context, formats strfmt.Registry) error {

	if m.ExecutionPrice != nil {

		if typeutils.IsZero(m.ExecutionPrice) { // not required
			return nil
		}

		if err := m.ExecutionPrice.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("executionPrice")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("executionPrice")
			}

			return err
		}
	}

	return nil
}

func (m *DepotTransaction) contextValidateFxRate(ctx context.Context, formats strfmt.Registry) error {

	if m.FxRate != nil {

		if typeutils.IsZero(m.FxRate) { // not required
			return nil
		}

		if err := m.FxRate.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("fxRate")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("fxRate")
			}

			return err
		}
	}

	return nil
}

func (m *DepotTransaction) contextValidateInstrument(ctx context.Context, formats strfmt.Registry) error {

	if m.Instrument != nil {

		if typeutils.IsZero(m.Instrument) { // not required
			return nil
		}

		if err := m.Instrument.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("instrument")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("instrument")
			}

			return err
		}
	}

	return nil
}

func (m *DepotTransaction) contextValidateInstrumentID(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "instrumentId", "body", m.InstrumentID); err != nil {
		return err
	}

	return nil
}

func (m *DepotTransaction) contextValidateQuantity(ctx context.Context, formats strfmt.Registry) error {

	if m.Quantity != nil {

		if typeutils.IsZero(m.Quantity) { // not required
			return nil
		}

		if err := m.Quantity.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("quantity")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("quantity")
			}

			return err
		}
	}

	return nil
}

func (m *DepotTransaction) contextValidateSettlementDate(ctx context.Context, formats strfmt.Registry) error {

	if m.SettlementDate != nil {

		if typeutils.IsZero(m.SettlementDate) { // not required
			return nil
		}

		if err := m.SettlementDate.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("settlementDate")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("settlementDate")
			}

			return err
		}
	}

	return nil
}

func (m *DepotTransaction) contextValidateTransactionDirection(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "transactionDirection", "body", m.TransactionDirection); err != nil {
		return err
	}

	return nil
}

func (m *DepotTransaction) contextValidateTransactionID(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "transactionId", "body", m.TransactionID); err != nil {
		return err
	}

	return nil
}

func (m *DepotTransaction) contextValidateTransactionType(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "transactionType", "body", m.TransactionType); err != nil {
		return err
	}

	return nil
}

func (m *DepotTransaction) contextValidateTransactionValue(ctx context.Context, formats strfmt.Registry) error {

	if m.TransactionValue != nil {

		if typeutils.IsZero(m.TransactionValue) { // not required
			return nil
		}

		if err := m.TransactionValue.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("transactionValue")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("transactionValue")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *DepotTransaction) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DepotTransaction) UnmarshalBinary(b []byte) error {
	var res DepotTransaction
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
