// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/validate"
)

// Depot depot
//
// swagger:model Depot
type Depot struct {

	// Identification code of the client uniquely assigned to the securities account
	// Example: 0123456789ABCDEF0123456789ABCDEF
	// Read Only: true
	ClientID string `json:"clientId,omitempty"`

	// Default settlement account number uniquely assigned to the securities account
	// Read Only: true
	DefaultSettlementAccountID string `json:"defaultSettlementAccountId,omitempty"`

	// Securities account Number
	// Read Only: true
	DepotDisplayID string `json:"depotDisplayId,omitempty"`

	// Securities account Identifier (UUID)
	// Read Only: true
	DepotID string `json:"depotId,omitempty"`

	// List of other settlement account identification numbers assigned to the securities account
	// Read Only: true
	SettlementAccountIds []string `json:"settlementAccountIds"`
}

// Validate validates this depot
func (m *Depot) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validate this depot based on the context it is used
func (m *Depot) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateClientID(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateDefaultSettlementAccountID(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateDepotDisplayID(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateDepotID(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateSettlementAccountIds(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Depot) contextValidateClientID(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "clientId", "body", m.ClientID); err != nil {
		return err
	}

	return nil
}

func (m *Depot) contextValidateDefaultSettlementAccountID(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "defaultSettlementAccountId", "body", m.DefaultSettlementAccountID); err != nil {
		return err
	}

	return nil
}

func (m *Depot) contextValidateDepotDisplayID(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "depotDisplayId", "body", m.DepotDisplayID); err != nil {
		return err
	}

	return nil
}

func (m *Depot) contextValidateDepotID(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "depotId", "body", m.DepotID); err != nil {
		return err
	}

	return nil
}

func (m *Depot) contextValidateSettlementAccountIds(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "settlementAccountIds", "body", m.SettlementAccountIds); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Depot) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Depot) UnmarshalBinary(b []byte) error {
	var res Depot
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
