// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
	"github.com/go-openapi/validate"
)

// DepotPosition depot position
//
// swagger:model DepotPosition
type DepotPosition struct {

	// Available quantity or nominal amount in case of a percentage quotation
	// Read Only: true
	AvailableQuantity *AmountValue `json:"availableQuantity,omitempty"`

	// Current price, if available
	// Read Only: true
	CurrentPrice *Price `json:"currentPrice,omitempty"`

	// Current value of the position
	// Read Only: true
	CurrentValue *AmountValue `json:"currentValue,omitempty"`

	// Custody type
	// Read Only: true
	CustodyType string `json:"custodyType,omitempty"`

	// Securities account Identifier (UUID)
	// Read Only: true
	DepotID string `json:"depotId,omitempty"`

	// Information about the instrument of the securities position
	// Read Only: true
	Instrument *Instrument `json:"instrument,omitempty"`

	// Position identification number in securities account
	// Read Only: true
	PositionID string `json:"positionId,omitempty"`

	// Price of the previous day, if available
	// Read Only: true
	PrevDayPrice *Price `json:"prevDayPrice,omitempty"`

	// Position value at previous day's closing price
	// Read Only: true
	PrevDayValue *AmountValue `json:"prevDayValue,omitempty"`

	// Absolute profit/loss compared to previous day, if available
	// Read Only: true
	ProfitLossPrevDayAbs *AmountValue `json:"profitLossPrevDayAbs,omitempty"`

	// Profit/Loss compared to previous day in percentage, if available
	// Read Only: true
	ProfitLossPrevDayRel *PercentageString `json:"profitLossPrevDayRel,omitempty"`

	// Absolute profit/loss at purchase price, if available
	// Read Only: true
	ProfitLossPurchaseAbs *AmountValue `json:"profitLossPurchaseAbs,omitempty"`

	// Profit/loss relative to purchase value in percentage, if available
	// Read Only: true
	ProfitLossPurchaseRel *PercentageString `json:"profitLossPurchaseRel,omitempty"`

	// Purchase price, if available
	// Read Only: true
	PurchasePrice *AmountValue `json:"purchasePrice,omitempty"`

	// Average purchase value of the position
	// Read Only: true
	PurchaseValue *AmountValue `json:"purchaseValue,omitempty"`

	// Quantity or nominal amount in case of a percentage quotation
	// Read Only: true
	Quantity *AmountValue `json:"quantity,omitempty"`

	// Position version, if available
	// Read Only: true
	Version string `json:"version,omitempty"`

	// Identification number of the instrument
	// Read Only: true
	Wkn string `json:"wkn,omitempty"`
}

// Validate validates this depot position
func (m *DepotPosition) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAvailableQuantity(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCurrentPrice(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCurrentValue(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateInstrument(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePrevDayPrice(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePrevDayValue(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProfitLossPrevDayAbs(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProfitLossPrevDayRel(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProfitLossPurchaseAbs(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProfitLossPurchaseRel(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePurchasePrice(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePurchaseValue(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateQuantity(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DepotPosition) validateAvailableQuantity(formats strfmt.Registry) error {
	if typeutils.IsZero(m.AvailableQuantity) { // not required
		return nil
	}

	if m.AvailableQuantity != nil {
		if err := m.AvailableQuantity.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("availableQuantity")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("availableQuantity")
			}

			return err
		}
	}

	return nil
}

func (m *DepotPosition) validateCurrentPrice(formats strfmt.Registry) error {
	if typeutils.IsZero(m.CurrentPrice) { // not required
		return nil
	}

	if m.CurrentPrice != nil {
		if err := m.CurrentPrice.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("currentPrice")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("currentPrice")
			}

			return err
		}
	}

	return nil
}

func (m *DepotPosition) validateCurrentValue(formats strfmt.Registry) error {
	if typeutils.IsZero(m.CurrentValue) { // not required
		return nil
	}

	if m.CurrentValue != nil {
		if err := m.CurrentValue.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("currentValue")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("currentValue")
			}

			return err
		}
	}

	return nil
}

func (m *DepotPosition) validateInstrument(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Instrument) { // not required
		return nil
	}

	if m.Instrument != nil {
		if err := m.Instrument.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("instrument")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("instrument")
			}

			return err
		}
	}

	return nil
}

func (m *DepotPosition) validatePrevDayPrice(formats strfmt.Registry) error {
	if typeutils.IsZero(m.PrevDayPrice) { // not required
		return nil
	}

	if m.PrevDayPrice != nil {
		if err := m.PrevDayPrice.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("prevDayPrice")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("prevDayPrice")
			}

			return err
		}
	}

	return nil
}

func (m *DepotPosition) validatePrevDayValue(formats strfmt.Registry) error {
	if typeutils.IsZero(m.PrevDayValue) { // not required
		return nil
	}

	if m.PrevDayValue != nil {
		if err := m.PrevDayValue.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("prevDayValue")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("prevDayValue")
			}

			return err
		}
	}

	return nil
}

func (m *DepotPosition) validateProfitLossPrevDayAbs(formats strfmt.Registry) error {
	if typeutils.IsZero(m.ProfitLossPrevDayAbs) { // not required
		return nil
	}

	if m.ProfitLossPrevDayAbs != nil {
		if err := m.ProfitLossPrevDayAbs.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("profitLossPrevDayAbs")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("profitLossPrevDayAbs")
			}

			return err
		}
	}

	return nil
}

func (m *DepotPosition) validateProfitLossPrevDayRel(formats strfmt.Registry) error {
	if typeutils.IsZero(m.ProfitLossPrevDayRel) { // not required
		return nil
	}

	if m.ProfitLossPrevDayRel != nil {
		if err := m.ProfitLossPrevDayRel.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("profitLossPrevDayRel")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("profitLossPrevDayRel")
			}

			return err
		}
	}

	return nil
}

func (m *DepotPosition) validateProfitLossPurchaseAbs(formats strfmt.Registry) error {
	if typeutils.IsZero(m.ProfitLossPurchaseAbs) { // not required
		return nil
	}

	if m.ProfitLossPurchaseAbs != nil {
		if err := m.ProfitLossPurchaseAbs.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("profitLossPurchaseAbs")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("profitLossPurchaseAbs")
			}

			return err
		}
	}

	return nil
}

func (m *DepotPosition) validateProfitLossPurchaseRel(formats strfmt.Registry) error {
	if typeutils.IsZero(m.ProfitLossPurchaseRel) { // not required
		return nil
	}

	if m.ProfitLossPurchaseRel != nil {
		if err := m.ProfitLossPurchaseRel.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("profitLossPurchaseRel")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("profitLossPurchaseRel")
			}

			return err
		}
	}

	return nil
}

func (m *DepotPosition) validatePurchasePrice(formats strfmt.Registry) error {
	if typeutils.IsZero(m.PurchasePrice) { // not required
		return nil
	}

	if m.PurchasePrice != nil {
		if err := m.PurchasePrice.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("purchasePrice")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("purchasePrice")
			}

			return err
		}
	}

	return nil
}

func (m *DepotPosition) validatePurchaseValue(formats strfmt.Registry) error {
	if typeutils.IsZero(m.PurchaseValue) { // not required
		return nil
	}

	if m.PurchaseValue != nil {
		if err := m.PurchaseValue.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("purchaseValue")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("purchaseValue")
			}

			return err
		}
	}

	return nil
}

func (m *DepotPosition) validateQuantity(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Quantity) { // not required
		return nil
	}

	if m.Quantity != nil {
		if err := m.Quantity.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("quantity")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("quantity")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this depot position based on the context it is used
func (m *DepotPosition) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAvailableQuantity(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateCurrentPrice(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateCurrentValue(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateCustodyType(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateDepotID(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateInstrument(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidatePositionID(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidatePrevDayPrice(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidatePrevDayValue(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateProfitLossPrevDayAbs(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateProfitLossPrevDayRel(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateProfitLossPurchaseAbs(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateProfitLossPurchaseRel(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidatePurchasePrice(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidatePurchaseValue(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateQuantity(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateVersion(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateWkn(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DepotPosition) contextValidateAvailableQuantity(ctx context.Context, formats strfmt.Registry) error {

	if m.AvailableQuantity != nil {

		if typeutils.IsZero(m.AvailableQuantity) { // not required
			return nil
		}

		if err := m.AvailableQuantity.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("availableQuantity")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("availableQuantity")
			}

			return err
		}
	}

	return nil
}

func (m *DepotPosition) contextValidateCurrentPrice(ctx context.Context, formats strfmt.Registry) error {

	if m.CurrentPrice != nil {

		if typeutils.IsZero(m.CurrentPrice) { // not required
			return nil
		}

		if err := m.CurrentPrice.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("currentPrice")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("currentPrice")
			}

			return err
		}
	}

	return nil
}

func (m *DepotPosition) contextValidateCurrentValue(ctx context.Context, formats strfmt.Registry) error {

	if m.CurrentValue != nil {

		if typeutils.IsZero(m.CurrentValue) { // not required
			return nil
		}

		if err := m.CurrentValue.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("currentValue")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("currentValue")
			}

			return err
		}
	}

	return nil
}

func (m *DepotPosition) contextValidateCustodyType(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "custodyType", "body", m.CustodyType); err != nil {
		return err
	}

	return nil
}

func (m *DepotPosition) contextValidateDepotID(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "depotId", "body", m.DepotID); err != nil {
		return err
	}

	return nil
}

func (m *DepotPosition) contextValidateInstrument(ctx context.Context, formats strfmt.Registry) error {

	if m.Instrument != nil {

		if typeutils.IsZero(m.Instrument) { // not required
			return nil
		}

		if err := m.Instrument.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("instrument")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("instrument")
			}

			return err
		}
	}

	return nil
}

func (m *DepotPosition) contextValidatePositionID(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "positionId", "body", m.PositionID); err != nil {
		return err
	}

	return nil
}

func (m *DepotPosition) contextValidatePrevDayPrice(ctx context.Context, formats strfmt.Registry) error {

	if m.PrevDayPrice != nil {

		if typeutils.IsZero(m.PrevDayPrice) { // not required
			return nil
		}

		if err := m.PrevDayPrice.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("prevDayPrice")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("prevDayPrice")
			}

			return err
		}
	}

	return nil
}

func (m *DepotPosition) contextValidatePrevDayValue(ctx context.Context, formats strfmt.Registry) error {

	if m.PrevDayValue != nil {

		if typeutils.IsZero(m.PrevDayValue) { // not required
			return nil
		}

		if err := m.PrevDayValue.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("prevDayValue")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("prevDayValue")
			}

			return err
		}
	}

	return nil
}

func (m *DepotPosition) contextValidateProfitLossPrevDayAbs(ctx context.Context, formats strfmt.Registry) error {

	if m.ProfitLossPrevDayAbs != nil {

		if typeutils.IsZero(m.ProfitLossPrevDayAbs) { // not required
			return nil
		}

		if err := m.ProfitLossPrevDayAbs.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("profitLossPrevDayAbs")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("profitLossPrevDayAbs")
			}

			return err
		}
	}

	return nil
}

func (m *DepotPosition) contextValidateProfitLossPrevDayRel(ctx context.Context, formats strfmt.Registry) error {

	if m.ProfitLossPrevDayRel != nil {

		if typeutils.IsZero(m.ProfitLossPrevDayRel) { // not required
			return nil
		}

		if err := m.ProfitLossPrevDayRel.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("profitLossPrevDayRel")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("profitLossPrevDayRel")
			}

			return err
		}
	}

	return nil
}

func (m *DepotPosition) contextValidateProfitLossPurchaseAbs(ctx context.Context, formats strfmt.Registry) error {

	if m.ProfitLossPurchaseAbs != nil {

		if typeutils.IsZero(m.ProfitLossPurchaseAbs) { // not required
			return nil
		}

		if err := m.ProfitLossPurchaseAbs.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("profitLossPurchaseAbs")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("profitLossPurchaseAbs")
			}

			return err
		}
	}

	return nil
}

func (m *DepotPosition) contextValidateProfitLossPurchaseRel(ctx context.Context, formats strfmt.Registry) error {

	if m.ProfitLossPurchaseRel != nil {

		if typeutils.IsZero(m.ProfitLossPurchaseRel) { // not required
			return nil
		}

		if err := m.ProfitLossPurchaseRel.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("profitLossPurchaseRel")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("profitLossPurchaseRel")
			}

			return err
		}
	}

	return nil
}

func (m *DepotPosition) contextValidatePurchasePrice(ctx context.Context, formats strfmt.Registry) error {

	if m.PurchasePrice != nil {

		if typeutils.IsZero(m.PurchasePrice) { // not required
			return nil
		}

		if err := m.PurchasePrice.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("purchasePrice")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("purchasePrice")
			}

			return err
		}
	}

	return nil
}

func (m *DepotPosition) contextValidatePurchaseValue(ctx context.Context, formats strfmt.Registry) error {

	if m.PurchaseValue != nil {

		if typeutils.IsZero(m.PurchaseValue) { // not required
			return nil
		}

		if err := m.PurchaseValue.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("purchaseValue")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("purchaseValue")
			}

			return err
		}
	}

	return nil
}

func (m *DepotPosition) contextValidateQuantity(ctx context.Context, formats strfmt.Registry) error {

	if m.Quantity != nil {

		if typeutils.IsZero(m.Quantity) { // not required
			return nil
		}

		if err := m.Quantity.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("quantity")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("quantity")
			}

			return err
		}
	}

	return nil
}

func (m *DepotPosition) contextValidateVersion(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "version", "body", m.Version); err != nil {
		return err
	}

	return nil
}

func (m *DepotPosition) contextValidateWkn(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "wkn", "body", m.Wkn); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *DepotPosition) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DepotPosition) UnmarshalBinary(b []byte) error {
	var res DepotPosition
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
