// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
	"github.com/go-openapi/validate"
)

// DepotAggregation depot aggregation
//
// swagger:model DepotAggregation
type DepotAggregation struct {

	// Current value of the securities account (the sum of all the securities holdings at their current prices)
	// Read Only: true
	CurrentValue *AmountValue `json:"currentValue,omitempty"`

	// Date of the last update of securities holdings & master data. YYYY-MM-DD
	// Read Only: true
	DateLastUpdate string `json:"dateLastUpdate,omitempty"`

	// The master data of this securities account (this attribute can be suppressed by using the parameter 'without-attr=depot')
	// Read Only: true
	Depot *Depot `json:"depot,omitempty"`

	// Securities account Identifier (UUID)
	// Read Only: true
	DepotID string `json:"depotId,omitempty"`

	// Sum of the lending values of all of the securities holdings
	// Read Only: true
	LendingValue *AmountValue `json:"lendingValue,omitempty"`

	// Value of the securities account (the sum of all the securities holdings at the closing prices of the previous day)
	// Read Only: true
	PrevDayValue *AmountValue `json:"prevDayValue,omitempty"`

	// Absolute profit/loss compared to the previous day
	// Read Only: true
	ProfitLossPrevDayAbs *AmountValue `json:"profitLossPrevDayAbs,omitempty"`

	// Profit/Loss compared to the previous day in percentage
	// Read Only: true
	ProfitLossPrevDayRel *PercentageString `json:"profitLossPrevDayRel,omitempty"`

	// Profit/loss at the absolute purchase value
	// Read Only: true
	ProfitLossPurchaseAbs *AmountValue `json:"profitLossPurchaseAbs,omitempty"`

	// Profit/loss relative to purchase value in percentage
	// Read Only: true
	ProfitLossPurchaseRel *PercentageString `json:"profitLossPurchaseRel,omitempty"`

	// Sum of the purchase values of all the securities holdings
	// Read Only: true
	PurchaseValue *AmountValue `json:"purchaseValue,omitempty"`
}

// Validate validates this depot aggregation
func (m *DepotAggregation) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCurrentValue(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDepot(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLendingValue(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePrevDayValue(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProfitLossPrevDayAbs(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProfitLossPrevDayRel(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProfitLossPurchaseAbs(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProfitLossPurchaseRel(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePurchaseValue(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DepotAggregation) validateCurrentValue(formats strfmt.Registry) error {
	if typeutils.IsZero(m.CurrentValue) { // not required
		return nil
	}

	if m.CurrentValue != nil {
		if err := m.CurrentValue.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("currentValue")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("currentValue")
			}

			return err
		}
	}

	return nil
}

func (m *DepotAggregation) validateDepot(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Depot) { // not required
		return nil
	}

	if m.Depot != nil {
		if err := m.Depot.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("depot")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("depot")
			}

			return err
		}
	}

	return nil
}

func (m *DepotAggregation) validateLendingValue(formats strfmt.Registry) error {
	if typeutils.IsZero(m.LendingValue) { // not required
		return nil
	}

	if m.LendingValue != nil {
		if err := m.LendingValue.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("lendingValue")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("lendingValue")
			}

			return err
		}
	}

	return nil
}

func (m *DepotAggregation) validatePrevDayValue(formats strfmt.Registry) error {
	if typeutils.IsZero(m.PrevDayValue) { // not required
		return nil
	}

	if m.PrevDayValue != nil {
		if err := m.PrevDayValue.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("prevDayValue")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("prevDayValue")
			}

			return err
		}
	}

	return nil
}

func (m *DepotAggregation) validateProfitLossPrevDayAbs(formats strfmt.Registry) error {
	if typeutils.IsZero(m.ProfitLossPrevDayAbs) { // not required
		return nil
	}

	if m.ProfitLossPrevDayAbs != nil {
		if err := m.ProfitLossPrevDayAbs.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("profitLossPrevDayAbs")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("profitLossPrevDayAbs")
			}

			return err
		}
	}

	return nil
}

func (m *DepotAggregation) validateProfitLossPrevDayRel(formats strfmt.Registry) error {
	if typeutils.IsZero(m.ProfitLossPrevDayRel) { // not required
		return nil
	}

	if m.ProfitLossPrevDayRel != nil {
		if err := m.ProfitLossPrevDayRel.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("profitLossPrevDayRel")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("profitLossPrevDayRel")
			}

			return err
		}
	}

	return nil
}

func (m *DepotAggregation) validateProfitLossPurchaseAbs(formats strfmt.Registry) error {
	if typeutils.IsZero(m.ProfitLossPurchaseAbs) { // not required
		return nil
	}

	if m.ProfitLossPurchaseAbs != nil {
		if err := m.ProfitLossPurchaseAbs.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("profitLossPurchaseAbs")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("profitLossPurchaseAbs")
			}

			return err
		}
	}

	return nil
}

func (m *DepotAggregation) validateProfitLossPurchaseRel(formats strfmt.Registry) error {
	if typeutils.IsZero(m.ProfitLossPurchaseRel) { // not required
		return nil
	}

	if m.ProfitLossPurchaseRel != nil {
		if err := m.ProfitLossPurchaseRel.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("profitLossPurchaseRel")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("profitLossPurchaseRel")
			}

			return err
		}
	}

	return nil
}

func (m *DepotAggregation) validatePurchaseValue(formats strfmt.Registry) error {
	if typeutils.IsZero(m.PurchaseValue) { // not required
		return nil
	}

	if m.PurchaseValue != nil {
		if err := m.PurchaseValue.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("purchaseValue")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("purchaseValue")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this depot aggregation based on the context it is used
func (m *DepotAggregation) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateCurrentValue(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateDateLastUpdate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateDepot(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateDepotID(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateLendingValue(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidatePrevDayValue(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateProfitLossPrevDayAbs(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateProfitLossPrevDayRel(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateProfitLossPurchaseAbs(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateProfitLossPurchaseRel(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidatePurchaseValue(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DepotAggregation) contextValidateCurrentValue(ctx context.Context, formats strfmt.Registry) error {

	if m.CurrentValue != nil {

		if typeutils.IsZero(m.CurrentValue) { // not required
			return nil
		}

		if err := m.CurrentValue.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("currentValue")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("currentValue")
			}

			return err
		}
	}

	return nil
}

func (m *DepotAggregation) contextValidateDateLastUpdate(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "dateLastUpdate", "body", m.DateLastUpdate); err != nil {
		return err
	}

	return nil
}

func (m *DepotAggregation) contextValidateDepot(ctx context.Context, formats strfmt.Registry) error {

	if m.Depot != nil {

		if typeutils.IsZero(m.Depot) { // not required
			return nil
		}

		if err := m.Depot.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("depot")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("depot")
			}

			return err
		}
	}

	return nil
}

func (m *DepotAggregation) contextValidateDepotID(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "depotId", "body", m.DepotID); err != nil {
		return err
	}

	return nil
}

func (m *DepotAggregation) contextValidateLendingValue(ctx context.Context, formats strfmt.Registry) error {

	if m.LendingValue != nil {

		if typeutils.IsZero(m.LendingValue) { // not required
			return nil
		}

		if err := m.LendingValue.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("lendingValue")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("lendingValue")
			}

			return err
		}
	}

	return nil
}

func (m *DepotAggregation) contextValidatePrevDayValue(ctx context.Context, formats strfmt.Registry) error {

	if m.PrevDayValue != nil {

		if typeutils.IsZero(m.PrevDayValue) { // not required
			return nil
		}

		if err := m.PrevDayValue.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("prevDayValue")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("prevDayValue")
			}

			return err
		}
	}

	return nil
}

func (m *DepotAggregation) contextValidateProfitLossPrevDayAbs(ctx context.Context, formats strfmt.Registry) error {

	if m.ProfitLossPrevDayAbs != nil {

		if typeutils.IsZero(m.ProfitLossPrevDayAbs) { // not required
			return nil
		}

		if err := m.ProfitLossPrevDayAbs.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("profitLossPrevDayAbs")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("profitLossPrevDayAbs")
			}

			return err
		}
	}

	return nil
}

func (m *DepotAggregation) contextValidateProfitLossPrevDayRel(ctx context.Context, formats strfmt.Registry) error {

	if m.ProfitLossPrevDayRel != nil {

		if typeutils.IsZero(m.ProfitLossPrevDayRel) { // not required
			return nil
		}

		if err := m.ProfitLossPrevDayRel.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("profitLossPrevDayRel")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("profitLossPrevDayRel")
			}

			return err
		}
	}

	return nil
}

func (m *DepotAggregation) contextValidateProfitLossPurchaseAbs(ctx context.Context, formats strfmt.Registry) error {

	if m.ProfitLossPurchaseAbs != nil {

		if typeutils.IsZero(m.ProfitLossPurchaseAbs) { // not required
			return nil
		}

		if err := m.ProfitLossPurchaseAbs.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("profitLossPurchaseAbs")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("profitLossPurchaseAbs")
			}

			return err
		}
	}

	return nil
}

func (m *DepotAggregation) contextValidateProfitLossPurchaseRel(ctx context.Context, formats strfmt.Registry) error {

	if m.ProfitLossPurchaseRel != nil {

		if typeutils.IsZero(m.ProfitLossPurchaseRel) { // not required
			return nil
		}

		if err := m.ProfitLossPurchaseRel.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("profitLossPurchaseRel")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("profitLossPurchaseRel")
			}

			return err
		}
	}

	return nil
}

func (m *DepotAggregation) contextValidatePurchaseValue(ctx context.Context, formats strfmt.Registry) error {

	if m.PurchaseValue != nil {

		if typeutils.IsZero(m.PurchaseValue) { // not required
			return nil
		}

		if err := m.PurchaseValue.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("purchaseValue")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("purchaseValue")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *DepotAggregation) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DepotAggregation) UnmarshalBinary(b []byte) error {
	var res DepotAggregation
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
