// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	"encoding/json"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
	"github.com/go-openapi/validate"
)

// DerivativeData additional data of a derivative
//
// swagger:model DerivativeData
type DerivativeData struct {

	// Certificate Type
	// Read Only: true
	// Enum: ["Hebel","Index","Basket","Hedge-Fonds-Zertifikat","Discount","Aktienanleihe","Bandbreite","Outperformance","Express","Bonus","Kapitalschutz"]
	CertificateType string `json:"certificateType,omitempty"`

	// expiry date of a derivative
	// Example: 2019-03-14
	// Read Only: true
	ExpiryDate string `json:"expiryDate,omitempty"`

	// date of the interest payment of a bond
	// Example: 2019-03-14
	// Read Only: true
	InterestPaymentDate string `json:"interestPaymentDate,omitempty"`

	// interval of the interest payment of a bond",allowableValues = "monthly, quarterly, biannualy, annualy
	// Read Only: true
	// Enum: ["MONTHLY","QUARTERLY","SEMIANNUALLY","ANNUALLY","OTHER"]
	InterestPaymentInterval string `json:"interestPaymentInterval,omitempty"`

	// Leverage of the derivate
	// Example: 13.37
	// Read Only: true
	Leverage string `json:"leverage,omitempty"`

	// maturity Date of a bonds
	// Example: 2019-03-14
	// Read Only: true
	MaturityDate string `json:"maturityDate,omitempty"`

	// multiplier of the underlying
	// Example: 13.37
	// Read Only: true
	Multiplier string `json:"multiplier,omitempty"`

	// nominal rate
	// Example: 99.999
	// Read Only: true
	NominalRate string `json:"nominalRate,omitempty"`

	// rating
	// Read Only: true
	Rating *Rating `json:"rating,omitempty"`

	// remaining Term (expiryDate-today)
	// Example: 13.37
	// Read Only: true
	RemainingTermInYears string `json:"remainingTermInYears,omitempty"`

	// strike price of the underlying
	// Read Only: true
	StrikePrice *AmountValue `json:"strikePrice,omitempty"`

	// the underlying instrument
	// Read Only: true
	UnderlyingInstrument *Instrument `json:"underlyingInstrument,omitempty"`

	// Price of the underlying
	// Read Only: true
	UnderlyingPrice *Price `json:"underlyingPrice,omitempty"`

	// Warrant Type
	// Read Only: true
	// Enum: ["Call","Put"]
	WarrantType string `json:"warrantType,omitempty"`

	// yield p.a.
	// Example: 99.999
	// Read Only: true
	YieldPA string `json:"yieldPA,omitempty"`
}

// Validate validates this derivative data
func (m *DerivativeData) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCertificateType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateInterestPaymentInterval(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRating(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStrikePrice(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUnderlyingInstrument(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUnderlyingPrice(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateWarrantType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var derivativeDataTypeCertificateTypePropEnum []any

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["Hebel","Index","Basket","Hedge-Fonds-Zertifikat","Discount","Aktienanleihe","Bandbreite","Outperformance","Express","Bonus","Kapitalschutz"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		derivativeDataTypeCertificateTypePropEnum = append(derivativeDataTypeCertificateTypePropEnum, v)
	}
}

const (

	// DerivativeDataCertificateTypeHebel captures enum value "Hebel"
	DerivativeDataCertificateTypeHebel string = "Hebel"

	// DerivativeDataCertificateTypeIndex captures enum value "Index"
	DerivativeDataCertificateTypeIndex string = "Index"

	// DerivativeDataCertificateTypeBasket captures enum value "Basket"
	DerivativeDataCertificateTypeBasket string = "Basket"

	// DerivativeDataCertificateTypeHedgeDashFondsDashZertifikat captures enum value "Hedge-Fonds-Zertifikat"
	DerivativeDataCertificateTypeHedgeDashFondsDashZertifikat string = "Hedge-Fonds-Zertifikat"

	// DerivativeDataCertificateTypeDiscount captures enum value "Discount"
	DerivativeDataCertificateTypeDiscount string = "Discount"

	// DerivativeDataCertificateTypeAktienanleihe captures enum value "Aktienanleihe"
	DerivativeDataCertificateTypeAktienanleihe string = "Aktienanleihe"

	// DerivativeDataCertificateTypeBandbreite captures enum value "Bandbreite"
	DerivativeDataCertificateTypeBandbreite string = "Bandbreite"

	// DerivativeDataCertificateTypeOutperformance captures enum value "Outperformance"
	DerivativeDataCertificateTypeOutperformance string = "Outperformance"

	// DerivativeDataCertificateTypeExpress captures enum value "Express"
	DerivativeDataCertificateTypeExpress string = "Express"

	// DerivativeDataCertificateTypeBonus captures enum value "Bonus"
	DerivativeDataCertificateTypeBonus string = "Bonus"

	// DerivativeDataCertificateTypeKapitalschutz captures enum value "Kapitalschutz"
	DerivativeDataCertificateTypeKapitalschutz string = "Kapitalschutz"
)

// prop value enum
func (m *DerivativeData) validateCertificateTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, derivativeDataTypeCertificateTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *DerivativeData) validateCertificateType(formats strfmt.Registry) error {
	if typeutils.IsZero(m.CertificateType) { // not required
		return nil
	}

	// value enum
	if err := m.validateCertificateTypeEnum("certificateType", "body", m.CertificateType); err != nil {
		return err
	}

	return nil
}

var derivativeDataTypeInterestPaymentIntervalPropEnum []any

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["MONTHLY","QUARTERLY","SEMIANNUALLY","ANNUALLY","OTHER"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		derivativeDataTypeInterestPaymentIntervalPropEnum = append(derivativeDataTypeInterestPaymentIntervalPropEnum, v)
	}
}

const (

	// DerivativeDataInterestPaymentIntervalMONTHLY captures enum value "MONTHLY"
	DerivativeDataInterestPaymentIntervalMONTHLY string = "MONTHLY"

	// DerivativeDataInterestPaymentIntervalQUARTERLY captures enum value "QUARTERLY"
	DerivativeDataInterestPaymentIntervalQUARTERLY string = "QUARTERLY"

	// DerivativeDataInterestPaymentIntervalSEMIANNUALLY captures enum value "SEMIANNUALLY"
	DerivativeDataInterestPaymentIntervalSEMIANNUALLY string = "SEMIANNUALLY"

	// DerivativeDataInterestPaymentIntervalANNUALLY captures enum value "ANNUALLY"
	DerivativeDataInterestPaymentIntervalANNUALLY string = "ANNUALLY"

	// DerivativeDataInterestPaymentIntervalOTHER captures enum value "OTHER"
	DerivativeDataInterestPaymentIntervalOTHER string = "OTHER"
)

// prop value enum
func (m *DerivativeData) validateInterestPaymentIntervalEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, derivativeDataTypeInterestPaymentIntervalPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *DerivativeData) validateInterestPaymentInterval(formats strfmt.Registry) error {
	if typeutils.IsZero(m.InterestPaymentInterval) { // not required
		return nil
	}

	// value enum
	if err := m.validateInterestPaymentIntervalEnum("interestPaymentInterval", "body", m.InterestPaymentInterval); err != nil {
		return err
	}

	return nil
}

func (m *DerivativeData) validateRating(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Rating) { // not required
		return nil
	}

	if m.Rating != nil {
		if err := m.Rating.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("rating")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("rating")
			}

			return err
		}
	}

	return nil
}

func (m *DerivativeData) validateStrikePrice(formats strfmt.Registry) error {
	if typeutils.IsZero(m.StrikePrice) { // not required
		return nil
	}

	if m.StrikePrice != nil {
		if err := m.StrikePrice.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("strikePrice")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("strikePrice")
			}

			return err
		}
	}

	return nil
}

func (m *DerivativeData) validateUnderlyingInstrument(formats strfmt.Registry) error {
	if typeutils.IsZero(m.UnderlyingInstrument) { // not required
		return nil
	}

	if m.UnderlyingInstrument != nil {
		if err := m.UnderlyingInstrument.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("underlyingInstrument")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("underlyingInstrument")
			}

			return err
		}
	}

	return nil
}

func (m *DerivativeData) validateUnderlyingPrice(formats strfmt.Registry) error {
	if typeutils.IsZero(m.UnderlyingPrice) { // not required
		return nil
	}

	if m.UnderlyingPrice != nil {
		if err := m.UnderlyingPrice.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("underlyingPrice")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("underlyingPrice")
			}

			return err
		}
	}

	return nil
}

var derivativeDataTypeWarrantTypePropEnum []any

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["Call","Put"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		derivativeDataTypeWarrantTypePropEnum = append(derivativeDataTypeWarrantTypePropEnum, v)
	}
}

const (

	// DerivativeDataWarrantTypeCall captures enum value "Call"
	DerivativeDataWarrantTypeCall string = "Call"

	// DerivativeDataWarrantTypePut captures enum value "Put"
	DerivativeDataWarrantTypePut string = "Put"
)

// prop value enum
func (m *DerivativeData) validateWarrantTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, derivativeDataTypeWarrantTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *DerivativeData) validateWarrantType(formats strfmt.Registry) error {
	if typeutils.IsZero(m.WarrantType) { // not required
		return nil
	}

	// value enum
	if err := m.validateWarrantTypeEnum("warrantType", "body", m.WarrantType); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this derivative data based on the context it is used
func (m *DerivativeData) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateCertificateType(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateExpiryDate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateInterestPaymentDate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateInterestPaymentInterval(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateLeverage(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateMaturityDate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateMultiplier(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateNominalRate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateRating(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateRemainingTermInYears(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateStrikePrice(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateUnderlyingInstrument(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateUnderlyingPrice(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateWarrantType(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateYieldPA(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DerivativeData) contextValidateCertificateType(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "certificateType", "body", m.CertificateType); err != nil {
		return err
	}

	return nil
}

func (m *DerivativeData) contextValidateExpiryDate(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "expiryDate", "body", m.ExpiryDate); err != nil {
		return err
	}

	return nil
}

func (m *DerivativeData) contextValidateInterestPaymentDate(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "interestPaymentDate", "body", m.InterestPaymentDate); err != nil {
		return err
	}

	return nil
}

func (m *DerivativeData) contextValidateInterestPaymentInterval(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "interestPaymentInterval", "body", m.InterestPaymentInterval); err != nil {
		return err
	}

	return nil
}

func (m *DerivativeData) contextValidateLeverage(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "leverage", "body", m.Leverage); err != nil {
		return err
	}

	return nil
}

func (m *DerivativeData) contextValidateMaturityDate(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "maturityDate", "body", m.MaturityDate); err != nil {
		return err
	}

	return nil
}

func (m *DerivativeData) contextValidateMultiplier(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "multiplier", "body", m.Multiplier); err != nil {
		return err
	}

	return nil
}

func (m *DerivativeData) contextValidateNominalRate(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "nominalRate", "body", m.NominalRate); err != nil {
		return err
	}

	return nil
}

func (m *DerivativeData) contextValidateRating(ctx context.Context, formats strfmt.Registry) error {

	if m.Rating != nil {

		if typeutils.IsZero(m.Rating) { // not required
			return nil
		}

		if err := m.Rating.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("rating")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("rating")
			}

			return err
		}
	}

	return nil
}

func (m *DerivativeData) contextValidateRemainingTermInYears(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "remainingTermInYears", "body", m.RemainingTermInYears); err != nil {
		return err
	}

	return nil
}

func (m *DerivativeData) contextValidateStrikePrice(ctx context.Context, formats strfmt.Registry) error {

	if m.StrikePrice != nil {

		if typeutils.IsZero(m.StrikePrice) { // not required
			return nil
		}

		if err := m.StrikePrice.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("strikePrice")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("strikePrice")
			}

			return err
		}
	}

	return nil
}

func (m *DerivativeData) contextValidateUnderlyingInstrument(ctx context.Context, formats strfmt.Registry) error {

	if m.UnderlyingInstrument != nil {

		if typeutils.IsZero(m.UnderlyingInstrument) { // not required
			return nil
		}

		if err := m.UnderlyingInstrument.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("underlyingInstrument")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("underlyingInstrument")
			}

			return err
		}
	}

	return nil
}

func (m *DerivativeData) contextValidateUnderlyingPrice(ctx context.Context, formats strfmt.Registry) error {

	if m.UnderlyingPrice != nil {

		if typeutils.IsZero(m.UnderlyingPrice) { // not required
			return nil
		}

		if err := m.UnderlyingPrice.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("underlyingPrice")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("underlyingPrice")
			}

			return err
		}
	}

	return nil
}

func (m *DerivativeData) contextValidateWarrantType(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "warrantType", "body", m.WarrantType); err != nil {
		return err
	}

	return nil
}

func (m *DerivativeData) contextValidateYieldPA(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "yieldPA", "body", m.YieldPA); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *DerivativeData) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DerivativeData) UnmarshalBinary(b []byte) error {
	var res DerivativeData
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
