// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	stderrors "errors"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
)

// Dimensions Model for dimensions.
//
// swagger:model Dimensions
type Dimensions struct {

	// venues
	Venues []*Venue `json:"venues"`
}

// Validate validates this dimensions
func (m *Dimensions) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateVenues(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Dimensions) validateVenues(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Venues) { // not required
		return nil
	}

	for i := 0; i < len(m.Venues); i++ {
		if typeutils.IsZero(m.Venues[i]) { // not required
			continue
		}

		if m.Venues[i] != nil {
			if err := m.Venues[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("venues" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("venues" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this dimensions based on the context it is used
func (m *Dimensions) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateVenues(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Dimensions) contextValidateVenues(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Venues); i++ {

		if m.Venues[i] != nil {

			if typeutils.IsZero(m.Venues[i]) { // not required
				return nil
			}

			if err := m.Venues[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("venues" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("venues" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *Dimensions) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Dimensions) UnmarshalBinary(b []byte) error {
	var res Dimensions
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
