// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/validate"
)

// DocumentMetadata Model for category-specific metadata of documents.
//
// swagger:model DocumentMetadata
type DocumentMetadata struct {

	// Has the document been read?
	// Read Only: true
	AlreadyRead *bool `json:"alreadyRead,omitempty"`

	// Is document archived?
	// Read Only: true
	Archived *bool `json:"archived,omitempty"`

	// Date on which the document was read.
	// Example: 2019-03-14
	// Read Only: true
	DateRead string `json:"dateRead,omitempty"`

	// predocument exists
	PredocumentExists *bool `json:"predocumentExists,omitempty"`
}

// Validate validates this document metadata
func (m *DocumentMetadata) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validate this document metadata based on the context it is used
func (m *DocumentMetadata) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAlreadyRead(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateArchived(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateDateRead(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DocumentMetadata) contextValidateAlreadyRead(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "alreadyRead", "body", m.AlreadyRead); err != nil {
		return err
	}

	return nil
}

func (m *DocumentMetadata) contextValidateArchived(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "archived", "body", m.Archived); err != nil {
		return err
	}

	return nil
}

func (m *DocumentMetadata) contextValidateDateRead(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "dateRead", "body", m.DateRead); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *DocumentMetadata) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DocumentMetadata) UnmarshalBinary(b []byte) error {
	var res DocumentMetadata
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
