// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
	"github.com/go-openapi/validate"
)

// EnumText Holds a unique key and the corresponding text.
//
// swagger:model EnumText
type EnumText struct {

	// Unique key value for an enumeration type.
	// Read Only: true
	// Max Length: 40
	// Min Length: 1
	Key string `json:"key,omitempty"`

	// Display text in German language.
	// Read Only: true
	// Max Length: 65
	// Min Length: 0
	Text string `json:"text,omitempty"`
}

// Validate validates this enum text
func (m *EnumText) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateKey(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateText(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *EnumText) validateKey(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Key) { // not required
		return nil
	}

	if err := validate.MinLength("key", "body", m.Key, 1); err != nil {
		return err
	}

	if err := validate.MaxLength("key", "body", m.Key, 40); err != nil {
		return err
	}

	return nil
}

func (m *EnumText) validateText(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Text) { // not required
		return nil
	}

	if err := validate.MinLength("text", "body", m.Text, 0); err != nil {
		return err
	}

	if err := validate.MaxLength("text", "body", m.Text, 65); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this enum text based on the context it is used
func (m *EnumText) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateKey(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateText(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *EnumText) contextValidateKey(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "key", "body", m.Key); err != nil {
		return err
	}

	return nil
}

func (m *EnumText) contextValidateText(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "text", "body", m.Text); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *EnumText) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EnumText) UnmarshalBinary(b []byte) error {
	var res EnumText
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
