// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
	"github.com/go-openapi/validate"
)

// Execution Model for an order's execution.
//
// swagger:model Execution
type Execution struct {

	// Quantity of executed units or nominal amount
	// Read Only: true
	ExecutedQuantity *AmountValue `json:"executedQuantity,omitempty"`

	// Execution ID (UUID)
	// Read Only: true
	// Max Length: 40
	// Min Length: 0
	ExecutionID string `json:"executionId,omitempty"`

	// Position (by time) of the execution of an order
	// Read Only: true
	ExecutionNumber int32 `json:"executionNumber,omitempty"`

	// Execution price
	// Read Only: true
	ExecutionPrice *AmountValue `json:"executionPrice,omitempty"`

	// Date/timestamp of the order entry in UTC in the following format: (MiFID II) YYYY-MM-DDThh:mm:ss,ffffff+zz
	// Read Only: true
	ExecutionTimestamp *TimestampString `json:"executionTimestamp,omitempty"`
}

// Validate validates this execution
func (m *Execution) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateExecutedQuantity(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateExecutionID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateExecutionPrice(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateExecutionTimestamp(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Execution) validateExecutedQuantity(formats strfmt.Registry) error {
	if typeutils.IsZero(m.ExecutedQuantity) { // not required
		return nil
	}

	if m.ExecutedQuantity != nil {
		if err := m.ExecutedQuantity.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("executedQuantity")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("executedQuantity")
			}

			return err
		}
	}

	return nil
}

func (m *Execution) validateExecutionID(formats strfmt.Registry) error {
	if typeutils.IsZero(m.ExecutionID) { // not required
		return nil
	}

	if err := validate.MinLength("executionId", "body", m.ExecutionID, 0); err != nil {
		return err
	}

	if err := validate.MaxLength("executionId", "body", m.ExecutionID, 40); err != nil {
		return err
	}

	return nil
}

func (m *Execution) validateExecutionPrice(formats strfmt.Registry) error {
	if typeutils.IsZero(m.ExecutionPrice) { // not required
		return nil
	}

	if m.ExecutionPrice != nil {
		if err := m.ExecutionPrice.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("executionPrice")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("executionPrice")
			}

			return err
		}
	}

	return nil
}

func (m *Execution) validateExecutionTimestamp(formats strfmt.Registry) error {
	if typeutils.IsZero(m.ExecutionTimestamp) { // not required
		return nil
	}

	if m.ExecutionTimestamp != nil {
		if err := m.ExecutionTimestamp.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("executionTimestamp")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("executionTimestamp")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this execution based on the context it is used
func (m *Execution) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateExecutedQuantity(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateExecutionID(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateExecutionNumber(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateExecutionPrice(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateExecutionTimestamp(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Execution) contextValidateExecutedQuantity(ctx context.Context, formats strfmt.Registry) error {

	if m.ExecutedQuantity != nil {

		if typeutils.IsZero(m.ExecutedQuantity) { // not required
			return nil
		}

		if err := m.ExecutedQuantity.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("executedQuantity")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("executedQuantity")
			}

			return err
		}
	}

	return nil
}

func (m *Execution) contextValidateExecutionID(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "executionId", "body", m.ExecutionID); err != nil {
		return err
	}

	return nil
}

func (m *Execution) contextValidateExecutionNumber(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "executionNumber", "body", m.ExecutionNumber); err != nil {
		return err
	}

	return nil
}

func (m *Execution) contextValidateExecutionPrice(ctx context.Context, formats strfmt.Registry) error {

	if m.ExecutionPrice != nil {

		if typeutils.IsZero(m.ExecutionPrice) { // not required
			return nil
		}

		if err := m.ExecutionPrice.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("executionPrice")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("executionPrice")
			}

			return err
		}
	}

	return nil
}

func (m *Execution) contextValidateExecutionTimestamp(ctx context.Context, formats strfmt.Registry) error {

	if m.ExecutionTimestamp != nil {

		if typeutils.IsZero(m.ExecutionTimestamp) { // not required
			return nil
		}

		if err := m.ExecutionTimestamp.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("executionTimestamp")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("executionTimestamp")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Execution) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Execution) UnmarshalBinary(b []byte) error {
	var res Execution
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
