// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
)

// FXRateEUR Exchange rate for settlement currency to FX.
//
// swagger:model FXRateEUR
type FXRateEUR struct {

	// Ask rate of settlement currency to FX
	// Example: 1,1757 USD (1 EUR)
	// Read Only: true
	Ask *AmountValue `json:"ask,omitempty"`

	// Bid rate of settlement currency to FX
	// Example: 1,1752 USD (1 EUR)
	// Read Only: true
	Bid *AmountValue `json:"bid,omitempty"`
}

// Validate validates this f x rate e u r
func (m *FXRateEUR) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAsk(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateBid(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *FXRateEUR) validateAsk(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Ask) { // not required
		return nil
	}

	if m.Ask != nil {
		if err := m.Ask.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("ask")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("ask")
			}

			return err
		}
	}

	return nil
}

func (m *FXRateEUR) validateBid(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Bid) { // not required
		return nil
	}

	if m.Bid != nil {
		if err := m.Bid.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("bid")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("bid")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this f x rate e u r based on the context it is used
func (m *FXRateEUR) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAsk(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateBid(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *FXRateEUR) contextValidateAsk(ctx context.Context, formats strfmt.Registry) error {

	if m.Ask != nil {

		if typeutils.IsZero(m.Ask) { // not required
			return nil
		}

		if err := m.Ask.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("ask")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("ask")
			}

			return err
		}
	}

	return nil
}

func (m *FXRateEUR) contextValidateBid(ctx context.Context, formats strfmt.Registry) error {

	if m.Bid != nil {

		if typeutils.IsZero(m.Bid) { // not required
			return nil
		}

		if err := m.Bid.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("bid")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("bid")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *FXRateEUR) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *FXRateEUR) UnmarshalBinary(b []byte) error {
	var res FXRateEUR
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
