// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	"encoding/json"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
	"github.com/go-openapi/validate"
)

// FixedTermSavings fixed term savings
//
// swagger:model FixedTermSavings
type FixedTermSavings struct {

	// Contract period of the deposit account in months.
	// Example: 120
	// Read Only: true
	ContractPeriodInMonths int32 `json:"contractPeriodInMonths,omitempty"`

	// Start date of investment.
	// Example: 2019-03-14
	// Read Only: true
	CreationDate string `json:"creationDate,omitempty"`

	// End date of investment.
	// Example: 2019-03-14
	// Read Only: true
	ExpirationDate string `json:"expirationDate,omitempty"`

	// Indicates whether the investment can be extended.
	// Example: true
	// Read Only: true
	Extendable *bool `json:"extendable,omitempty"`

	// Name of the deposit account.
	// Example: Laufzeitkonto
	// Read Only: true
	FixedTermSavingsDisplayName string `json:"fixedTermSavingsDisplayName,omitempty"`

	// UUID of the deposit account.
	// Example: 0123456789ABCDEF0123456789ABCDEF
	// Read Only: true
	FixedTermSavingsID string `json:"fixedTermSavingsId,omitempty"`

	// Type of the deposit account.
	// Read Only: true
	// Enum: ["SHORT_TERM","LONG_TERM"]
	FixedTermSavingsType string `json:"fixedTermSavingsType,omitempty"`

	// Interest rate of the deposit account.
	// Example: 99.999
	// Read Only: true
	InterestRate string `json:"interestRate,omitempty"`

	// Amount of money for prolongation.
	// Read Only: true
	ProlongationAmount *AmountValue `json:"prolongationAmount,omitempty"`

	// Total of investment.
	// Read Only: true
	SavingsAmount *AmountValue `json:"savingsAmount,omitempty"`
}

// Validate validates this fixed term savings
func (m *FixedTermSavings) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFixedTermSavingsType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProlongationAmount(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSavingsAmount(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var fixedTermSavingsTypeFixedTermSavingsTypePropEnum []any

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["SHORT_TERM","LONG_TERM"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		fixedTermSavingsTypeFixedTermSavingsTypePropEnum = append(fixedTermSavingsTypeFixedTermSavingsTypePropEnum, v)
	}
}

const (

	// FixedTermSavingsFixedTermSavingsTypeSHORTTERM captures enum value "SHORT_TERM"
	FixedTermSavingsFixedTermSavingsTypeSHORTTERM string = "SHORT_TERM"

	// FixedTermSavingsFixedTermSavingsTypeLONGTERM captures enum value "LONG_TERM"
	FixedTermSavingsFixedTermSavingsTypeLONGTERM string = "LONG_TERM"
)

// prop value enum
func (m *FixedTermSavings) validateFixedTermSavingsTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, fixedTermSavingsTypeFixedTermSavingsTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *FixedTermSavings) validateFixedTermSavingsType(formats strfmt.Registry) error {
	if typeutils.IsZero(m.FixedTermSavingsType) { // not required
		return nil
	}

	// value enum
	if err := m.validateFixedTermSavingsTypeEnum("fixedTermSavingsType", "body", m.FixedTermSavingsType); err != nil {
		return err
	}

	return nil
}

func (m *FixedTermSavings) validateProlongationAmount(formats strfmt.Registry) error {
	if typeutils.IsZero(m.ProlongationAmount) { // not required
		return nil
	}

	if m.ProlongationAmount != nil {
		if err := m.ProlongationAmount.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("prolongationAmount")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("prolongationAmount")
			}

			return err
		}
	}

	return nil
}

func (m *FixedTermSavings) validateSavingsAmount(formats strfmt.Registry) error {
	if typeutils.IsZero(m.SavingsAmount) { // not required
		return nil
	}

	if m.SavingsAmount != nil {
		if err := m.SavingsAmount.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("savingsAmount")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("savingsAmount")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this fixed term savings based on the context it is used
func (m *FixedTermSavings) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateContractPeriodInMonths(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateCreationDate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateExpirationDate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateExtendable(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateFixedTermSavingsDisplayName(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateFixedTermSavingsID(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateFixedTermSavingsType(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateInterestRate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateProlongationAmount(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateSavingsAmount(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *FixedTermSavings) contextValidateContractPeriodInMonths(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "contractPeriodInMonths", "body", m.ContractPeriodInMonths); err != nil {
		return err
	}

	return nil
}

func (m *FixedTermSavings) contextValidateCreationDate(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "creationDate", "body", m.CreationDate); err != nil {
		return err
	}

	return nil
}

func (m *FixedTermSavings) contextValidateExpirationDate(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "expirationDate", "body", m.ExpirationDate); err != nil {
		return err
	}

	return nil
}

func (m *FixedTermSavings) contextValidateExtendable(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "extendable", "body", m.Extendable); err != nil {
		return err
	}

	return nil
}

func (m *FixedTermSavings) contextValidateFixedTermSavingsDisplayName(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "fixedTermSavingsDisplayName", "body", m.FixedTermSavingsDisplayName); err != nil {
		return err
	}

	return nil
}

func (m *FixedTermSavings) contextValidateFixedTermSavingsID(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "fixedTermSavingsId", "body", m.FixedTermSavingsID); err != nil {
		return err
	}

	return nil
}

func (m *FixedTermSavings) contextValidateFixedTermSavingsType(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "fixedTermSavingsType", "body", m.FixedTermSavingsType); err != nil {
		return err
	}

	return nil
}

func (m *FixedTermSavings) contextValidateInterestRate(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "interestRate", "body", m.InterestRate); err != nil {
		return err
	}

	return nil
}

func (m *FixedTermSavings) contextValidateProlongationAmount(ctx context.Context, formats strfmt.Registry) error {

	if m.ProlongationAmount != nil {

		if typeutils.IsZero(m.ProlongationAmount) { // not required
			return nil
		}

		if err := m.ProlongationAmount.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("prolongationAmount")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("prolongationAmount")
			}

			return err
		}
	}

	return nil
}

func (m *FixedTermSavings) contextValidateSavingsAmount(ctx context.Context, formats strfmt.Registry) error {

	if m.SavingsAmount != nil {

		if typeutils.IsZero(m.SavingsAmount) { // not required
			return nil
		}

		if err := m.SavingsAmount.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("savingsAmount")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("savingsAmount")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *FixedTermSavings) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *FixedTermSavings) UnmarshalBinary(b []byte) error {
	var res FixedTermSavings
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
