// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	"encoding/json"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
	"github.com/go-openapi/validate"
)

// FundDistribution additional fund data, if the instrument is a fund
//
// swagger:model FundDistribution
type FundDistribution struct {

	// Bonification
	// Example: 99.999
	// Read Only: true
	Bonification string `json:"bonification,omitempty"`

	// currency of fund
	// Example: EUR
	// Read Only: true
	Currency string `json:"currency,omitempty"`

	// Discount issue surcharge
	// Example: 99.999
	// Read Only: true
	DiscountIssueSurcharge string `json:"discountIssueSurcharge,omitempty"`

	// List of different features of funds
	// Read Only: true
	FundFlags []string `json:"fundFlags"`

	// Status of fund
	// Read Only: true
	// Enum: ["A","K","P","R","V","N","L","D","F","I","M"]
	FundStatus string `json:"fundStatus,omitempty"`

	// Individual issue surcharge
	// Example: 99.999
	// Read Only: true
	IndividualIssueSurcharge string `json:"individualIssueSurcharge,omitempty"`

	// Investment category
	// Read Only: true
	InvestmentCategory string `json:"investmentCategory,omitempty"`

	// Is individual issue surcharge corrected
	// Read Only: true
	IsIndividualIssueSurchargeCorrected *bool `json:"isIndividualIssueSurchargeCorrected,omitempty"`

	// Rating
	// Read Only: true
	Rating *Rating `json:"rating,omitempty"`

	// Reduced issue surcharge
	// Example: 99.999
	// Read Only: true
	ReducedIssueSurcharge string `json:"reducedIssueSurcharge,omitempty"`

	// Regular issue surcharge
	// Example: 99.999
	// Read Only: true
	RegularIssueSurcharge string `json:"regularIssueSurcharge,omitempty"`

	// Total expense ratio
	// Example: 99.999
	// Read Only: true
	TotalExpenseRatio string `json:"totalExpenseRatio,omitempty"`
}

// Validate validates this fund distribution
func (m *FundDistribution) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFundStatus(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRating(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var fundDistributionTypeFundStatusPropEnum []any

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["A","K","P","R","V","N","L","D","F","I","M"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		fundDistributionTypeFundStatusPropEnum = append(fundDistributionTypeFundStatusPropEnum, v)
	}
}

const (

	// FundDistributionFundStatusA captures enum value "A"
	FundDistributionFundStatusA string = "A"

	// FundDistributionFundStatusK captures enum value "K"
	FundDistributionFundStatusK string = "K"

	// FundDistributionFundStatusP captures enum value "P"
	FundDistributionFundStatusP string = "P"

	// FundDistributionFundStatusR captures enum value "R"
	FundDistributionFundStatusR string = "R"

	// FundDistributionFundStatusV captures enum value "V"
	FundDistributionFundStatusV string = "V"

	// FundDistributionFundStatusN captures enum value "N"
	FundDistributionFundStatusN string = "N"

	// FundDistributionFundStatusL captures enum value "L"
	FundDistributionFundStatusL string = "L"

	// FundDistributionFundStatusD captures enum value "D"
	FundDistributionFundStatusD string = "D"

	// FundDistributionFundStatusF captures enum value "F"
	FundDistributionFundStatusF string = "F"

	// FundDistributionFundStatusI captures enum value "I"
	FundDistributionFundStatusI string = "I"

	// FundDistributionFundStatusM captures enum value "M"
	FundDistributionFundStatusM string = "M"
)

// prop value enum
func (m *FundDistribution) validateFundStatusEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, fundDistributionTypeFundStatusPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *FundDistribution) validateFundStatus(formats strfmt.Registry) error {
	if typeutils.IsZero(m.FundStatus) { // not required
		return nil
	}

	// value enum
	if err := m.validateFundStatusEnum("fundStatus", "body", m.FundStatus); err != nil {
		return err
	}

	return nil
}

func (m *FundDistribution) validateRating(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Rating) { // not required
		return nil
	}

	if m.Rating != nil {
		if err := m.Rating.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("rating")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("rating")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this fund distribution based on the context it is used
func (m *FundDistribution) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateBonification(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateCurrency(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateDiscountIssueSurcharge(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateFundFlags(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateFundStatus(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateIndividualIssueSurcharge(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateInvestmentCategory(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateIsIndividualIssueSurchargeCorrected(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateRating(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateReducedIssueSurcharge(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateRegularIssueSurcharge(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateTotalExpenseRatio(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *FundDistribution) contextValidateBonification(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "bonification", "body", m.Bonification); err != nil {
		return err
	}

	return nil
}

func (m *FundDistribution) contextValidateCurrency(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "currency", "body", m.Currency); err != nil {
		return err
	}

	return nil
}

func (m *FundDistribution) contextValidateDiscountIssueSurcharge(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "discountIssueSurcharge", "body", m.DiscountIssueSurcharge); err != nil {
		return err
	}

	return nil
}

func (m *FundDistribution) contextValidateFundFlags(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "fundFlags", "body", m.FundFlags); err != nil {
		return err
	}

	return nil
}

func (m *FundDistribution) contextValidateFundStatus(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "fundStatus", "body", m.FundStatus); err != nil {
		return err
	}

	return nil
}

func (m *FundDistribution) contextValidateIndividualIssueSurcharge(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "individualIssueSurcharge", "body", m.IndividualIssueSurcharge); err != nil {
		return err
	}

	return nil
}

func (m *FundDistribution) contextValidateInvestmentCategory(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "investmentCategory", "body", m.InvestmentCategory); err != nil {
		return err
	}

	return nil
}

func (m *FundDistribution) contextValidateIsIndividualIssueSurchargeCorrected(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "isIndividualIssueSurchargeCorrected", "body", m.IsIndividualIssueSurchargeCorrected); err != nil {
		return err
	}

	return nil
}

func (m *FundDistribution) contextValidateRating(ctx context.Context, formats strfmt.Registry) error {

	if m.Rating != nil {

		if typeutils.IsZero(m.Rating) { // not required
			return nil
		}

		if err := m.Rating.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("rating")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("rating")
			}

			return err
		}
	}

	return nil
}

func (m *FundDistribution) contextValidateReducedIssueSurcharge(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "reducedIssueSurcharge", "body", m.ReducedIssueSurcharge); err != nil {
		return err
	}

	return nil
}

func (m *FundDistribution) contextValidateRegularIssueSurcharge(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "regularIssueSurcharge", "body", m.RegularIssueSurcharge); err != nil {
		return err
	}

	return nil
}

func (m *FundDistribution) contextValidateTotalExpenseRatio(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "totalExpenseRatio", "body", m.TotalExpenseRatio); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *FundDistribution) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *FundDistribution) UnmarshalBinary(b []byte) error {
	var res FundDistribution
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
