// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
	"github.com/go-openapi/validate"
)

// InstallmentLoanBalance Balance and master data of an installment loan
//
// swagger:model InstallmentLoanBalance
type InstallmentLoanBalance struct {

	// Current balance of the installment loan in EUR, including residual debt insurance and interest.
	// Read Only: true
	Balance *AmountValue `json:"balance,omitempty"`

	// Master data of the installment loan.
	// Read Only: true
	InstallmentLoan *InstallmentLoan `json:"installmentLoan,omitempty"`

	// Installment loan identifier (UUID).
	// Example: 0123456789ABCDEF0123456789ABCDEF
	// Read Only: true
	InstallmentLoanID string `json:"installmentLoanId,omitempty"`
}

// Validate validates this installment loan balance
func (m *InstallmentLoanBalance) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBalance(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateInstallmentLoan(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *InstallmentLoanBalance) validateBalance(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Balance) { // not required
		return nil
	}

	if m.Balance != nil {
		if err := m.Balance.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("balance")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("balance")
			}

			return err
		}
	}

	return nil
}

func (m *InstallmentLoanBalance) validateInstallmentLoan(formats strfmt.Registry) error {
	if typeutils.IsZero(m.InstallmentLoan) { // not required
		return nil
	}

	if m.InstallmentLoan != nil {
		if err := m.InstallmentLoan.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("installmentLoan")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("installmentLoan")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this installment loan balance based on the context it is used
func (m *InstallmentLoanBalance) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateBalance(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateInstallmentLoan(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateInstallmentLoanID(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *InstallmentLoanBalance) contextValidateBalance(ctx context.Context, formats strfmt.Registry) error {

	if m.Balance != nil {

		if typeutils.IsZero(m.Balance) { // not required
			return nil
		}

		if err := m.Balance.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("balance")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("balance")
			}

			return err
		}
	}

	return nil
}

func (m *InstallmentLoanBalance) contextValidateInstallmentLoan(ctx context.Context, formats strfmt.Registry) error {

	if m.InstallmentLoan != nil {

		if typeutils.IsZero(m.InstallmentLoan) { // not required
			return nil
		}

		if err := m.InstallmentLoan.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("installmentLoan")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("installmentLoan")
			}

			return err
		}
	}

	return nil
}

func (m *InstallmentLoanBalance) contextValidateInstallmentLoanID(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "installmentLoanId", "body", m.InstallmentLoanID); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *InstallmentLoanBalance) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InstallmentLoanBalance) UnmarshalBinary(b []byte) error {
	var res InstallmentLoanBalance
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
