// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
	"github.com/go-openapi/validate"
)

// Instrument Model for an instrument.
//
// swagger:model Instrument
type Instrument struct {

	// additional data of a derivative
	// Read Only: true
	DerivativeData *DerivativeData `json:"derivativeData,omitempty"`

	// additional fund data, if the instrument is a fund
	// Read Only: true
	FundsDistribution *FundDistribution `json:"fundsDistribution,omitempty"`

	// Instrument id (UUID), unique identification of an instrument (security, derivative, etc.) for future use
	// Read Only: true
	InstrumentID string `json:"instrumentId,omitempty"`

	// ISIN
	// Read Only: true
	Isin string `json:"isin,omitempty"`

	// Security symbol according to WM data-service
	// Read Only: true
	Mnemonic string `json:"mnemonic,omitempty"`

	// Name of the instrument
	// Read Only: true
	Name string `json:"name,omitempty"`

	// List of the trading venues including the attributes (orderDimensions)
	// Read Only: true
	OrderDimensions *Dimensions `json:"orderDimensions,omitempty"`

	// Short name of the instrument
	// Read Only: true
	ShortName string `json:"shortName,omitempty"`

	// Static data of the instrument, e.g., notation, instrument type
	// Read Only: true
	StaticData *StaticData `json:"staticData,omitempty"`

	// WKN
	// Read Only: true
	Wkn string `json:"wkn,omitempty"`
}

// Validate validates this instrument
func (m *Instrument) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDerivativeData(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateFundsDistribution(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOrderDimensions(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStaticData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Instrument) validateDerivativeData(formats strfmt.Registry) error {
	if typeutils.IsZero(m.DerivativeData) { // not required
		return nil
	}

	if m.DerivativeData != nil {
		if err := m.DerivativeData.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("derivativeData")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("derivativeData")
			}

			return err
		}
	}

	return nil
}

func (m *Instrument) validateFundsDistribution(formats strfmt.Registry) error {
	if typeutils.IsZero(m.FundsDistribution) { // not required
		return nil
	}

	if m.FundsDistribution != nil {
		if err := m.FundsDistribution.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("fundsDistribution")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("fundsDistribution")
			}

			return err
		}
	}

	return nil
}

func (m *Instrument) validateOrderDimensions(formats strfmt.Registry) error {
	if typeutils.IsZero(m.OrderDimensions) { // not required
		return nil
	}

	if m.OrderDimensions != nil {
		if err := m.OrderDimensions.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("orderDimensions")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("orderDimensions")
			}

			return err
		}
	}

	return nil
}

func (m *Instrument) validateStaticData(formats strfmt.Registry) error {
	if typeutils.IsZero(m.StaticData) { // not required
		return nil
	}

	if m.StaticData != nil {
		if err := m.StaticData.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("staticData")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("staticData")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this instrument based on the context it is used
func (m *Instrument) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateDerivativeData(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateFundsDistribution(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateInstrumentID(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateIsin(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateMnemonic(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateName(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateOrderDimensions(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateShortName(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateStaticData(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateWkn(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Instrument) contextValidateDerivativeData(ctx context.Context, formats strfmt.Registry) error {

	if m.DerivativeData != nil {

		if typeutils.IsZero(m.DerivativeData) { // not required
			return nil
		}

		if err := m.DerivativeData.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("derivativeData")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("derivativeData")
			}

			return err
		}
	}

	return nil
}

func (m *Instrument) contextValidateFundsDistribution(ctx context.Context, formats strfmt.Registry) error {

	if m.FundsDistribution != nil {

		if typeutils.IsZero(m.FundsDistribution) { // not required
			return nil
		}

		if err := m.FundsDistribution.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("fundsDistribution")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("fundsDistribution")
			}

			return err
		}
	}

	return nil
}

func (m *Instrument) contextValidateInstrumentID(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "instrumentId", "body", m.InstrumentID); err != nil {
		return err
	}

	return nil
}

func (m *Instrument) contextValidateIsin(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "isin", "body", m.Isin); err != nil {
		return err
	}

	return nil
}

func (m *Instrument) contextValidateMnemonic(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "mnemonic", "body", m.Mnemonic); err != nil {
		return err
	}

	return nil
}

func (m *Instrument) contextValidateName(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

func (m *Instrument) contextValidateOrderDimensions(ctx context.Context, formats strfmt.Registry) error {

	if m.OrderDimensions != nil {

		if typeutils.IsZero(m.OrderDimensions) { // not required
			return nil
		}

		if err := m.OrderDimensions.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("orderDimensions")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("orderDimensions")
			}

			return err
		}
	}

	return nil
}

func (m *Instrument) contextValidateShortName(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "shortName", "body", m.ShortName); err != nil {
		return err
	}

	return nil
}

func (m *Instrument) contextValidateStaticData(ctx context.Context, formats strfmt.Registry) error {

	if m.StaticData != nil {

		if typeutils.IsZero(m.StaticData) { // not required
			return nil
		}

		if err := m.StaticData.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("staticData")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("staticData")
			}

			return err
		}
	}

	return nil
}

func (m *Instrument) contextValidateWkn(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "wkn", "body", m.Wkn); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Instrument) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Instrument) UnmarshalBinary(b []byte) error {
	var res Instrument
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
