// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
	"github.com/go-openapi/validate"
)

// InstallmentLoan Master data of an installment loan
//
// swagger:model InstallmentLoan
type InstallmentLoan struct {

	// Date of conclusion of the installment loan.
	// Example: 2019-03-14
	// Read Only: true
	ContractConclusionDate string `json:"contractConclusionDate,omitempty"`

	// Runtime of the installment loan in months.
	// Example: 42
	// Read Only: true
	ContractPeriodInMonths int32 `json:"contractPeriodInMonths,omitempty"`

	// Approved loan amount of the initial conclusion of the loan in EUR, including residual debt insurance and interest.
	// Read Only: true
	CreditAmount *AmountValue `json:"creditAmount,omitempty"`

	// Effective interest rate.
	// Example: 99.999
	// Read Only: true
	EffectiveInterest string `json:"effectiveInterest,omitempty"`

	// Amount of the installment loan in EUR.
	// Read Only: true
	InstallmentAmount *AmountValue `json:"installmentAmount,omitempty"`

	// Installment loan identifier (UUID).
	// Example: 0123456789ABCDEF0123456789ABCDEF
	// Read Only: true
	InstallmentLoanID string `json:"installmentLoanId,omitempty"`

	// Approved loan amount of the initial conclusion of the loan in EUR, before residual debt insurance and interest.
	// Read Only: true
	NetCreditAmount *AmountValue `json:"netCreditAmount,omitempty"`

	// Nominal interest rate.
	// Example: 99.999
	// Read Only: true
	NominalInterest string `json:"nominalInterest,omitempty"`

	// Paid out amount of the approved loan, can include additions or deductions for residual debt insurance or interest.
	// Read Only: true
	PaidOutAmount *AmountValue `json:"paidOutAmount,omitempty"`

	// SWK number of the installment loan.
	// Example: 0123456789
	// Read Only: true
	ProductDisplayID string `json:"productDisplayId,omitempty"`
}

// Validate validates this installment loan
func (m *InstallmentLoan) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCreditAmount(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateInstallmentAmount(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateNetCreditAmount(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePaidOutAmount(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *InstallmentLoan) validateCreditAmount(formats strfmt.Registry) error {
	if typeutils.IsZero(m.CreditAmount) { // not required
		return nil
	}

	if m.CreditAmount != nil {
		if err := m.CreditAmount.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("creditAmount")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("creditAmount")
			}

			return err
		}
	}

	return nil
}

func (m *InstallmentLoan) validateInstallmentAmount(formats strfmt.Registry) error {
	if typeutils.IsZero(m.InstallmentAmount) { // not required
		return nil
	}

	if m.InstallmentAmount != nil {
		if err := m.InstallmentAmount.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("installmentAmount")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("installmentAmount")
			}

			return err
		}
	}

	return nil
}

func (m *InstallmentLoan) validateNetCreditAmount(formats strfmt.Registry) error {
	if typeutils.IsZero(m.NetCreditAmount) { // not required
		return nil
	}

	if m.NetCreditAmount != nil {
		if err := m.NetCreditAmount.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("netCreditAmount")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("netCreditAmount")
			}

			return err
		}
	}

	return nil
}

func (m *InstallmentLoan) validatePaidOutAmount(formats strfmt.Registry) error {
	if typeutils.IsZero(m.PaidOutAmount) { // not required
		return nil
	}

	if m.PaidOutAmount != nil {
		if err := m.PaidOutAmount.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("paidOutAmount")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("paidOutAmount")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this installment loan based on the context it is used
func (m *InstallmentLoan) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateContractConclusionDate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateContractPeriodInMonths(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateCreditAmount(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateEffectiveInterest(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateInstallmentAmount(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateInstallmentLoanID(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateNetCreditAmount(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateNominalInterest(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidatePaidOutAmount(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateProductDisplayID(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *InstallmentLoan) contextValidateContractConclusionDate(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "contractConclusionDate", "body", m.ContractConclusionDate); err != nil {
		return err
	}

	return nil
}

func (m *InstallmentLoan) contextValidateContractPeriodInMonths(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "contractPeriodInMonths", "body", m.ContractPeriodInMonths); err != nil {
		return err
	}

	return nil
}

func (m *InstallmentLoan) contextValidateCreditAmount(ctx context.Context, formats strfmt.Registry) error {

	if m.CreditAmount != nil {

		if typeutils.IsZero(m.CreditAmount) { // not required
			return nil
		}

		if err := m.CreditAmount.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("creditAmount")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("creditAmount")
			}

			return err
		}
	}

	return nil
}

func (m *InstallmentLoan) contextValidateEffectiveInterest(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "effectiveInterest", "body", m.EffectiveInterest); err != nil {
		return err
	}

	return nil
}

func (m *InstallmentLoan) contextValidateInstallmentAmount(ctx context.Context, formats strfmt.Registry) error {

	if m.InstallmentAmount != nil {

		if typeutils.IsZero(m.InstallmentAmount) { // not required
			return nil
		}

		if err := m.InstallmentAmount.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("installmentAmount")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("installmentAmount")
			}

			return err
		}
	}

	return nil
}

func (m *InstallmentLoan) contextValidateInstallmentLoanID(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "installmentLoanId", "body", m.InstallmentLoanID); err != nil {
		return err
	}

	return nil
}

func (m *InstallmentLoan) contextValidateNetCreditAmount(ctx context.Context, formats strfmt.Registry) error {

	if m.NetCreditAmount != nil {

		if typeutils.IsZero(m.NetCreditAmount) { // not required
			return nil
		}

		if err := m.NetCreditAmount.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("netCreditAmount")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("netCreditAmount")
			}

			return err
		}
	}

	return nil
}

func (m *InstallmentLoan) contextValidateNominalInterest(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "nominalInterest", "body", m.NominalInterest); err != nil {
		return err
	}

	return nil
}

func (m *InstallmentLoan) contextValidatePaidOutAmount(ctx context.Context, formats strfmt.Registry) error {

	if m.PaidOutAmount != nil {

		if typeutils.IsZero(m.PaidOutAmount) { // not required
			return nil
		}

		if err := m.PaidOutAmount.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("paidOutAmount")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("paidOutAmount")
			}

			return err
		}
	}

	return nil
}

func (m *InstallmentLoan) contextValidateProductDisplayID(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "productDisplayId", "body", m.ProductDisplayID); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *InstallmentLoan) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InstallmentLoan) UnmarshalBinary(b []byte) error {
	var res InstallmentLoan
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
