// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/validate"
)

// OrderType Model for an order type.
//
// swagger:model OrderType
type OrderType struct {

	// Names of the possible limit extensions
	// Read Only: true
	LimitExtensions []string `json:"limitExtensions"`

	// Names of possible trading restrictions
	// Read Only: true
	TradingRestrictions []string `json:"tradingRestrictions"`
}

// Validate validates this order type
func (m *OrderType) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validate this order type based on the context it is used
func (m *OrderType) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateLimitExtensions(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateTradingRestrictions(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OrderType) contextValidateLimitExtensions(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "limitExtensions", "body", m.LimitExtensions); err != nil {
		return err
	}

	return nil
}

func (m *OrderType) contextValidateTradingRestrictions(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "tradingRestrictions", "body", m.TradingRestrictions); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *OrderType) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OrderType) UnmarshalBinary(b []byte) error {
	var res OrderType
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
