// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	"encoding/json"
	stderrors "errors"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
	"github.com/go-openapi/validate"
)

// Order Model for an order.
//
// swagger:model Order
type Order struct {

	// Flag if order is a best-execution-order, default value is false
	BestEx *bool `json:"bestEx,omitempty"`

	// Canceled quantity or nominal amount
	CancelledQuantity *AmountValue `json:"cancelledQuantity,omitempty"`

	// Date/timestamp of the order entry in UTC with the following format: YYYY-MM-DDThh:mm:ss,ffffff+zz
	// Read Only: true
	CreationTimestamp *TimestampString `json:"creationTimestamp,omitempty"`

	// Unique securities account identification (as UUID)
	// Max Length: 40
	// Min Length: 0
	DepotID *string `json:"depotId,omitempty"`

	// Canceled quantity or nominal amount
	ExecutedQuantity *AmountValue `json:"executedQuantity,omitempty"`

	// List of execution types for the order
	// Read Only: true
	Executions []*Execution `json:"executions"`

	// Expected value of the limit order
	// Read Only: true
	ExpectedValue *AmountValue `json:"expectedValue,omitempty"`

	// WKN, ISIN or uuId; wkn will be returned if instrumentId is entered as wkn, an ISIN is returned if instrumentId is entered as ISIN, a uuId is returned if instrumentId is entered as uuId
	// Max Length: 40
	// Min Length: 0
	InstrumentID *string `json:"instrumentId,omitempty"`

	// Order leg number (if ordertype is OCO or NEO)
	// Read Only: true
	LegNumber int32 `json:"legNumber,omitempty"`

	// Limit of the order, empty in case of a market order, stop market, trailing stop market order or a corresponding suborder
	Limit *AmountValue `json:"limit,omitempty"`

	// Order extensions (Fill-or-Kill, Immediate-or-Cancel, All-or-None)
	// Max Length: 3
	// Min Length: 0
	// Enum: ["FOK","IOC","AON"]
	LimitExtension *string `json:"limitExtension,omitempty"`

	// Open quantity or nominal amount
	OpenQuantity *AmountValue `json:"openQuantity,omitempty"`

	// Unique order-Id (UUID)
	// Read Only: true
	// Max Length: 40
	// Min Length: 0
	OrderID string `json:"orderId,omitempty"`

	// Status of the order
	// Read Only: true
	// Max Length: 30
	// Min Length: 0
	// Enum: ["PENDING","OPEN","EXECUTED","SETTLED","CANCELLED_USER","EXPIRED","CANCELLED_SYSTEM","CANCELLED_TRADE","UNKNOWN"]
	OrderStatus string `json:"orderStatus,omitempty"`

	// Ordertype, partially executed and open orders are listed in the execution parameters
	// Max Length: 30
	// Min Length: 0
	// Enum: ["MARKET","LIMIT","QUOTE","STOP_MARKET","STOP_LIMIT","TRAILING_STOP_MARKET","TRAILING_STOP_LIMIT","ONE_CANCELS_OTHER","NEXT_ORDER"]
	OrderType *string `json:"orderType,omitempty"`

	// Quantity or nominal amount in the case of a percentage quotation
	Quantity *AmountValue `json:"quantity,omitempty"`

	// Quote-Id as reference for the quote received from the trading venue (issuer or exchange) on the quote request
	// Max Length: 40
	// Min Length: 0
	QuoteID *string `json:"quoteId,omitempty"`

	// Ticket UUID for the quote order. This is mandatory, if for a quote order
	// Max Length: 40
	// Min Length: 0
	QuoteTicketID *string `json:"quoteTicketId,omitempty"`

	// Reference settlement account for the securities account, if different from the settlement account assigned directly to the securities account (UUID)
	// Max Length: 40
	// Min Length: 0
	SettlementAccountID *string `json:"settlementAccountId,omitempty"`

	// Type of transaction
	// Max Length: 4
	// Min Length: 0
	// Enum: ["BUY","SELL"]
	Side *string `json:"side,omitempty"`

	// Parts of the orders, e.g. combination orders OCO, NEO (Next Order) with different order legs or partially executed or partially cancelled orders with different parts of an order
	SubOrders []*Order `json:"subOrders"`

	// Restrictions on trade (Opening Auction Only, Auction Only, Closing Auction Only)
	// Max Length: 3
	// Min Length: 0
	// Enum: ["OAO","AO","CAO"]
	TradingRestriction *string `json:"tradingRestriction,omitempty"`

	// Distance trigger limit of the trailing stop order from the current absolute price
	TrailingLimitDistAbs *AmountValue `json:"trailingLimitDistAbs,omitempty"`

	// Distance trigger limit of the trailing stop order from the current price in percentage
	TrailingLimitDistRel *PercentageString `json:"trailingLimitDistRel,omitempty"`

	// Trigger limit: stop limit by which a Stop order is triggered (Stop, TLS, OCO)
	TriggerLimit *AmountValue `json:"triggerLimit,omitempty"`

	// Date of order validity in format YYYY-MM-DD; required for validityType=GTD
	Validity *DateString `json:"validity,omitempty"`

	// Type of order validity (Good-for-day (default), Good-til-date (incl. end of month))
	// Max Length: 3
	// Min Length: 0
	// Enum: ["GFD","GTD"]
	ValidityType *string `json:"validityType,omitempty"`

	// UUID of the trading venue or partner. This is mandatory, if isBestEx=FALSE
	// Max Length: 40
	// Min Length: 0
	VenueID *string `json:"venueId,omitempty"`

	// Version of the position to be sold. Only applicable for sell
	Version string `json:"version,omitempty"`
}

// Validate validates this order
func (m *Order) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCancelledQuantity(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCreationTimestamp(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDepotID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateExecutedQuantity(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateExecutions(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateExpectedValue(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateInstrumentID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLimit(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLimitExtension(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOpenQuantity(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOrderID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOrderStatus(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOrderType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateQuantity(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateQuoteID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateQuoteTicketID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSettlementAccountID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSide(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSubOrders(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTradingRestriction(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTrailingLimitDistAbs(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTrailingLimitDistRel(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTriggerLimit(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateValidity(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateValidityType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateVenueID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Order) validateCancelledQuantity(formats strfmt.Registry) error {
	if typeutils.IsZero(m.CancelledQuantity) { // not required
		return nil
	}

	if m.CancelledQuantity != nil {
		if err := m.CancelledQuantity.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("cancelledQuantity")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("cancelledQuantity")
			}

			return err
		}
	}

	return nil
}

func (m *Order) validateCreationTimestamp(formats strfmt.Registry) error {
	if typeutils.IsZero(m.CreationTimestamp) { // not required
		return nil
	}

	if m.CreationTimestamp != nil {
		if err := m.CreationTimestamp.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("creationTimestamp")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("creationTimestamp")
			}

			return err
		}
	}

	return nil
}

func (m *Order) validateDepotID(formats strfmt.Registry) error {
	if typeutils.IsZero(m.DepotID) { // not required
		return nil
	}

	if err := validate.MinLength("depotId", "body", *m.DepotID, 0); err != nil {
		return err
	}

	if err := validate.MaxLength("depotId", "body", *m.DepotID, 40); err != nil {
		return err
	}

	return nil
}

func (m *Order) validateExecutedQuantity(formats strfmt.Registry) error {
	if typeutils.IsZero(m.ExecutedQuantity) { // not required
		return nil
	}

	if m.ExecutedQuantity != nil {
		if err := m.ExecutedQuantity.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("executedQuantity")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("executedQuantity")
			}

			return err
		}
	}

	return nil
}

func (m *Order) validateExecutions(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Executions) { // not required
		return nil
	}

	for i := 0; i < len(m.Executions); i++ {
		if typeutils.IsZero(m.Executions[i]) { // not required
			continue
		}

		if m.Executions[i] != nil {
			if err := m.Executions[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("executions" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("executions" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *Order) validateExpectedValue(formats strfmt.Registry) error {
	if typeutils.IsZero(m.ExpectedValue) { // not required
		return nil
	}

	if m.ExpectedValue != nil {
		if err := m.ExpectedValue.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("expectedValue")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("expectedValue")
			}

			return err
		}
	}

	return nil
}

func (m *Order) validateInstrumentID(formats strfmt.Registry) error {
	if typeutils.IsZero(m.InstrumentID) { // not required
		return nil
	}

	if err := validate.MinLength("instrumentId", "body", *m.InstrumentID, 0); err != nil {
		return err
	}

	if err := validate.MaxLength("instrumentId", "body", *m.InstrumentID, 40); err != nil {
		return err
	}

	return nil
}

func (m *Order) validateLimit(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Limit) { // not required
		return nil
	}

	if m.Limit != nil {
		if err := m.Limit.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("limit")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("limit")
			}

			return err
		}
	}

	return nil
}

var orderTypeLimitExtensionPropEnum []any

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["FOK","IOC","AON"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		orderTypeLimitExtensionPropEnum = append(orderTypeLimitExtensionPropEnum, v)
	}
}

const (

	// OrderLimitExtensionFOK captures enum value "FOK"
	OrderLimitExtensionFOK string = "FOK"

	// OrderLimitExtensionIOC captures enum value "IOC"
	OrderLimitExtensionIOC string = "IOC"

	// OrderLimitExtensionAON captures enum value "AON"
	OrderLimitExtensionAON string = "AON"
)

// prop value enum
func (m *Order) validateLimitExtensionEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, orderTypeLimitExtensionPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *Order) validateLimitExtension(formats strfmt.Registry) error {
	if typeutils.IsZero(m.LimitExtension) { // not required
		return nil
	}

	if err := validate.MinLength("limitExtension", "body", *m.LimitExtension, 0); err != nil {
		return err
	}

	if err := validate.MaxLength("limitExtension", "body", *m.LimitExtension, 3); err != nil {
		return err
	}

	// value enum
	if err := m.validateLimitExtensionEnum("limitExtension", "body", *m.LimitExtension); err != nil {
		return err
	}

	return nil
}

func (m *Order) validateOpenQuantity(formats strfmt.Registry) error {
	if typeutils.IsZero(m.OpenQuantity) { // not required
		return nil
	}

	if m.OpenQuantity != nil {
		if err := m.OpenQuantity.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("openQuantity")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("openQuantity")
			}

			return err
		}
	}

	return nil
}

func (m *Order) validateOrderID(formats strfmt.Registry) error {
	if typeutils.IsZero(m.OrderID) { // not required
		return nil
	}

	if err := validate.MinLength("orderId", "body", m.OrderID, 0); err != nil {
		return err
	}

	if err := validate.MaxLength("orderId", "body", m.OrderID, 40); err != nil {
		return err
	}

	return nil
}

var orderTypeOrderStatusPropEnum []any

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["PENDING","OPEN","EXECUTED","SETTLED","CANCELLED_USER","EXPIRED","CANCELLED_SYSTEM","CANCELLED_TRADE","UNKNOWN"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		orderTypeOrderStatusPropEnum = append(orderTypeOrderStatusPropEnum, v)
	}
}

const (

	// OrderOrderStatusPENDING captures enum value "PENDING"
	OrderOrderStatusPENDING string = "PENDING"

	// OrderOrderStatusOPEN captures enum value "OPEN"
	OrderOrderStatusOPEN string = "OPEN"

	// OrderOrderStatusEXECUTED captures enum value "EXECUTED"
	OrderOrderStatusEXECUTED string = "EXECUTED"

	// OrderOrderStatusSETTLED captures enum value "SETTLED"
	OrderOrderStatusSETTLED string = "SETTLED"

	// OrderOrderStatusCANCELLEDUSER captures enum value "CANCELLED_USER"
	OrderOrderStatusCANCELLEDUSER string = "CANCELLED_USER"

	// OrderOrderStatusEXPIRED captures enum value "EXPIRED"
	OrderOrderStatusEXPIRED string = "EXPIRED"

	// OrderOrderStatusCANCELLEDSYSTEM captures enum value "CANCELLED_SYSTEM"
	OrderOrderStatusCANCELLEDSYSTEM string = "CANCELLED_SYSTEM"

	// OrderOrderStatusCANCELLEDTRADE captures enum value "CANCELLED_TRADE"
	OrderOrderStatusCANCELLEDTRADE string = "CANCELLED_TRADE"

	// OrderOrderStatusUNKNOWN captures enum value "UNKNOWN"
	OrderOrderStatusUNKNOWN string = "UNKNOWN"
)

// prop value enum
func (m *Order) validateOrderStatusEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, orderTypeOrderStatusPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *Order) validateOrderStatus(formats strfmt.Registry) error {
	if typeutils.IsZero(m.OrderStatus) { // not required
		return nil
	}

	if err := validate.MinLength("orderStatus", "body", m.OrderStatus, 0); err != nil {
		return err
	}

	if err := validate.MaxLength("orderStatus", "body", m.OrderStatus, 30); err != nil {
		return err
	}

	// value enum
	if err := m.validateOrderStatusEnum("orderStatus", "body", m.OrderStatus); err != nil {
		return err
	}

	return nil
}

var orderTypeOrderTypePropEnum []any

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["MARKET","LIMIT","QUOTE","STOP_MARKET","STOP_LIMIT","TRAILING_STOP_MARKET","TRAILING_STOP_LIMIT","ONE_CANCELS_OTHER","NEXT_ORDER"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		orderTypeOrderTypePropEnum = append(orderTypeOrderTypePropEnum, v)
	}
}

const (

	// OrderOrderTypeMARKET captures enum value "MARKET"
	OrderOrderTypeMARKET string = "MARKET"

	// OrderOrderTypeLIMIT captures enum value "LIMIT"
	OrderOrderTypeLIMIT string = "LIMIT"

	// OrderOrderTypeQUOTE captures enum value "QUOTE"
	OrderOrderTypeQUOTE string = "QUOTE"

	// OrderOrderTypeSTOPMARKET captures enum value "STOP_MARKET"
	OrderOrderTypeSTOPMARKET string = "STOP_MARKET"

	// OrderOrderTypeSTOPLIMIT captures enum value "STOP_LIMIT"
	OrderOrderTypeSTOPLIMIT string = "STOP_LIMIT"

	// OrderOrderTypeTRAILINGSTOPMARKET captures enum value "TRAILING_STOP_MARKET"
	OrderOrderTypeTRAILINGSTOPMARKET string = "TRAILING_STOP_MARKET"

	// OrderOrderTypeTRAILINGSTOPLIMIT captures enum value "TRAILING_STOP_LIMIT"
	OrderOrderTypeTRAILINGSTOPLIMIT string = "TRAILING_STOP_LIMIT"

	// OrderOrderTypeONECANCELSOTHER captures enum value "ONE_CANCELS_OTHER"
	OrderOrderTypeONECANCELSOTHER string = "ONE_CANCELS_OTHER"

	// OrderOrderTypeNEXTORDER captures enum value "NEXT_ORDER"
	OrderOrderTypeNEXTORDER string = "NEXT_ORDER"
)

// prop value enum
func (m *Order) validateOrderTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, orderTypeOrderTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *Order) validateOrderType(formats strfmt.Registry) error {
	if typeutils.IsZero(m.OrderType) { // not required
		return nil
	}

	if err := validate.MinLength("orderType", "body", *m.OrderType, 0); err != nil {
		return err
	}

	if err := validate.MaxLength("orderType", "body", *m.OrderType, 30); err != nil {
		return err
	}

	// value enum
	if err := m.validateOrderTypeEnum("orderType", "body", *m.OrderType); err != nil {
		return err
	}

	return nil
}

func (m *Order) validateQuantity(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Quantity) { // not required
		return nil
	}

	if m.Quantity != nil {
		if err := m.Quantity.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("quantity")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("quantity")
			}

			return err
		}
	}

	return nil
}

func (m *Order) validateQuoteID(formats strfmt.Registry) error {
	if typeutils.IsZero(m.QuoteID) { // not required
		return nil
	}

	if err := validate.MinLength("quoteId", "body", *m.QuoteID, 0); err != nil {
		return err
	}

	if err := validate.MaxLength("quoteId", "body", *m.QuoteID, 40); err != nil {
		return err
	}

	return nil
}

func (m *Order) validateQuoteTicketID(formats strfmt.Registry) error {
	if typeutils.IsZero(m.QuoteTicketID) { // not required
		return nil
	}

	if err := validate.MinLength("quoteTicketId", "body", *m.QuoteTicketID, 0); err != nil {
		return err
	}

	if err := validate.MaxLength("quoteTicketId", "body", *m.QuoteTicketID, 40); err != nil {
		return err
	}

	return nil
}

func (m *Order) validateSettlementAccountID(formats strfmt.Registry) error {
	if typeutils.IsZero(m.SettlementAccountID) { // not required
		return nil
	}

	if err := validate.MinLength("settlementAccountId", "body", *m.SettlementAccountID, 0); err != nil {
		return err
	}

	if err := validate.MaxLength("settlementAccountId", "body", *m.SettlementAccountID, 40); err != nil {
		return err
	}

	return nil
}

var orderTypeSidePropEnum []any

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["BUY","SELL"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		orderTypeSidePropEnum = append(orderTypeSidePropEnum, v)
	}
}

const (

	// OrderSideBUY captures enum value "BUY"
	OrderSideBUY string = "BUY"

	// OrderSideSELL captures enum value "SELL"
	OrderSideSELL string = "SELL"
)

// prop value enum
func (m *Order) validateSideEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, orderTypeSidePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *Order) validateSide(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Side) { // not required
		return nil
	}

	if err := validate.MinLength("side", "body", *m.Side, 0); err != nil {
		return err
	}

	if err := validate.MaxLength("side", "body", *m.Side, 4); err != nil {
		return err
	}

	// value enum
	if err := m.validateSideEnum("side", "body", *m.Side); err != nil {
		return err
	}

	return nil
}

func (m *Order) validateSubOrders(formats strfmt.Registry) error {
	if typeutils.IsZero(m.SubOrders) { // not required
		return nil
	}

	for i := 0; i < len(m.SubOrders); i++ {
		if typeutils.IsZero(m.SubOrders[i]) { // not required
			continue
		}

		if m.SubOrders[i] != nil {
			if err := m.SubOrders[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("subOrders" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("subOrders" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

var orderTypeTradingRestrictionPropEnum []any

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["OAO","AO","CAO"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		orderTypeTradingRestrictionPropEnum = append(orderTypeTradingRestrictionPropEnum, v)
	}
}

const (

	// OrderTradingRestrictionOAO captures enum value "OAO"
	OrderTradingRestrictionOAO string = "OAO"

	// OrderTradingRestrictionAO captures enum value "AO"
	OrderTradingRestrictionAO string = "AO"

	// OrderTradingRestrictionCAO captures enum value "CAO"
	OrderTradingRestrictionCAO string = "CAO"
)

// prop value enum
func (m *Order) validateTradingRestrictionEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, orderTypeTradingRestrictionPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *Order) validateTradingRestriction(formats strfmt.Registry) error {
	if typeutils.IsZero(m.TradingRestriction) { // not required
		return nil
	}

	if err := validate.MinLength("tradingRestriction", "body", *m.TradingRestriction, 0); err != nil {
		return err
	}

	if err := validate.MaxLength("tradingRestriction", "body", *m.TradingRestriction, 3); err != nil {
		return err
	}

	// value enum
	if err := m.validateTradingRestrictionEnum("tradingRestriction", "body", *m.TradingRestriction); err != nil {
		return err
	}

	return nil
}

func (m *Order) validateTrailingLimitDistAbs(formats strfmt.Registry) error {
	if typeutils.IsZero(m.TrailingLimitDistAbs) { // not required
		return nil
	}

	if m.TrailingLimitDistAbs != nil {
		if err := m.TrailingLimitDistAbs.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("trailingLimitDistAbs")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("trailingLimitDistAbs")
			}

			return err
		}
	}

	return nil
}

func (m *Order) validateTrailingLimitDistRel(formats strfmt.Registry) error {
	if typeutils.IsZero(m.TrailingLimitDistRel) { // not required
		return nil
	}

	if m.TrailingLimitDistRel != nil {
		if err := m.TrailingLimitDistRel.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("trailingLimitDistRel")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("trailingLimitDistRel")
			}

			return err
		}
	}

	return nil
}

func (m *Order) validateTriggerLimit(formats strfmt.Registry) error {
	if typeutils.IsZero(m.TriggerLimit) { // not required
		return nil
	}

	if m.TriggerLimit != nil {
		if err := m.TriggerLimit.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("triggerLimit")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("triggerLimit")
			}

			return err
		}
	}

	return nil
}

func (m *Order) validateValidity(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Validity) { // not required
		return nil
	}

	if m.Validity != nil {
		if err := m.Validity.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("validity")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("validity")
			}

			return err
		}
	}

	return nil
}

var orderTypeValidityTypePropEnum []any

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["GFD","GTD"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		orderTypeValidityTypePropEnum = append(orderTypeValidityTypePropEnum, v)
	}
}

const (

	// OrderValidityTypeGFD captures enum value "GFD"
	OrderValidityTypeGFD string = "GFD"

	// OrderValidityTypeGTD captures enum value "GTD"
	OrderValidityTypeGTD string = "GTD"
)

// prop value enum
func (m *Order) validateValidityTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, orderTypeValidityTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *Order) validateValidityType(formats strfmt.Registry) error {
	if typeutils.IsZero(m.ValidityType) { // not required
		return nil
	}

	if err := validate.MinLength("validityType", "body", *m.ValidityType, 0); err != nil {
		return err
	}

	if err := validate.MaxLength("validityType", "body", *m.ValidityType, 3); err != nil {
		return err
	}

	// value enum
	if err := m.validateValidityTypeEnum("validityType", "body", *m.ValidityType); err != nil {
		return err
	}

	return nil
}

func (m *Order) validateVenueID(formats strfmt.Registry) error {
	if typeutils.IsZero(m.VenueID) { // not required
		return nil
	}

	if err := validate.MinLength("venueId", "body", *m.VenueID, 0); err != nil {
		return err
	}

	if err := validate.MaxLength("venueId", "body", *m.VenueID, 40); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this order based on the context it is used
func (m *Order) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateCancelledQuantity(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateCreationTimestamp(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateExecutedQuantity(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateExecutions(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateExpectedValue(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateLegNumber(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateLimit(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateOpenQuantity(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateOrderID(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateOrderStatus(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateQuantity(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateSubOrders(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateTrailingLimitDistAbs(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateTrailingLimitDistRel(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateTriggerLimit(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateValidity(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Order) contextValidateCancelledQuantity(ctx context.Context, formats strfmt.Registry) error {

	if m.CancelledQuantity != nil {

		if typeutils.IsZero(m.CancelledQuantity) { // not required
			return nil
		}

		if err := m.CancelledQuantity.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("cancelledQuantity")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("cancelledQuantity")
			}

			return err
		}
	}

	return nil
}

func (m *Order) contextValidateCreationTimestamp(ctx context.Context, formats strfmt.Registry) error {

	if m.CreationTimestamp != nil {

		if typeutils.IsZero(m.CreationTimestamp) { // not required
			return nil
		}

		if err := m.CreationTimestamp.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("creationTimestamp")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("creationTimestamp")
			}

			return err
		}
	}

	return nil
}

func (m *Order) contextValidateExecutedQuantity(ctx context.Context, formats strfmt.Registry) error {

	if m.ExecutedQuantity != nil {

		if typeutils.IsZero(m.ExecutedQuantity) { // not required
			return nil
		}

		if err := m.ExecutedQuantity.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("executedQuantity")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("executedQuantity")
			}

			return err
		}
	}

	return nil
}

func (m *Order) contextValidateExecutions(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "executions", "body", m.Executions); err != nil {
		return err
	}

	for i := 0; i < len(m.Executions); i++ {

		if m.Executions[i] != nil {

			if typeutils.IsZero(m.Executions[i]) { // not required
				return nil
			}

			if err := m.Executions[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("executions" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("executions" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *Order) contextValidateExpectedValue(ctx context.Context, formats strfmt.Registry) error {

	if m.ExpectedValue != nil {

		if typeutils.IsZero(m.ExpectedValue) { // not required
			return nil
		}

		if err := m.ExpectedValue.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("expectedValue")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("expectedValue")
			}

			return err
		}
	}

	return nil
}

func (m *Order) contextValidateLegNumber(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "legNumber", "body", m.LegNumber); err != nil {
		return err
	}

	return nil
}

func (m *Order) contextValidateLimit(ctx context.Context, formats strfmt.Registry) error {

	if m.Limit != nil {

		if typeutils.IsZero(m.Limit) { // not required
			return nil
		}

		if err := m.Limit.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("limit")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("limit")
			}

			return err
		}
	}

	return nil
}

func (m *Order) contextValidateOpenQuantity(ctx context.Context, formats strfmt.Registry) error {

	if m.OpenQuantity != nil {

		if typeutils.IsZero(m.OpenQuantity) { // not required
			return nil
		}

		if err := m.OpenQuantity.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("openQuantity")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("openQuantity")
			}

			return err
		}
	}

	return nil
}

func (m *Order) contextValidateOrderID(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "orderId", "body", m.OrderID); err != nil {
		return err
	}

	return nil
}

func (m *Order) contextValidateOrderStatus(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "orderStatus", "body", m.OrderStatus); err != nil {
		return err
	}

	return nil
}

func (m *Order) contextValidateQuantity(ctx context.Context, formats strfmt.Registry) error {

	if m.Quantity != nil {

		if typeutils.IsZero(m.Quantity) { // not required
			return nil
		}

		if err := m.Quantity.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("quantity")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("quantity")
			}

			return err
		}
	}

	return nil
}

func (m *Order) contextValidateSubOrders(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.SubOrders); i++ {

		if m.SubOrders[i] != nil {

			if typeutils.IsZero(m.SubOrders[i]) { // not required
				return nil
			}

			if err := m.SubOrders[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("subOrders" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("subOrders" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *Order) contextValidateTrailingLimitDistAbs(ctx context.Context, formats strfmt.Registry) error {

	if m.TrailingLimitDistAbs != nil {

		if typeutils.IsZero(m.TrailingLimitDistAbs) { // not required
			return nil
		}

		if err := m.TrailingLimitDistAbs.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("trailingLimitDistAbs")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("trailingLimitDistAbs")
			}

			return err
		}
	}

	return nil
}

func (m *Order) contextValidateTrailingLimitDistRel(ctx context.Context, formats strfmt.Registry) error {

	if m.TrailingLimitDistRel != nil {

		if typeutils.IsZero(m.TrailingLimitDistRel) { // not required
			return nil
		}

		if err := m.TrailingLimitDistRel.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("trailingLimitDistRel")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("trailingLimitDistRel")
			}

			return err
		}
	}

	return nil
}

func (m *Order) contextValidateTriggerLimit(ctx context.Context, formats strfmt.Registry) error {

	if m.TriggerLimit != nil {

		if typeutils.IsZero(m.TriggerLimit) { // not required
			return nil
		}

		if err := m.TriggerLimit.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("triggerLimit")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("triggerLimit")
			}

			return err
		}
	}

	return nil
}

func (m *Order) contextValidateValidity(ctx context.Context, formats strfmt.Registry) error {

	if m.Validity != nil {

		if typeutils.IsZero(m.Validity) { // not required
			return nil
		}

		if err := m.Validity.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("validity")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("validity")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Order) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Order) UnmarshalBinary(b []byte) error {
	var res Order
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
