// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// PagingInfo paging info
//
// swagger:model PagingInfo
type PagingInfo struct {

	// index
	Index int32 `json:"index,omitempty"`

	// matches
	Matches int32 `json:"matches,omitempty"`
}

// Validate validates this paging info
func (m *PagingInfo) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this paging info based on context it is used
func (m *PagingInfo) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PagingInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PagingInfo) UnmarshalBinary(b []byte) error {
	var res PagingInfo
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
