// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
	"github.com/go-openapi/validate"
)

// PercentageString Represents the percentage value.
//
// swagger:model PercentageString
type PercentageString struct {

	// Decimal places
	// Example: 99
	// Pattern: ^[0-9]*$
	DecimalPlaces string `json:"decimalPlaces,omitempty"`

	// percent string
	PercentString string `json:"percentString,omitempty"`

	// Pre-decimal places
	// Example: 99
	// Max Length: 18
	// Min Length: 0
	// Pattern: ^(0|[1-9][0-9]*)$
	PreDecimalPlaces *string `json:"preDecimalPlaces,omitempty"`
}

// Validate validates this percentage string
func (m *PercentageString) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDecimalPlaces(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePreDecimalPlaces(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PercentageString) validateDecimalPlaces(formats strfmt.Registry) error {
	if typeutils.IsZero(m.DecimalPlaces) { // not required
		return nil
	}

	if err := validate.Pattern("decimalPlaces", "body", m.DecimalPlaces, `^[0-9]*$`); err != nil {
		return err
	}

	return nil
}

func (m *PercentageString) validatePreDecimalPlaces(formats strfmt.Registry) error {
	if typeutils.IsZero(m.PreDecimalPlaces) { // not required
		return nil
	}

	if err := validate.MinLength("preDecimalPlaces", "body", *m.PreDecimalPlaces, 0); err != nil {
		return err
	}

	if err := validate.MaxLength("preDecimalPlaces", "body", *m.PreDecimalPlaces, 18); err != nil {
		return err
	}

	if err := validate.Pattern("preDecimalPlaces", "body", *m.PreDecimalPlaces, `^(0|[1-9][0-9]*)$`); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this percentage string based on context it is used
func (m *PercentageString) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PercentageString) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PercentageString) UnmarshalBinary(b []byte) error {
	var res PercentageString
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
