// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
	"github.com/go-openapi/validate"
)

// Price Represents a price.
//
// swagger:model Price
type Price struct {

	// Price.
	// Example: 999.99 EUR
	// Read Only: true
	Price *AmountValue `json:"price,omitempty"`

	// Datetime with format: 'yyyy-MM-dd'T'HH:mm:ssX
	// Example: 2018-07-03T12:29:30+01
	// Read Only: true
	PriceDateTime *DateTimeString `json:"priceDateTime,omitempty"`

	// Quantity or nominal amount in case of a percentage quotation.
	// Example: 1000 XXX
	// Read Only: true
	Quantity *AmountValue `json:"quantity,omitempty"`

	// Type of the price. Can be one of the following: {LST, BID, ASK, MID}.
	// Example: BID
	// Read Only: true
	// Max Length: 3
	// Min Length: 3
	Type string `json:"type,omitempty"`
}

// Validate validates this price
func (m *Price) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePrice(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePriceDateTime(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateQuantity(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Price) validatePrice(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Price) { // not required
		return nil
	}

	if m.Price != nil {
		if err := m.Price.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("price")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("price")
			}

			return err
		}
	}

	return nil
}

func (m *Price) validatePriceDateTime(formats strfmt.Registry) error {
	if typeutils.IsZero(m.PriceDateTime) { // not required
		return nil
	}

	if m.PriceDateTime != nil {
		if err := m.PriceDateTime.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("priceDateTime")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("priceDateTime")
			}

			return err
		}
	}

	return nil
}

func (m *Price) validateQuantity(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Quantity) { // not required
		return nil
	}

	if m.Quantity != nil {
		if err := m.Quantity.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("quantity")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("quantity")
			}

			return err
		}
	}

	return nil
}

func (m *Price) validateType(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Type) { // not required
		return nil
	}

	if err := validate.MinLength("type", "body", m.Type, 3); err != nil {
		return err
	}

	if err := validate.MaxLength("type", "body", m.Type, 3); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this price based on the context it is used
func (m *Price) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidatePrice(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidatePriceDateTime(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateQuantity(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateType(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Price) contextValidatePrice(ctx context.Context, formats strfmt.Registry) error {

	if m.Price != nil {

		if typeutils.IsZero(m.Price) { // not required
			return nil
		}

		if err := m.Price.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("price")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("price")
			}

			return err
		}
	}

	return nil
}

func (m *Price) contextValidatePriceDateTime(ctx context.Context, formats strfmt.Registry) error {

	if m.PriceDateTime != nil {

		if typeutils.IsZero(m.PriceDateTime) { // not required
			return nil
		}

		if err := m.PriceDateTime.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("priceDateTime")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("priceDateTime")
			}

			return err
		}
	}

	return nil
}

func (m *Price) contextValidateQuantity(ctx context.Context, formats strfmt.Registry) error {

	if m.Quantity != nil {

		if typeutils.IsZero(m.Quantity) { // not required
			return nil
		}

		if err := m.Quantity.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("quantity")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("quantity")
			}

			return err
		}
	}

	return nil
}

func (m *Price) contextValidateType(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "type", "body", m.Type); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Price) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Price) UnmarshalBinary(b []byte) error {
	var res Price
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
