// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	"encoding/json"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
	"github.com/go-openapi/validate"
)

// ProductBalance Model for a product balance.
//
// swagger:model ProductBalance
type ProductBalance struct {

	// Balance object based on the product type.
	// Read Only: true
	Balance *Balance `json:"balance,omitempty"`

	// Type of the client connection.
	// Example: CURRENT_CLIENT
	// Read Only: true
	// Enum: ["CURRENT_CLIENT","OTHER_COMDIRECT","OTHER_EXTERNAL"]
	ClientConnectionType string `json:"clientConnectionType,omitempty"`

	// Unique ID of the product (UUID).
	// Example: B2D8C9A36F640148C915338922030951
	// Read Only: true
	ProductID string `json:"productId,omitempty"`

	// Type of the product.
	// Example: ACCOUNT
	// Read Only: true
	// Enum: ["ACCOUNT","CARD","DEPOT","LOAN","SAVINGS"]
	ProductType string `json:"productType,omitempty"`

	// Unique Id of the target client (UUID).
	// Example: B2D8C9A36F640148C915338922030951
	// Read Only: true
	TargetClientID string `json:"targetClientId,omitempty"`
}

// Validate validates this product balance
func (m *ProductBalance) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBalance(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateClientConnectionType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProductType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ProductBalance) validateBalance(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Balance) { // not required
		return nil
	}

	if m.Balance != nil {
		if err := m.Balance.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("balance")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("balance")
			}

			return err
		}
	}

	return nil
}

var productBalanceTypeClientConnectionTypePropEnum []any

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["CURRENT_CLIENT","OTHER_COMDIRECT","OTHER_EXTERNAL"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		productBalanceTypeClientConnectionTypePropEnum = append(productBalanceTypeClientConnectionTypePropEnum, v)
	}
}

const (

	// ProductBalanceClientConnectionTypeCURRENTCLIENT captures enum value "CURRENT_CLIENT"
	ProductBalanceClientConnectionTypeCURRENTCLIENT string = "CURRENT_CLIENT"

	// ProductBalanceClientConnectionTypeOTHERCOMDIRECT captures enum value "OTHER_COMDIRECT"
	ProductBalanceClientConnectionTypeOTHERCOMDIRECT string = "OTHER_COMDIRECT"

	// ProductBalanceClientConnectionTypeOTHEREXTERNAL captures enum value "OTHER_EXTERNAL"
	ProductBalanceClientConnectionTypeOTHEREXTERNAL string = "OTHER_EXTERNAL"
)

// prop value enum
func (m *ProductBalance) validateClientConnectionTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, productBalanceTypeClientConnectionTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *ProductBalance) validateClientConnectionType(formats strfmt.Registry) error {
	if typeutils.IsZero(m.ClientConnectionType) { // not required
		return nil
	}

	// value enum
	if err := m.validateClientConnectionTypeEnum("clientConnectionType", "body", m.ClientConnectionType); err != nil {
		return err
	}

	return nil
}

var productBalanceTypeProductTypePropEnum []any

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["ACCOUNT","CARD","DEPOT","LOAN","SAVINGS"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		productBalanceTypeProductTypePropEnum = append(productBalanceTypeProductTypePropEnum, v)
	}
}

const (

	// ProductBalanceProductTypeACCOUNT captures enum value "ACCOUNT"
	ProductBalanceProductTypeACCOUNT string = "ACCOUNT"

	// ProductBalanceProductTypeCARD captures enum value "CARD"
	ProductBalanceProductTypeCARD string = "CARD"

	// ProductBalanceProductTypeDEPOT captures enum value "DEPOT"
	ProductBalanceProductTypeDEPOT string = "DEPOT"

	// ProductBalanceProductTypeLOAN captures enum value "LOAN"
	ProductBalanceProductTypeLOAN string = "LOAN"

	// ProductBalanceProductTypeSAVINGS captures enum value "SAVINGS"
	ProductBalanceProductTypeSAVINGS string = "SAVINGS"
)

// prop value enum
func (m *ProductBalance) validateProductTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, productBalanceTypeProductTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *ProductBalance) validateProductType(formats strfmt.Registry) error {
	if typeutils.IsZero(m.ProductType) { // not required
		return nil
	}

	// value enum
	if err := m.validateProductTypeEnum("productType", "body", m.ProductType); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this product balance based on the context it is used
func (m *ProductBalance) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateBalance(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateClientConnectionType(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateProductID(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateProductType(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateTargetClientID(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ProductBalance) contextValidateBalance(ctx context.Context, formats strfmt.Registry) error {

	if m.Balance != nil {

		if typeutils.IsZero(m.Balance) { // not required
			return nil
		}

		if err := m.Balance.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("balance")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("balance")
			}

			return err
		}
	}

	return nil
}

func (m *ProductBalance) contextValidateClientConnectionType(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "clientConnectionType", "body", m.ClientConnectionType); err != nil {
		return err
	}

	return nil
}

func (m *ProductBalance) contextValidateProductID(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "productId", "body", m.ProductID); err != nil {
		return err
	}

	return nil
}

func (m *ProductBalance) contextValidateProductType(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "productType", "body", m.ProductType); err != nil {
		return err
	}

	return nil
}

func (m *ProductBalance) contextValidateTargetClientID(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "targetClientId", "body", m.TargetClientID); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ProductBalance) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ProductBalance) UnmarshalBinary(b []byte) error {
	var res ProductBalance
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
