// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	"encoding/json"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
	"github.com/go-openapi/validate"
)

// Quote Model for a quote request.
//
// swagger:model Quote
type Quote struct {

	// Unique securities account identification (as UUID)
	// Max Length: 40
	// Min Length: 0
	DepotID *string `json:"depotId,omitempty"`

	// WKN, ISIN or uuId; wkn will be returned if instrumentId is entered as wkn, an ISIN is returned if instrumentId is entered as ISIN, a uuId is returned if instrumentId is entered as uuId
	// Max Length: 40
	// Min Length: 0
	InstrumentID *string `json:"instrumentId,omitempty"`

	// Quantity or nominal amount in the case of a percentage quotation
	Quantity *AmountValue `json:"quantity,omitempty"`

	// Type of transaction
	// Max Length: 4
	// Min Length: 0
	// Enum: ["BUY","SELL"]
	Side *string `json:"side,omitempty"`

	// UUID of the trading venue or partner. This is mandatory, if isBestEx=FALSE
	// Max Length: 40
	// Min Length: 0
	VenueID *string `json:"venueId,omitempty"`
}

// Validate validates this quote
func (m *Quote) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDepotID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateInstrumentID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateQuantity(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSide(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateVenueID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Quote) validateDepotID(formats strfmt.Registry) error {
	if typeutils.IsZero(m.DepotID) { // not required
		return nil
	}

	if err := validate.MinLength("depotId", "body", *m.DepotID, 0); err != nil {
		return err
	}

	if err := validate.MaxLength("depotId", "body", *m.DepotID, 40); err != nil {
		return err
	}

	return nil
}

func (m *Quote) validateInstrumentID(formats strfmt.Registry) error {
	if typeutils.IsZero(m.InstrumentID) { // not required
		return nil
	}

	if err := validate.MinLength("instrumentId", "body", *m.InstrumentID, 0); err != nil {
		return err
	}

	if err := validate.MaxLength("instrumentId", "body", *m.InstrumentID, 40); err != nil {
		return err
	}

	return nil
}

func (m *Quote) validateQuantity(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Quantity) { // not required
		return nil
	}

	if m.Quantity != nil {
		if err := m.Quantity.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("quantity")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("quantity")
			}

			return err
		}
	}

	return nil
}

var quoteTypeSidePropEnum []any

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["BUY","SELL"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		quoteTypeSidePropEnum = append(quoteTypeSidePropEnum, v)
	}
}

const (

	// QuoteSideBUY captures enum value "BUY"
	QuoteSideBUY string = "BUY"

	// QuoteSideSELL captures enum value "SELL"
	QuoteSideSELL string = "SELL"
)

// prop value enum
func (m *Quote) validateSideEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, quoteTypeSidePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *Quote) validateSide(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Side) { // not required
		return nil
	}

	if err := validate.MinLength("side", "body", *m.Side, 0); err != nil {
		return err
	}

	if err := validate.MaxLength("side", "body", *m.Side, 4); err != nil {
		return err
	}

	// value enum
	if err := m.validateSideEnum("side", "body", *m.Side); err != nil {
		return err
	}

	return nil
}

func (m *Quote) validateVenueID(formats strfmt.Registry) error {
	if typeutils.IsZero(m.VenueID) { // not required
		return nil
	}

	if err := validate.MinLength("venueId", "body", *m.VenueID, 0); err != nil {
		return err
	}

	if err := validate.MaxLength("venueId", "body", *m.VenueID, 40); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this quote based on the context it is used
func (m *Quote) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateQuantity(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Quote) contextValidateQuantity(ctx context.Context, formats strfmt.Registry) error {

	if m.Quantity != nil {

		if typeutils.IsZero(m.Quantity) { // not required
			return nil
		}

		if err := m.Quantity.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("quantity")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("quantity")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Quote) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Quote) UnmarshalBinary(b []byte) error {
	var res Quote
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
