// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/validate"
)

// Rating Rating of the instrument.
//
// swagger:model Rating
type Rating struct {

	// Bonds Rating
	// Read Only: true
	Moodys string `json:"moodys,omitempty"`

	// Funds Rating
	// Read Only: true
	Morningstar string `json:"morningstar,omitempty"`
}

// Validate validates this rating
func (m *Rating) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validate this rating based on the context it is used
func (m *Rating) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateMoodys(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateMorningstar(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Rating) contextValidateMoodys(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "moodys", "body", m.Moodys); err != nil {
		return err
	}

	return nil
}

func (m *Rating) contextValidateMorningstar(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "morningstar", "body", m.Morningstar); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Rating) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Rating) UnmarshalBinary(b []byte) error {
	var res Rating
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
