// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	"encoding/json"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
	"github.com/go-openapi/validate"
)

// StaticData Static data of the instrument.
//
// swagger:model StaticData
type StaticData struct {

	// instrument currency of a security, e.g., for bonds, bond and open real estate funds; additionally to ISO 4217 currency code the following values are possible: XXX (Pcs.), XXP (Pts.), XXU (Unknown)
	// Read Only: true
	Currency *CurrencyString `json:"currency,omitempty"`

	// Flag indicating - if TRUE - that within prevalidation and before placement of a buy order a static note must be displayed indicating that the redemption of the fund is limited.
	// Read Only: true
	FundRedemptionLimited *bool `json:"fundRedemptionLimited,omitempty"`

	// Instrument type
	// Read Only: true
	// Enum: ["SHARE","BONDS","SUBSCRIPTION_RIGHT","ETF","PROFIT_PART_CERTIFICATE","FUND","WARRANT","CERTIFICATE","NOT_AVAILABLE"]
	InstrumentType string `json:"instrumentType,omitempty"`

	// Flag indicating - if TRUE - that a Key Information Document (KID) of the issuer is electronically available. Before order placement a static note ought to displayed in such a case.
	// Read Only: true
	KidAvailable *bool `json:"kidAvailable,omitempty"`

	// Ticker symbol or notation of a security
	// Read Only: true
	// Enum: ["XXX","XXC","XXM","XXP","XXU"]
	Notation string `json:"notation,omitempty"`

	// Flag indicating - if TRUE - that EU-regulation referring to Packaged Retail and Insurance-based Investment Products - PRIIPs) is relevant for the instrument
	// Read Only: true
	PriipsRelevant *bool `json:"priipsRelevant,omitempty"`

	// Flag indicating - if TRUE - that within prevalidation and before placement of a buy order the investor must approve, e.g., by a frontend checkbox that no shipping of fund sales information is required (waiver); a static note regarding that information ought to be displayed in such a case. Without an explicit waiver the order placement must be prevented in the frontend.
	// Read Only: true
	ShippingWaiverRequired *bool `json:"shippingWaiverRequired,omitempty"`
}

// Validate validates this static data
func (m *StaticData) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCurrency(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateInstrumentType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateNotation(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *StaticData) validateCurrency(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Currency) { // not required
		return nil
	}

	if m.Currency != nil {
		if err := m.Currency.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("currency")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("currency")
			}

			return err
		}
	}

	return nil
}

var staticDataTypeInstrumentTypePropEnum []any

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["SHARE","BONDS","SUBSCRIPTION_RIGHT","ETF","PROFIT_PART_CERTIFICATE","FUND","WARRANT","CERTIFICATE","NOT_AVAILABLE"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		staticDataTypeInstrumentTypePropEnum = append(staticDataTypeInstrumentTypePropEnum, v)
	}
}

const (

	// StaticDataInstrumentTypeSHARE captures enum value "SHARE"
	StaticDataInstrumentTypeSHARE string = "SHARE"

	// StaticDataInstrumentTypeBONDS captures enum value "BONDS"
	StaticDataInstrumentTypeBONDS string = "BONDS"

	// StaticDataInstrumentTypeSUBSCRIPTIONRIGHT captures enum value "SUBSCRIPTION_RIGHT"
	StaticDataInstrumentTypeSUBSCRIPTIONRIGHT string = "SUBSCRIPTION_RIGHT"

	// StaticDataInstrumentTypeETF captures enum value "ETF"
	StaticDataInstrumentTypeETF string = "ETF"

	// StaticDataInstrumentTypePROFITPARTCERTIFICATE captures enum value "PROFIT_PART_CERTIFICATE"
	StaticDataInstrumentTypePROFITPARTCERTIFICATE string = "PROFIT_PART_CERTIFICATE"

	// StaticDataInstrumentTypeFUND captures enum value "FUND"
	StaticDataInstrumentTypeFUND string = "FUND"

	// StaticDataInstrumentTypeWARRANT captures enum value "WARRANT"
	StaticDataInstrumentTypeWARRANT string = "WARRANT"

	// StaticDataInstrumentTypeCERTIFICATE captures enum value "CERTIFICATE"
	StaticDataInstrumentTypeCERTIFICATE string = "CERTIFICATE"

	// StaticDataInstrumentTypeNOTAVAILABLE captures enum value "NOT_AVAILABLE"
	StaticDataInstrumentTypeNOTAVAILABLE string = "NOT_AVAILABLE"
)

// prop value enum
func (m *StaticData) validateInstrumentTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, staticDataTypeInstrumentTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *StaticData) validateInstrumentType(formats strfmt.Registry) error {
	if typeutils.IsZero(m.InstrumentType) { // not required
		return nil
	}

	// value enum
	if err := m.validateInstrumentTypeEnum("instrumentType", "body", m.InstrumentType); err != nil {
		return err
	}

	return nil
}

var staticDataTypeNotationPropEnum []any

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["XXX","XXC","XXM","XXP","XXU"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		staticDataTypeNotationPropEnum = append(staticDataTypeNotationPropEnum, v)
	}
}

const (

	// StaticDataNotationXXX captures enum value "XXX"
	StaticDataNotationXXX string = "XXX"

	// StaticDataNotationXXC captures enum value "XXC"
	StaticDataNotationXXC string = "XXC"

	// StaticDataNotationXXM captures enum value "XXM"
	StaticDataNotationXXM string = "XXM"

	// StaticDataNotationXXP captures enum value "XXP"
	StaticDataNotationXXP string = "XXP"

	// StaticDataNotationXXU captures enum value "XXU"
	StaticDataNotationXXU string = "XXU"
)

// prop value enum
func (m *StaticData) validateNotationEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, staticDataTypeNotationPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *StaticData) validateNotation(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Notation) { // not required
		return nil
	}

	// value enum
	if err := m.validateNotationEnum("notation", "body", m.Notation); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this static data based on the context it is used
func (m *StaticData) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateCurrency(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateFundRedemptionLimited(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateInstrumentType(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateKidAvailable(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateNotation(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidatePriipsRelevant(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateShippingWaiverRequired(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *StaticData) contextValidateCurrency(ctx context.Context, formats strfmt.Registry) error {

	if m.Currency != nil {

		if typeutils.IsZero(m.Currency) { // not required
			return nil
		}

		if err := m.Currency.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("currency")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("currency")
			}

			return err
		}
	}

	return nil
}

func (m *StaticData) contextValidateFundRedemptionLimited(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "fundRedemptionLimited", "body", m.FundRedemptionLimited); err != nil {
		return err
	}

	return nil
}

func (m *StaticData) contextValidateInstrumentType(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "instrumentType", "body", m.InstrumentType); err != nil {
		return err
	}

	return nil
}

func (m *StaticData) contextValidateKidAvailable(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "kidAvailable", "body", m.KidAvailable); err != nil {
		return err
	}

	return nil
}

func (m *StaticData) contextValidateNotation(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "notation", "body", m.Notation); err != nil {
		return err
	}

	return nil
}

func (m *StaticData) contextValidatePriipsRelevant(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "priipsRelevant", "body", m.PriipsRelevant); err != nil {
		return err
	}

	return nil
}

func (m *StaticData) contextValidateShippingWaiverRequired(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "shippingWaiverRequired", "body", m.ShippingWaiverRequired); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *StaticData) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *StaticData) UnmarshalBinary(b []byte) error {
	var res StaticData
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
