// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
)

// TotalCostBlock Model for a total cost block including total cost entries segregated as: E (own service costs of bank), F (external service costs), and P (product costs).
//
// swagger:model TotalCostBlock
type TotalCostBlock struct {

	// Total cost entry for external service costs (F)
	// Read Only: true
	ExternalCosts *TotalCostEntry `json:"externalCosts,omitempty"`

	// Total cost entry for product costs (P)
	// Read Only: true
	ProductCosts *TotalCostEntry `json:"productCosts,omitempty"`

	// Total cost entry for own service costs of bank (E)
	// Read Only: true
	ServiceCosts *TotalCostEntry `json:"serviceCosts,omitempty"`

	// Total amount of inducements for own service costs of bank
	// Read Only: true
	ServiceInducement *AmountValue `json:"serviceInducement,omitempty"`
}

// Validate validates this total cost block
func (m *TotalCostBlock) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateExternalCosts(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProductCosts(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateServiceCosts(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateServiceInducement(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TotalCostBlock) validateExternalCosts(formats strfmt.Registry) error {
	if typeutils.IsZero(m.ExternalCosts) { // not required
		return nil
	}

	if m.ExternalCosts != nil {
		if err := m.ExternalCosts.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("externalCosts")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("externalCosts")
			}

			return err
		}
	}

	return nil
}

func (m *TotalCostBlock) validateProductCosts(formats strfmt.Registry) error {
	if typeutils.IsZero(m.ProductCosts) { // not required
		return nil
	}

	if m.ProductCosts != nil {
		if err := m.ProductCosts.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("productCosts")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("productCosts")
			}

			return err
		}
	}

	return nil
}

func (m *TotalCostBlock) validateServiceCosts(formats strfmt.Registry) error {
	if typeutils.IsZero(m.ServiceCosts) { // not required
		return nil
	}

	if m.ServiceCosts != nil {
		if err := m.ServiceCosts.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("serviceCosts")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("serviceCosts")
			}

			return err
		}
	}

	return nil
}

func (m *TotalCostBlock) validateServiceInducement(formats strfmt.Registry) error {
	if typeutils.IsZero(m.ServiceInducement) { // not required
		return nil
	}

	if m.ServiceInducement != nil {
		if err := m.ServiceInducement.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("serviceInducement")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("serviceInducement")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this total cost block based on the context it is used
func (m *TotalCostBlock) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateExternalCosts(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateProductCosts(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateServiceCosts(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateServiceInducement(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TotalCostBlock) contextValidateExternalCosts(ctx context.Context, formats strfmt.Registry) error {

	if m.ExternalCosts != nil {

		if typeutils.IsZero(m.ExternalCosts) { // not required
			return nil
		}

		if err := m.ExternalCosts.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("externalCosts")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("externalCosts")
			}

			return err
		}
	}

	return nil
}

func (m *TotalCostBlock) contextValidateProductCosts(ctx context.Context, formats strfmt.Registry) error {

	if m.ProductCosts != nil {

		if typeutils.IsZero(m.ProductCosts) { // not required
			return nil
		}

		if err := m.ProductCosts.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("productCosts")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("productCosts")
			}

			return err
		}
	}

	return nil
}

func (m *TotalCostBlock) contextValidateServiceCosts(ctx context.Context, formats strfmt.Registry) error {

	if m.ServiceCosts != nil {

		if typeutils.IsZero(m.ServiceCosts) { // not required
			return nil
		}

		if err := m.ServiceCosts.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("serviceCosts")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("serviceCosts")
			}

			return err
		}
	}

	return nil
}

func (m *TotalCostBlock) contextValidateServiceInducement(ctx context.Context, formats strfmt.Registry) error {

	if m.ServiceInducement != nil {

		if typeutils.IsZero(m.ServiceInducement) { // not required
			return nil
		}

		if err := m.ServiceInducement.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("serviceInducement")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("serviceInducement")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TotalCostBlock) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TotalCostBlock) UnmarshalBinary(b []byte) error {
	var res TotalCostBlock
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
