// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
)

// TotalHoldingCostBlock List of cost blocks over time.
//
// swagger:model TotalHoldingCostBlock
type TotalHoldingCostBlock struct {

	// Total holding cost entry for the year of the sale
	// Read Only: true
	Sales *TotalHoldingCostEntry `json:"sales,omitempty"`

	// Total holding cost entry for the first year
	// Read Only: true
	Year1 *TotalHoldingCostEntry `json:"year1,omitempty"`

	// Total holding cost entry for the second year
	// Read Only: true
	Year2 *TotalHoldingCostEntry `json:"year2,omitempty"`
}

// Validate validates this total holding cost block
func (m *TotalHoldingCostBlock) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSales(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateYear1(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateYear2(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TotalHoldingCostBlock) validateSales(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Sales) { // not required
		return nil
	}

	if m.Sales != nil {
		if err := m.Sales.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("sales")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("sales")
			}

			return err
		}
	}

	return nil
}

func (m *TotalHoldingCostBlock) validateYear1(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Year1) { // not required
		return nil
	}

	if m.Year1 != nil {
		if err := m.Year1.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("year1")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("year1")
			}

			return err
		}
	}

	return nil
}

func (m *TotalHoldingCostBlock) validateYear2(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Year2) { // not required
		return nil
	}

	if m.Year2 != nil {
		if err := m.Year2.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("year2")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("year2")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this total holding cost block based on the context it is used
func (m *TotalHoldingCostBlock) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateSales(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateYear1(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateYear2(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TotalHoldingCostBlock) contextValidateSales(ctx context.Context, formats strfmt.Registry) error {

	if m.Sales != nil {

		if typeutils.IsZero(m.Sales) { // not required
			return nil
		}

		if err := m.Sales.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("sales")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("sales")
			}

			return err
		}
	}

	return nil
}

func (m *TotalHoldingCostBlock) contextValidateYear1(ctx context.Context, formats strfmt.Registry) error {

	if m.Year1 != nil {

		if typeutils.IsZero(m.Year1) { // not required
			return nil
		}

		if err := m.Year1.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("year1")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("year1")
			}

			return err
		}
	}

	return nil
}

func (m *TotalHoldingCostBlock) contextValidateYear2(ctx context.Context, formats strfmt.Registry) error {

	if m.Year2 != nil {

		if typeutils.IsZero(m.Year2) { // not required
			return nil
		}

		if err := m.Year2.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("year2")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("year2")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TotalHoldingCostBlock) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TotalHoldingCostBlock) UnmarshalBinary(b []byte) error {
	var res TotalHoldingCostBlock
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
