// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	"encoding/json"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
	"github.com/go-openapi/validate"
)

// TotalHoldingCostEntry Model for cost block over time.
//
// swagger:model TotalHoldingCostEntry
type TotalHoldingCostEntry struct {

	// Cost in reporting currency
	// Read Only: true
	Amount *AmountValue `json:"amount,omitempty"`

	// Average return reduction per year
	// Read Only: true
	AverageReturnPA *PercentageString `json:"averageReturnPA,omitempty"`

	// Type of total holding cost entry
	// Read Only: true
	// Enum: ["IM_ERSTEN_JAHR","IM_ZWEITEN_JAHR","IM_JAHR_DER_VERAUESSERUNG"]
	Type string `json:"type,omitempty"`
}

// Validate validates this total holding cost entry
func (m *TotalHoldingCostEntry) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAmount(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateAverageReturnPA(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TotalHoldingCostEntry) validateAmount(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Amount) { // not required
		return nil
	}

	if m.Amount != nil {
		if err := m.Amount.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("amount")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("amount")
			}

			return err
		}
	}

	return nil
}

func (m *TotalHoldingCostEntry) validateAverageReturnPA(formats strfmt.Registry) error {
	if typeutils.IsZero(m.AverageReturnPA) { // not required
		return nil
	}

	if m.AverageReturnPA != nil {
		if err := m.AverageReturnPA.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("averageReturnPA")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("averageReturnPA")
			}

			return err
		}
	}

	return nil
}

var totalHoldingCostEntryTypeTypePropEnum []any

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["IM_ERSTEN_JAHR","IM_ZWEITEN_JAHR","IM_JAHR_DER_VERAUESSERUNG"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		totalHoldingCostEntryTypeTypePropEnum = append(totalHoldingCostEntryTypeTypePropEnum, v)
	}
}

const (

	// TotalHoldingCostEntryTypeIMERSTENJAHR captures enum value "IM_ERSTEN_JAHR"
	TotalHoldingCostEntryTypeIMERSTENJAHR string = "IM_ERSTEN_JAHR"

	// TotalHoldingCostEntryTypeIMZWEITENJAHR captures enum value "IM_ZWEITEN_JAHR"
	TotalHoldingCostEntryTypeIMZWEITENJAHR string = "IM_ZWEITEN_JAHR"

	// TotalHoldingCostEntryTypeIMJAHRDERVERAUESSERUNG captures enum value "IM_JAHR_DER_VERAUESSERUNG"
	TotalHoldingCostEntryTypeIMJAHRDERVERAUESSERUNG string = "IM_JAHR_DER_VERAUESSERUNG"
)

// prop value enum
func (m *TotalHoldingCostEntry) validateTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, totalHoldingCostEntryTypeTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *TotalHoldingCostEntry) validateType(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Type) { // not required
		return nil
	}

	// value enum
	if err := m.validateTypeEnum("type", "body", m.Type); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this total holding cost entry based on the context it is used
func (m *TotalHoldingCostEntry) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAmount(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateAverageReturnPA(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateType(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TotalHoldingCostEntry) contextValidateAmount(ctx context.Context, formats strfmt.Registry) error {

	if m.Amount != nil {

		if typeutils.IsZero(m.Amount) { // not required
			return nil
		}

		if err := m.Amount.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("amount")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("amount")
			}

			return err
		}
	}

	return nil
}

func (m *TotalHoldingCostEntry) contextValidateAverageReturnPA(ctx context.Context, formats strfmt.Registry) error {

	if m.AverageReturnPA != nil {

		if typeutils.IsZero(m.AverageReturnPA) { // not required
			return nil
		}

		if err := m.AverageReturnPA.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("averageReturnPA")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("averageReturnPA")
			}

			return err
		}
	}

	return nil
}

func (m *TotalHoldingCostEntry) contextValidateType(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "type", "body", m.Type); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TotalHoldingCostEntry) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TotalHoldingCostEntry) UnmarshalBinary(b []byte) error {
	var res TotalHoldingCostEntry
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
