// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	stderrors "errors"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
	"github.com/go-openapi/validate"
)

// Venue Model for a venue.
//
// swagger:model Venue
type Venue struct {

	// country
	Country string `json:"country,omitempty"`

	// currencies
	Currencies []*CurrencyString `json:"currencies"`

	// name
	Name string `json:"name,omitempty"`

	// order types
	OrderTypes map[string]OrderType `json:"orderTypes,omitempty"`

	// sides
	Sides []string `json:"sides"`

	// type
	Type string `json:"type,omitempty"`

	// validity types
	ValidityTypes []string `json:"validityTypes"`

	// venue Id
	VenueID string `json:"venueId,omitempty"`
}

// Validate validates this venue
func (m *Venue) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCurrencies(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOrderTypes(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Venue) validateCurrencies(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Currencies) { // not required
		return nil
	}

	for i := 0; i < len(m.Currencies); i++ {
		if typeutils.IsZero(m.Currencies[i]) { // not required
			continue
		}

		if m.Currencies[i] != nil {
			if err := m.Currencies[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("currencies" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("currencies" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *Venue) validateOrderTypes(formats strfmt.Registry) error {
	if typeutils.IsZero(m.OrderTypes) { // not required
		return nil
	}

	for k := range m.OrderTypes {

		if err := validate.Required("orderTypes"+"."+k, "body", m.OrderTypes[k]); err != nil {
			return err
		}
		if val, ok := m.OrderTypes[k]; ok {
			if err := val.Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("orderTypes" + "." + k)
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("orderTypes" + "." + k)
				}

				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this venue based on the context it is used
func (m *Venue) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateCurrencies(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateOrderTypes(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Venue) contextValidateCurrencies(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Currencies); i++ {

		if m.Currencies[i] != nil {

			if typeutils.IsZero(m.Currencies[i]) { // not required
				return nil
			}

			if err := m.Currencies[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("currencies" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("currencies" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *Venue) contextValidateOrderTypes(ctx context.Context, formats strfmt.Registry) error {

	for k := range m.OrderTypes {

		if val, ok := m.OrderTypes[k]; ok {
			if err := val.ContextValidate(ctx, formats); err != nil {
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *Venue) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Venue) UnmarshalBinary(b []byte) error {
	var res Venue
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
