// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/validate"
)

// VisaCardImage visa card image
//
// swagger:model VisaCardImage
type VisaCardImage struct {

	// Base filename for the files representing the image. The name has to be extended with a postfix indicating the resolution and file type, e.g. -1x.jpg. The resulting filename can be used to retrieve the image from the comdirect CMS
	// Example: visual_visamotiv_karte0002
	// Read Only: true
	ImageBaseFilename string `json:"imageBaseFilename,omitempty"`

	// Description of the image
	// Example: Schmetterling
	// Read Only: true
	ImageDescription string `json:"imageDescription,omitempty"`

	// Visa card image ID to be used in the application
	// Example: 0002
	// Read Only: true
	VisaCardImageID string `json:"visaCardImageId,omitempty"`
}

// Validate validates this visa card image
func (m *VisaCardImage) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validate this visa card image based on the context it is used
func (m *VisaCardImage) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateImageBaseFilename(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateImageDescription(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateVisaCardImageID(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *VisaCardImage) contextValidateImageBaseFilename(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "imageBaseFilename", "body", m.ImageBaseFilename); err != nil {
		return err
	}

	return nil
}

func (m *VisaCardImage) contextValidateImageDescription(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "imageDescription", "body", m.ImageDescription); err != nil {
		return err
	}

	return nil
}

func (m *VisaCardImage) contextValidateVisaCardImageID(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "visaCardImageId", "body", m.VisaCardImageID); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *VisaCardImage) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VisaCardImage) UnmarshalBinary(b []byte) error {
	var res VisaCardImage
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
