// Code generated by go-swagger; DO NOT EDIT.

package session

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/jabbrwcky/paperless-bank/internal/bank/comdirect/models"
)

// SessionV1GetSessionReader is a Reader for the SessionV1GetSession structure.
type SessionV1GetSessionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SessionV1GetSessionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewSessionV1GetSessionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewSessionV1GetSessionInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /session/clients/{user}/v1/sessions] sessionV1GetSession", response, response.Code())
	}
}

// NewSessionV1GetSessionOK creates a SessionV1GetSessionOK with default headers values
func NewSessionV1GetSessionOK() *SessionV1GetSessionOK {
	return &SessionV1GetSessionOK{}
}

/*
SessionV1GetSessionOK describes a response with status code 200, with default header values.

successful operation
*/
type SessionV1GetSessionOK struct {
	Payload []*models.Session
}

// IsSuccess returns true when this session v1 get session o k response has a 2xx status code
func (o *SessionV1GetSessionOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this session v1 get session o k response has a 3xx status code
func (o *SessionV1GetSessionOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this session v1 get session o k response has a 4xx status code
func (o *SessionV1GetSessionOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this session v1 get session o k response has a 5xx status code
func (o *SessionV1GetSessionOK) IsServerError() bool {
	return false
}

// IsCode returns true when this session v1 get session o k response a status code equal to that given
func (o *SessionV1GetSessionOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the session v1 get session o k response
func (o *SessionV1GetSessionOK) Code() int {
	return 200
}

func (o *SessionV1GetSessionOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /session/clients/{user}/v1/sessions][%d] sessionV1GetSessionOK %s", 200, payload)
}

func (o *SessionV1GetSessionOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /session/clients/{user}/v1/sessions][%d] sessionV1GetSessionOK %s", 200, payload)
}

func (o *SessionV1GetSessionOK) GetPayload() []*models.Session {
	return o.Payload
}

func (o *SessionV1GetSessionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewSessionV1GetSessionInternalServerError creates a SessionV1GetSessionInternalServerError with default headers values
func NewSessionV1GetSessionInternalServerError() *SessionV1GetSessionInternalServerError {
	return &SessionV1GetSessionInternalServerError{}
}

/*
SessionV1GetSessionInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type SessionV1GetSessionInternalServerError struct {
}

// IsSuccess returns true when this session v1 get session internal server error response has a 2xx status code
func (o *SessionV1GetSessionInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this session v1 get session internal server error response has a 3xx status code
func (o *SessionV1GetSessionInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this session v1 get session internal server error response has a 4xx status code
func (o *SessionV1GetSessionInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this session v1 get session internal server error response has a 5xx status code
func (o *SessionV1GetSessionInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this session v1 get session internal server error response a status code equal to that given
func (o *SessionV1GetSessionInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the session v1 get session internal server error response
func (o *SessionV1GetSessionInternalServerError) Code() int {
	return 500
}

func (o *SessionV1GetSessionInternalServerError) Error() string {
	return fmt.Sprintf("[GET /session/clients/{user}/v1/sessions][%d] sessionV1GetSessionInternalServerError", 500)
}

func (o *SessionV1GetSessionInternalServerError) String() string {
	return fmt.Sprintf("[GET /session/clients/{user}/v1/sessions][%d] sessionV1GetSessionInternalServerError", 500)
}

func (o *SessionV1GetSessionInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
