// Code generated by go-swagger; DO NOT EDIT.

package session

import (
	"context"
	"fmt"
	"time"

	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// New creates a new session API client.
func New(transport runtime.ContextualTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

// New creates a new session API client with basic auth credentials.
//
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - user: user for basic authentication header.
// - password: password for basic authentication header.
func NewClientWithBasicAuth(host, basePath, scheme, user, password string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BasicAuth(user, password)
	return &Client{transport: transport, formats: strfmt.Default}
}

// New creates a new session API client with a bearer token for authentication.
//
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - bearerToken: bearer token for Bearer authentication header.
func NewClientWithBearerToken(host, basePath, scheme, bearerToken string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BearerToken(bearerToken)
	return &Client{transport: transport, formats: strfmt.Default}
}

/*
Client for session API.
*/
type Client struct {
	transport runtime.ContextualTransport
	formats   strfmt.Registry
}

// ClientOption may be used to customize the behavior of Client methods.
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods.
type ClientService interface {

	// SessionV1GetSession returns the current session objects for the specified client can handle the literal user for the currently logged in client.
	SessionV1GetSession(params *SessionV1GetSessionParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*SessionV1GetSessionOK, error)

	// SessionV1GetSessionContext returns the current session objects for the specified client can handle the literal user for the currently logged in client.
	SessionV1GetSessionContext(ctx context.Context, params *SessionV1GetSessionParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*SessionV1GetSessionOK, error)

	// SessionV1PatchSession writes updates to a session.
	SessionV1PatchSession(params *SessionV1PatchSessionParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*SessionV1PatchSessionOK, error)

	// SessionV1PatchSessionContext writes updates to a session.
	SessionV1PatchSessionContext(ctx context.Context, params *SessionV1PatchSessionParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*SessionV1PatchSessionOK, error)

	// SessionV1PostSessionValidation validates the input and checks if the client is able to update the current session an activated session t a n cannot be deactivated in the current session it is necessary to provide a t a n when patching the activation of the session t a n.
	SessionV1PostSessionValidation(params *SessionV1PostSessionValidationParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*SessionV1PostSessionValidationOK, error)

	// SessionV1PostSessionValidationContext validates the input and checks if the client is able to update the current session an activated session t a n cannot be deactivated in the current session it is necessary to provide a t a n when patching the activation of the session t a n.
	SessionV1PostSessionValidationContext(ctx context.Context, params *SessionV1PostSessionValidationParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*SessionV1PostSessionValidationOK, error)

	SetTransport(transport runtime.ContextualTransport)
}

/*
SessionV1GetSessionreturns the current session objects for the specified client can handle the literal user for the currently logged in client.

This method does not support injected context.
However, timeout and opentracing contexts are honored whenever enabled.

If you need to pass a specific context, use [Client.SessionV1GetSessionContext] instead.
*/
func (a *Client) SessionV1GetSession(params *SessionV1GetSessionParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*SessionV1GetSessionOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.SessionV1GetSessionContext(ctx, params, authInfo, opts...)
}

/*
SessionV1GetSessionContextreturns the current session objects for the specified client can handle the literal user for the currently logged in client.

Do not use the deprecated [SessionV1GetSessionParams.Context] with this method: it would be ignored.
*/
func (a *Client) SessionV1GetSessionContext(ctx context.Context, params *SessionV1GetSessionParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*SessionV1GetSessionOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewSessionV1GetSessionParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "sessionV1GetSession",
		Method:             "GET",
		PathPattern:        "/session/clients/{user}/v1/sessions",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &SessionV1GetSessionReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*SessionV1GetSessionOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for sessionV1GetSession: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
SessionV1PatchSessionwrites updates to a session.

This method does not support injected context.
However, timeout and opentracing contexts are honored whenever enabled.

If you need to pass a specific context, use [Client.SessionV1PatchSessionContext] instead.
*/
func (a *Client) SessionV1PatchSession(params *SessionV1PatchSessionParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*SessionV1PatchSessionOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.SessionV1PatchSessionContext(ctx, params, authInfo, opts...)
}

/*
SessionV1PatchSessionContextwrites updates to a session.

Do not use the deprecated [SessionV1PatchSessionParams.Context] with this method: it would be ignored.
*/
func (a *Client) SessionV1PatchSessionContext(ctx context.Context, params *SessionV1PatchSessionParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*SessionV1PatchSessionOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewSessionV1PatchSessionParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "sessionV1PatchSession",
		Method:             "PATCH",
		PathPattern:        "/session/clients/{user}/v1/sessions/{session}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &SessionV1PatchSessionReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*SessionV1PatchSessionOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for sessionV1PatchSession: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
SessionV1PostSessionValidationvalidates the input and checks if the client is able to update the current session an activated session t a n cannot be deactivated in the current session it is necessary to provide a t a n when patching the activation of the session t a n.

This method does not support injected context.
However, timeout and opentracing contexts are honored whenever enabled.

If you need to pass a specific context, use [Client.SessionV1PostSessionValidationContext] instead.
*/
func (a *Client) SessionV1PostSessionValidation(params *SessionV1PostSessionValidationParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*SessionV1PostSessionValidationOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.SessionV1PostSessionValidationContext(ctx, params, authInfo, opts...)
}

/*
SessionV1PostSessionValidationContextvalidates the input and checks if the client is able to update the current session an activated session t a n cannot be deactivated in the current session it is necessary to provide a t a n when patching the activation of the session t a n.

Do not use the deprecated [SessionV1PostSessionValidationParams.Context] with this method: it would be ignored.
*/
func (a *Client) SessionV1PostSessionValidationContext(ctx context.Context, params *SessionV1PostSessionValidationParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*SessionV1PostSessionValidationOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewSessionV1PostSessionValidationParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "sessionV1PostSessionValidation",
		Method:             "POST",
		PathPattern:        "/session/clients/{user}/v1/sessions/{session}/validate",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &SessionV1PostSessionValidationReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*SessionV1PostSessionValidationOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for sessionV1PostSessionValidation: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ContextualTransport) {
	a.transport = transport
}

// innerParams captures internal fields so they don't conflict with user-supplied parameters.
type innerParams struct {
	timeout time.Duration

	// Deprecated: use the operation call with context to pass the context instead of [SessionParams].
	ctx context.Context
}
