// Code generated by go-swagger; DO NOT EDIT.

package session

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewSessionV1GetSessionParams creates a new SessionV1GetSessionParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSessionV1GetSessionParams() *SessionV1GetSessionParams {
	return NewSessionV1GetSessionParamsWithTimeout(cr.DefaultTimeout)
}

// NewSessionV1GetSessionParamsWithTimeout creates a new SessionV1GetSessionParams object
// with the ability to set a timeout on a request.
func NewSessionV1GetSessionParamsWithTimeout(timeout time.Duration) *SessionV1GetSessionParams {
	return &SessionV1GetSessionParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewSessionV1GetSessionParamsWithContext creates a new SessionV1GetSessionParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [SessionV1GetSessionParams].
func NewSessionV1GetSessionParamsWithContext(ctx context.Context) *SessionV1GetSessionParams {
	return &SessionV1GetSessionParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewSessionV1GetSessionParamsWithHTTPClient creates a new SessionV1GetSessionParams object
// with the ability to set a custom HTTPClient for a request.
func NewSessionV1GetSessionParamsWithHTTPClient(client *http.Client) *SessionV1GetSessionParams {
	return &SessionV1GetSessionParams{
		HTTPClient: client,
	}
}

/*
SessionV1GetSessionParams contains all the parameters to send to the API endpoint

	for the session v1 get session operation.

	Typically these are written to a http.Request.
*/
type SessionV1GetSessionParams struct {

	/* User.

	   The literal "user" or the UUID of the client.
	*/
	User string

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the session v1 get session params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SessionV1GetSessionParams) WithDefaults() *SessionV1GetSessionParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the session v1 get session params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SessionV1GetSessionParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the session v1 get session params.
func (o *SessionV1GetSessionParams) WithTimeout(timeout time.Duration) *SessionV1GetSessionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the session v1 get session params.
func (o *SessionV1GetSessionParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the session v1 get session params.
//
// Deprecated: use the operation call with context to pass the context instead of [SessionV1GetSessionParams].
func (o *SessionV1GetSessionParams) WithContext(ctx context.Context) *SessionV1GetSessionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the session v1 get session params.
//
// Deprecated: use the operation call with context to pass the context instead of [SessionV1GetSessionParams].
func (o *SessionV1GetSessionParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the session v1 get session params.
func (o *SessionV1GetSessionParams) WithHTTPClient(client *http.Client) *SessionV1GetSessionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the session v1 get session params.
func (o *SessionV1GetSessionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUser adds the user to the session v1 get session params.
func (o *SessionV1GetSessionParams) WithUser(user string) *SessionV1GetSessionParams {
	o.SetUser(user)
	return o
}

// SetUser adds the user to the session v1 get session params.
func (o *SessionV1GetSessionParams) SetUser(user string) {
	o.User = user
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *SessionV1GetSessionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	// path param user
	if err := r.SetPathParam("user", o.User); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
