// Code generated by go-swagger; DO NOT EDIT.

package session

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/jabbrwcky/paperless-bank/internal/bank/comdirect/models"
)

// SessionV1PatchSessionReader is a Reader for the SessionV1PatchSession structure.
type SessionV1PatchSessionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SessionV1PatchSessionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewSessionV1PatchSessionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 422:
		result := NewSessionV1PatchSessionUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewSessionV1PatchSessionInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[PATCH /session/clients/{user}/v1/sessions/{session}] sessionV1PatchSession", response, response.Code())
	}
}

// NewSessionV1PatchSessionOK creates a SessionV1PatchSessionOK with default headers values
func NewSessionV1PatchSessionOK() *SessionV1PatchSessionOK {
	return &SessionV1PatchSessionOK{}
}

/*
SessionV1PatchSessionOK describes a response with status code 200, with default header values.

successful operation
*/
type SessionV1PatchSessionOK struct {
	Payload *models.Session
}

// IsSuccess returns true when this session v1 patch session o k response has a 2xx status code
func (o *SessionV1PatchSessionOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this session v1 patch session o k response has a 3xx status code
func (o *SessionV1PatchSessionOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this session v1 patch session o k response has a 4xx status code
func (o *SessionV1PatchSessionOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this session v1 patch session o k response has a 5xx status code
func (o *SessionV1PatchSessionOK) IsServerError() bool {
	return false
}

// IsCode returns true when this session v1 patch session o k response a status code equal to that given
func (o *SessionV1PatchSessionOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the session v1 patch session o k response
func (o *SessionV1PatchSessionOK) Code() int {
	return 200
}

func (o *SessionV1PatchSessionOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /session/clients/{user}/v1/sessions/{session}][%d] sessionV1PatchSessionOK %s", 200, payload)
}

func (o *SessionV1PatchSessionOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /session/clients/{user}/v1/sessions/{session}][%d] sessionV1PatchSessionOK %s", 200, payload)
}

func (o *SessionV1PatchSessionOK) GetPayload() *models.Session {
	return o.Payload
}

func (o *SessionV1PatchSessionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Session)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewSessionV1PatchSessionUnprocessableEntity creates a SessionV1PatchSessionUnprocessableEntity with default headers values
func NewSessionV1PatchSessionUnprocessableEntity() *SessionV1PatchSessionUnprocessableEntity {
	return &SessionV1PatchSessionUnprocessableEntity{}
}

/*
SessionV1PatchSessionUnprocessableEntity describes a response with status code 422, with default header values.

Unprocessable Entity
*/
type SessionV1PatchSessionUnprocessableEntity struct {
}

// IsSuccess returns true when this session v1 patch session unprocessable entity response has a 2xx status code
func (o *SessionV1PatchSessionUnprocessableEntity) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this session v1 patch session unprocessable entity response has a 3xx status code
func (o *SessionV1PatchSessionUnprocessableEntity) IsRedirect() bool {
	return false
}

// IsClientError returns true when this session v1 patch session unprocessable entity response has a 4xx status code
func (o *SessionV1PatchSessionUnprocessableEntity) IsClientError() bool {
	return true
}

// IsServerError returns true when this session v1 patch session unprocessable entity response has a 5xx status code
func (o *SessionV1PatchSessionUnprocessableEntity) IsServerError() bool {
	return false
}

// IsCode returns true when this session v1 patch session unprocessable entity response a status code equal to that given
func (o *SessionV1PatchSessionUnprocessableEntity) IsCode(code int) bool {
	return code == 422
}

// Code gets the status code for the session v1 patch session unprocessable entity response
func (o *SessionV1PatchSessionUnprocessableEntity) Code() int {
	return 422
}

func (o *SessionV1PatchSessionUnprocessableEntity) Error() string {
	return fmt.Sprintf("[PATCH /session/clients/{user}/v1/sessions/{session}][%d] sessionV1PatchSessionUnprocessableEntity", 422)
}

func (o *SessionV1PatchSessionUnprocessableEntity) String() string {
	return fmt.Sprintf("[PATCH /session/clients/{user}/v1/sessions/{session}][%d] sessionV1PatchSessionUnprocessableEntity", 422)
}

func (o *SessionV1PatchSessionUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSessionV1PatchSessionInternalServerError creates a SessionV1PatchSessionInternalServerError with default headers values
func NewSessionV1PatchSessionInternalServerError() *SessionV1PatchSessionInternalServerError {
	return &SessionV1PatchSessionInternalServerError{}
}

/*
SessionV1PatchSessionInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type SessionV1PatchSessionInternalServerError struct {
}

// IsSuccess returns true when this session v1 patch session internal server error response has a 2xx status code
func (o *SessionV1PatchSessionInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this session v1 patch session internal server error response has a 3xx status code
func (o *SessionV1PatchSessionInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this session v1 patch session internal server error response has a 4xx status code
func (o *SessionV1PatchSessionInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this session v1 patch session internal server error response has a 5xx status code
func (o *SessionV1PatchSessionInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this session v1 patch session internal server error response a status code equal to that given
func (o *SessionV1PatchSessionInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the session v1 patch session internal server error response
func (o *SessionV1PatchSessionInternalServerError) Code() int {
	return 500
}

func (o *SessionV1PatchSessionInternalServerError) Error() string {
	return fmt.Sprintf("[PATCH /session/clients/{user}/v1/sessions/{session}][%d] sessionV1PatchSessionInternalServerError", 500)
}

func (o *SessionV1PatchSessionInternalServerError) String() string {
	return fmt.Sprintf("[PATCH /session/clients/{user}/v1/sessions/{session}][%d] sessionV1PatchSessionInternalServerError", 500)
}

func (o *SessionV1PatchSessionInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
