// Code generated by go-swagger; DO NOT EDIT.

package session

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/jabbrwcky/paperless-bank/internal/bank/comdirect/models"
)

// NewSessionV1PatchSessionParams creates a new SessionV1PatchSessionParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSessionV1PatchSessionParams() *SessionV1PatchSessionParams {
	return NewSessionV1PatchSessionParamsWithTimeout(cr.DefaultTimeout)
}

// NewSessionV1PatchSessionParamsWithTimeout creates a new SessionV1PatchSessionParams object
// with the ability to set a timeout on a request.
func NewSessionV1PatchSessionParamsWithTimeout(timeout time.Duration) *SessionV1PatchSessionParams {
	return &SessionV1PatchSessionParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewSessionV1PatchSessionParamsWithContext creates a new SessionV1PatchSessionParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [SessionV1PatchSessionParams].
func NewSessionV1PatchSessionParamsWithContext(ctx context.Context) *SessionV1PatchSessionParams {
	return &SessionV1PatchSessionParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewSessionV1PatchSessionParamsWithHTTPClient creates a new SessionV1PatchSessionParams object
// with the ability to set a custom HTTPClient for a request.
func NewSessionV1PatchSessionParamsWithHTTPClient(client *http.Client) *SessionV1PatchSessionParams {
	return &SessionV1PatchSessionParams{
		HTTPClient: client,
	}
}

/*
SessionV1PatchSessionParams contains all the parameters to send to the API endpoint

	for the session v1 patch session operation.

	Typically these are written to a http.Request.
*/
type SessionV1PatchSessionParams struct {

	// Body.
	Body *models.Session

	/* Session.

	   Reference to the session (UUID)
	*/
	Session string

	/* User.

	   The literal "user" or the UUID of the client.
	*/
	User string

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the session v1 patch session params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SessionV1PatchSessionParams) WithDefaults() *SessionV1PatchSessionParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the session v1 patch session params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SessionV1PatchSessionParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the session v1 patch session params.
func (o *SessionV1PatchSessionParams) WithTimeout(timeout time.Duration) *SessionV1PatchSessionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the session v1 patch session params.
func (o *SessionV1PatchSessionParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the session v1 patch session params.
//
// Deprecated: use the operation call with context to pass the context instead of [SessionV1PatchSessionParams].
func (o *SessionV1PatchSessionParams) WithContext(ctx context.Context) *SessionV1PatchSessionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the session v1 patch session params.
//
// Deprecated: use the operation call with context to pass the context instead of [SessionV1PatchSessionParams].
func (o *SessionV1PatchSessionParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the session v1 patch session params.
func (o *SessionV1PatchSessionParams) WithHTTPClient(client *http.Client) *SessionV1PatchSessionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the session v1 patch session params.
func (o *SessionV1PatchSessionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the session v1 patch session params.
func (o *SessionV1PatchSessionParams) WithBody(body *models.Session) *SessionV1PatchSessionParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the session v1 patch session params.
func (o *SessionV1PatchSessionParams) SetBody(body *models.Session) {
	o.Body = body
}

// WithSession adds the session to the session v1 patch session params.
func (o *SessionV1PatchSessionParams) WithSession(session string) *SessionV1PatchSessionParams {
	o.SetSession(session)
	return o
}

// SetSession adds the session to the session v1 patch session params.
func (o *SessionV1PatchSessionParams) SetSession(session string) {
	o.Session = session
}

// WithUser adds the user to the session v1 patch session params.
func (o *SessionV1PatchSessionParams) WithUser(user string) *SessionV1PatchSessionParams {
	o.SetUser(user)
	return o
}

// SetUser adds the user to the session v1 patch session params.
func (o *SessionV1PatchSessionParams) SetUser(user string) {
	o.User = user
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *SessionV1PatchSessionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param session
	if err := r.SetPathParam("session", o.Session); err != nil {
		return err
	}

	// path param user
	if err := r.SetPathParam("user", o.User); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
