// Code generated by go-swagger; DO NOT EDIT.

package session

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/jabbrwcky/paperless-bank/internal/bank/comdirect/models"
)

// SessionV1PostSessionValidationReader is a Reader for the SessionV1PostSessionValidation structure.
type SessionV1PostSessionValidationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SessionV1PostSessionValidationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewSessionV1PostSessionValidationOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 422:
		result := NewSessionV1PostSessionValidationUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewSessionV1PostSessionValidationInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /session/clients/{user}/v1/sessions/{session}/validate] sessionV1PostSessionValidation", response, response.Code())
	}
}

// NewSessionV1PostSessionValidationOK creates a SessionV1PostSessionValidationOK with default headers values
func NewSessionV1PostSessionValidationOK() *SessionV1PostSessionValidationOK {
	return &SessionV1PostSessionValidationOK{}
}

/*
SessionV1PostSessionValidationOK describes a response with status code 200, with default header values.

successful operation
*/
type SessionV1PostSessionValidationOK struct {
	Payload *models.Session
}

// IsSuccess returns true when this session v1 post session validation o k response has a 2xx status code
func (o *SessionV1PostSessionValidationOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this session v1 post session validation o k response has a 3xx status code
func (o *SessionV1PostSessionValidationOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this session v1 post session validation o k response has a 4xx status code
func (o *SessionV1PostSessionValidationOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this session v1 post session validation o k response has a 5xx status code
func (o *SessionV1PostSessionValidationOK) IsServerError() bool {
	return false
}

// IsCode returns true when this session v1 post session validation o k response a status code equal to that given
func (o *SessionV1PostSessionValidationOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the session v1 post session validation o k response
func (o *SessionV1PostSessionValidationOK) Code() int {
	return 200
}

func (o *SessionV1PostSessionValidationOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /session/clients/{user}/v1/sessions/{session}/validate][%d] sessionV1PostSessionValidationOK %s", 200, payload)
}

func (o *SessionV1PostSessionValidationOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /session/clients/{user}/v1/sessions/{session}/validate][%d] sessionV1PostSessionValidationOK %s", 200, payload)
}

func (o *SessionV1PostSessionValidationOK) GetPayload() *models.Session {
	return o.Payload
}

func (o *SessionV1PostSessionValidationOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Session)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewSessionV1PostSessionValidationUnprocessableEntity creates a SessionV1PostSessionValidationUnprocessableEntity with default headers values
func NewSessionV1PostSessionValidationUnprocessableEntity() *SessionV1PostSessionValidationUnprocessableEntity {
	return &SessionV1PostSessionValidationUnprocessableEntity{}
}

/*
SessionV1PostSessionValidationUnprocessableEntity describes a response with status code 422, with default header values.

Unprocessable Entity
*/
type SessionV1PostSessionValidationUnprocessableEntity struct {
}

// IsSuccess returns true when this session v1 post session validation unprocessable entity response has a 2xx status code
func (o *SessionV1PostSessionValidationUnprocessableEntity) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this session v1 post session validation unprocessable entity response has a 3xx status code
func (o *SessionV1PostSessionValidationUnprocessableEntity) IsRedirect() bool {
	return false
}

// IsClientError returns true when this session v1 post session validation unprocessable entity response has a 4xx status code
func (o *SessionV1PostSessionValidationUnprocessableEntity) IsClientError() bool {
	return true
}

// IsServerError returns true when this session v1 post session validation unprocessable entity response has a 5xx status code
func (o *SessionV1PostSessionValidationUnprocessableEntity) IsServerError() bool {
	return false
}

// IsCode returns true when this session v1 post session validation unprocessable entity response a status code equal to that given
func (o *SessionV1PostSessionValidationUnprocessableEntity) IsCode(code int) bool {
	return code == 422
}

// Code gets the status code for the session v1 post session validation unprocessable entity response
func (o *SessionV1PostSessionValidationUnprocessableEntity) Code() int {
	return 422
}

func (o *SessionV1PostSessionValidationUnprocessableEntity) Error() string {
	return fmt.Sprintf("[POST /session/clients/{user}/v1/sessions/{session}/validate][%d] sessionV1PostSessionValidationUnprocessableEntity", 422)
}

func (o *SessionV1PostSessionValidationUnprocessableEntity) String() string {
	return fmt.Sprintf("[POST /session/clients/{user}/v1/sessions/{session}/validate][%d] sessionV1PostSessionValidationUnprocessableEntity", 422)
}

func (o *SessionV1PostSessionValidationUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSessionV1PostSessionValidationInternalServerError creates a SessionV1PostSessionValidationInternalServerError with default headers values
func NewSessionV1PostSessionValidationInternalServerError() *SessionV1PostSessionValidationInternalServerError {
	return &SessionV1PostSessionValidationInternalServerError{}
}

/*
SessionV1PostSessionValidationInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type SessionV1PostSessionValidationInternalServerError struct {
}

// IsSuccess returns true when this session v1 post session validation internal server error response has a 2xx status code
func (o *SessionV1PostSessionValidationInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this session v1 post session validation internal server error response has a 3xx status code
func (o *SessionV1PostSessionValidationInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this session v1 post session validation internal server error response has a 4xx status code
func (o *SessionV1PostSessionValidationInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this session v1 post session validation internal server error response has a 5xx status code
func (o *SessionV1PostSessionValidationInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this session v1 post session validation internal server error response a status code equal to that given
func (o *SessionV1PostSessionValidationInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the session v1 post session validation internal server error response
func (o *SessionV1PostSessionValidationInternalServerError) Code() int {
	return 500
}

func (o *SessionV1PostSessionValidationInternalServerError) Error() string {
	return fmt.Sprintf("[POST /session/clients/{user}/v1/sessions/{session}/validate][%d] sessionV1PostSessionValidationInternalServerError", 500)
}

func (o *SessionV1PostSessionValidationInternalServerError) String() string {
	return fmt.Sprintf("[POST /session/clients/{user}/v1/sessions/{session}/validate][%d] sessionV1PostSessionValidationInternalServerError", 500)
}

func (o *SessionV1PostSessionValidationInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
